/*
 * Zernio API
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.zernio.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.zernio.model.CreateLeadFormBodyContextCard;
import dev.zernio.model.CreateLeadFormBodyLegalContent;
import dev.zernio.model.LeadGenFormQuestion;
import java.net.URI;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import dev.zernio.ApiClient;
/**
 * CreateLeadFormBody
 */
@JsonPropertyOrder({
  CreateLeadFormBody.JSON_PROPERTY_ACCOUNT_ID,
  CreateLeadFormBody.JSON_PROPERTY_NAME,
  CreateLeadFormBody.JSON_PROPERTY_QUESTIONS,
  CreateLeadFormBody.JSON_PROPERTY_PRIVACY_POLICY_URL,
  CreateLeadFormBody.JSON_PROPERTY_PRIVACY_POLICY_LINK_TEXT,
  CreateLeadFormBody.JSON_PROPERTY_FOLLOW_UP_ACTION_URL,
  CreateLeadFormBody.JSON_PROPERTY_LOCALE,
  CreateLeadFormBody.JSON_PROPERTY_THANK_YOU_TITLE,
  CreateLeadFormBody.JSON_PROPERTY_THANK_YOU_BODY,
  CreateLeadFormBody.JSON_PROPERTY_THANK_YOU_BUTTON_TEXT,
  CreateLeadFormBody.JSON_PROPERTY_THANK_YOU_BUTTON_TYPE,
  CreateLeadFormBody.JSON_PROPERTY_THANK_YOU_WEBSITE_URL,
  CreateLeadFormBody.JSON_PROPERTY_IS_OPTIMIZED_FOR_QUALITY,
  CreateLeadFormBody.JSON_PROPERTY_CONTEXT_CARD,
  CreateLeadFormBody.JSON_PROPERTY_LEGAL_CONTENT,
  CreateLeadFormBody.JSON_PROPERTY_TRACKING_PARAMETERS,
  CreateLeadFormBody.JSON_PROPERTY_QUESTION_PAGE_CUSTOM_HEADLINE,
  CreateLeadFormBody.JSON_PROPERTY_ALLOW_ORGANIC_LEAD,
  CreateLeadFormBody.JSON_PROPERTY_BLOCK_DISPLAY_FOR_NON_TARGETED_VIEWER
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-03T11:25:43.942041687Z[Etc/UTC]", comments = "Generator version: 7.19.0")
public class CreateLeadFormBody {
  public static final String JSON_PROPERTY_ACCOUNT_ID = "accountId";
  @javax.annotation.Nonnull
  private String accountId;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nonnull
  private String name;

  public static final String JSON_PROPERTY_QUESTIONS = "questions";
  @javax.annotation.Nonnull
  private List<LeadGenFormQuestion> questions = new ArrayList<>();

  public static final String JSON_PROPERTY_PRIVACY_POLICY_URL = "privacyPolicyUrl";
  @javax.annotation.Nonnull
  private URI privacyPolicyUrl;

  public static final String JSON_PROPERTY_PRIVACY_POLICY_LINK_TEXT = "privacyPolicyLinkText";
  @javax.annotation.Nullable
  private String privacyPolicyLinkText;

  public static final String JSON_PROPERTY_FOLLOW_UP_ACTION_URL = "followUpActionUrl";
  @javax.annotation.Nullable
  private URI followUpActionUrl;

  public static final String JSON_PROPERTY_LOCALE = "locale";
  @javax.annotation.Nullable
  private String locale;

  public static final String JSON_PROPERTY_THANK_YOU_TITLE = "thankYouTitle";
  @javax.annotation.Nullable
  private String thankYouTitle;

  public static final String JSON_PROPERTY_THANK_YOU_BODY = "thankYouBody";
  @javax.annotation.Nullable
  private String thankYouBody;

  public static final String JSON_PROPERTY_THANK_YOU_BUTTON_TEXT = "thankYouButtonText";
  @javax.annotation.Nullable
  private String thankYouButtonText;

  public static final String JSON_PROPERTY_THANK_YOU_BUTTON_TYPE = "thankYouButtonType";
  @javax.annotation.Nullable
  private String thankYouButtonType;

  public static final String JSON_PROPERTY_THANK_YOU_WEBSITE_URL = "thankYouWebsiteUrl";
  @javax.annotation.Nullable
  private URI thankYouWebsiteUrl;

  public static final String JSON_PROPERTY_IS_OPTIMIZED_FOR_QUALITY = "isOptimizedForQuality";
  @javax.annotation.Nullable
  private Boolean isOptimizedForQuality;

  public static final String JSON_PROPERTY_CONTEXT_CARD = "contextCard";
  @javax.annotation.Nullable
  private CreateLeadFormBodyContextCard contextCard;

  public static final String JSON_PROPERTY_LEGAL_CONTENT = "legalContent";
  @javax.annotation.Nullable
  private CreateLeadFormBodyLegalContent legalContent;

  public static final String JSON_PROPERTY_TRACKING_PARAMETERS = "trackingParameters";
  @javax.annotation.Nullable
  private Map<String, String> trackingParameters = new HashMap<>();

  public static final String JSON_PROPERTY_QUESTION_PAGE_CUSTOM_HEADLINE = "questionPageCustomHeadline";
  @javax.annotation.Nullable
  private String questionPageCustomHeadline;

  public static final String JSON_PROPERTY_ALLOW_ORGANIC_LEAD = "allowOrganicLead";
  @javax.annotation.Nullable
  private Boolean allowOrganicLead;

  public static final String JSON_PROPERTY_BLOCK_DISPLAY_FOR_NON_TARGETED_VIEWER = "blockDisplayForNonTargetedViewer";
  @javax.annotation.Nullable
  private Boolean blockDisplayForNonTargetedViewer;

  public CreateLeadFormBody() { 
  }

  public CreateLeadFormBody accountId(@javax.annotation.Nonnull String accountId) {
    this.accountId = accountId;
    return this;
  }

  /**
   * Facebook social account ID (Late SocialAccount _id).
   * @return accountId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ACCOUNT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getAccountId() {
    return accountId;
  }


  @JsonProperty(value = JSON_PROPERTY_ACCOUNT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAccountId(@javax.annotation.Nonnull String accountId) {
    this.accountId = accountId;
  }


  public CreateLeadFormBody name(@javax.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }


  public CreateLeadFormBody questions(@javax.annotation.Nonnull List<LeadGenFormQuestion> questions) {
    this.questions = questions;
    return this;
  }

  public CreateLeadFormBody addQuestionsItem(LeadGenFormQuestion questionsItem) {
    if (this.questions == null) {
      this.questions = new ArrayList<>();
    }
    this.questions.add(questionsItem);
    return this;
  }

  /**
   * Get questions
   * @return questions
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_QUESTIONS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<LeadGenFormQuestion> getQuestions() {
    return questions;
  }


  @JsonProperty(value = JSON_PROPERTY_QUESTIONS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setQuestions(@javax.annotation.Nonnull List<LeadGenFormQuestion> questions) {
    this.questions = questions;
  }


  public CreateLeadFormBody privacyPolicyUrl(@javax.annotation.Nonnull URI privacyPolicyUrl) {
    this.privacyPolicyUrl = privacyPolicyUrl;
    return this;
  }

  /**
   * Required by Meta. Must be reachable from Meta&#39;s crawler.
   * @return privacyPolicyUrl
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_PRIVACY_POLICY_URL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public URI getPrivacyPolicyUrl() {
    return privacyPolicyUrl;
  }


  @JsonProperty(value = JSON_PROPERTY_PRIVACY_POLICY_URL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPrivacyPolicyUrl(@javax.annotation.Nonnull URI privacyPolicyUrl) {
    this.privacyPolicyUrl = privacyPolicyUrl;
  }


  public CreateLeadFormBody privacyPolicyLinkText(@javax.annotation.Nullable String privacyPolicyLinkText) {
    this.privacyPolicyLinkText = privacyPolicyLinkText;
    return this;
  }

  /**
   * Get privacyPolicyLinkText
   * @return privacyPolicyLinkText
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PRIVACY_POLICY_LINK_TEXT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getPrivacyPolicyLinkText() {
    return privacyPolicyLinkText;
  }


  @JsonProperty(value = JSON_PROPERTY_PRIVACY_POLICY_LINK_TEXT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPrivacyPolicyLinkText(@javax.annotation.Nullable String privacyPolicyLinkText) {
    this.privacyPolicyLinkText = privacyPolicyLinkText;
  }


  public CreateLeadFormBody followUpActionUrl(@javax.annotation.Nullable URI followUpActionUrl) {
    this.followUpActionUrl = followUpActionUrl;
    return this;
  }

  /**
   * Get followUpActionUrl
   * @return followUpActionUrl
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FOLLOW_UP_ACTION_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public URI getFollowUpActionUrl() {
    return followUpActionUrl;
  }


  @JsonProperty(value = JSON_PROPERTY_FOLLOW_UP_ACTION_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFollowUpActionUrl(@javax.annotation.Nullable URI followUpActionUrl) {
    this.followUpActionUrl = followUpActionUrl;
  }


  public CreateLeadFormBody locale(@javax.annotation.Nullable String locale) {
    this.locale = locale;
    return this;
  }

  /**
   * Get locale
   * @return locale
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LOCALE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getLocale() {
    return locale;
  }


  @JsonProperty(value = JSON_PROPERTY_LOCALE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLocale(@javax.annotation.Nullable String locale) {
    this.locale = locale;
  }


  public CreateLeadFormBody thankYouTitle(@javax.annotation.Nullable String thankYouTitle) {
    this.thankYouTitle = thankYouTitle;
    return this;
  }

  /**
   * Get thankYouTitle
   * @return thankYouTitle
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_THANK_YOU_TITLE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getThankYouTitle() {
    return thankYouTitle;
  }


  @JsonProperty(value = JSON_PROPERTY_THANK_YOU_TITLE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setThankYouTitle(@javax.annotation.Nullable String thankYouTitle) {
    this.thankYouTitle = thankYouTitle;
  }


  public CreateLeadFormBody thankYouBody(@javax.annotation.Nullable String thankYouBody) {
    this.thankYouBody = thankYouBody;
    return this;
  }

  /**
   * Get thankYouBody
   * @return thankYouBody
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_THANK_YOU_BODY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getThankYouBody() {
    return thankYouBody;
  }


  @JsonProperty(value = JSON_PROPERTY_THANK_YOU_BODY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setThankYouBody(@javax.annotation.Nullable String thankYouBody) {
    this.thankYouBody = thankYouBody;
  }


  public CreateLeadFormBody thankYouButtonText(@javax.annotation.Nullable String thankYouButtonText) {
    this.thankYouButtonText = thankYouButtonText;
    return this;
  }

  /**
   * Get thankYouButtonText
   * @return thankYouButtonText
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_THANK_YOU_BUTTON_TEXT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getThankYouButtonText() {
    return thankYouButtonText;
  }


  @JsonProperty(value = JSON_PROPERTY_THANK_YOU_BUTTON_TEXT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setThankYouButtonText(@javax.annotation.Nullable String thankYouButtonText) {
    this.thankYouButtonText = thankYouButtonText;
  }


  public CreateLeadFormBody thankYouButtonType(@javax.annotation.Nullable String thankYouButtonType) {
    this.thankYouButtonType = thankYouButtonType;
    return this;
  }

  /**
   * Meta enum (e.g. VIEW_WEBSITE, CALL_BUSINESS, DOWNLOAD)
   * @return thankYouButtonType
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_THANK_YOU_BUTTON_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getThankYouButtonType() {
    return thankYouButtonType;
  }


  @JsonProperty(value = JSON_PROPERTY_THANK_YOU_BUTTON_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setThankYouButtonType(@javax.annotation.Nullable String thankYouButtonType) {
    this.thankYouButtonType = thankYouButtonType;
  }


  public CreateLeadFormBody thankYouWebsiteUrl(@javax.annotation.Nullable URI thankYouWebsiteUrl) {
    this.thankYouWebsiteUrl = thankYouWebsiteUrl;
    return this;
  }

  /**
   * Get thankYouWebsiteUrl
   * @return thankYouWebsiteUrl
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_THANK_YOU_WEBSITE_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public URI getThankYouWebsiteUrl() {
    return thankYouWebsiteUrl;
  }


  @JsonProperty(value = JSON_PROPERTY_THANK_YOU_WEBSITE_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setThankYouWebsiteUrl(@javax.annotation.Nullable URI thankYouWebsiteUrl) {
    this.thankYouWebsiteUrl = thankYouWebsiteUrl;
  }


  public CreateLeadFormBody isOptimizedForQuality(@javax.annotation.Nullable Boolean isOptimizedForQuality) {
    this.isOptimizedForQuality = isOptimizedForQuality;
    return this;
  }

  /**
   * Get isOptimizedForQuality
   * @return isOptimizedForQuality
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_IS_OPTIMIZED_FOR_QUALITY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getIsOptimizedForQuality() {
    return isOptimizedForQuality;
  }


  @JsonProperty(value = JSON_PROPERTY_IS_OPTIMIZED_FOR_QUALITY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsOptimizedForQuality(@javax.annotation.Nullable Boolean isOptimizedForQuality) {
    this.isOptimizedForQuality = isOptimizedForQuality;
  }


  public CreateLeadFormBody contextCard(@javax.annotation.Nullable CreateLeadFormBodyContextCard contextCard) {
    this.contextCard = contextCard;
    return this;
  }

  /**
   * Get contextCard
   * @return contextCard
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CONTEXT_CARD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public CreateLeadFormBodyContextCard getContextCard() {
    return contextCard;
  }


  @JsonProperty(value = JSON_PROPERTY_CONTEXT_CARD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContextCard(@javax.annotation.Nullable CreateLeadFormBodyContextCard contextCard) {
    this.contextCard = contextCard;
  }


  public CreateLeadFormBody legalContent(@javax.annotation.Nullable CreateLeadFormBodyLegalContent legalContent) {
    this.legalContent = legalContent;
    return this;
  }

  /**
   * Get legalContent
   * @return legalContent
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LEGAL_CONTENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public CreateLeadFormBodyLegalContent getLegalContent() {
    return legalContent;
  }


  @JsonProperty(value = JSON_PROPERTY_LEGAL_CONTENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLegalContent(@javax.annotation.Nullable CreateLeadFormBodyLegalContent legalContent) {
    this.legalContent = legalContent;
  }


  public CreateLeadFormBody trackingParameters(@javax.annotation.Nullable Map<String, String> trackingParameters) {
    this.trackingParameters = trackingParameters;
    return this;
  }

  public CreateLeadFormBody putTrackingParametersItem(String key, String trackingParametersItem) {
    if (this.trackingParameters == null) {
      this.trackingParameters = new HashMap<>();
    }
    this.trackingParameters.put(key, trackingParametersItem);
    return this;
  }

  /**
   * Up to 20 key/value pairs surfaced on every lead for attribution.
   * @return trackingParameters
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TRACKING_PARAMETERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Map<String, String> getTrackingParameters() {
    return trackingParameters;
  }


  @JsonProperty(value = JSON_PROPERTY_TRACKING_PARAMETERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTrackingParameters(@javax.annotation.Nullable Map<String, String> trackingParameters) {
    this.trackingParameters = trackingParameters;
  }


  public CreateLeadFormBody questionPageCustomHeadline(@javax.annotation.Nullable String questionPageCustomHeadline) {
    this.questionPageCustomHeadline = questionPageCustomHeadline;
    return this;
  }

  /**
   * Get questionPageCustomHeadline
   * @return questionPageCustomHeadline
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_QUESTION_PAGE_CUSTOM_HEADLINE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getQuestionPageCustomHeadline() {
    return questionPageCustomHeadline;
  }


  @JsonProperty(value = JSON_PROPERTY_QUESTION_PAGE_CUSTOM_HEADLINE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQuestionPageCustomHeadline(@javax.annotation.Nullable String questionPageCustomHeadline) {
    this.questionPageCustomHeadline = questionPageCustomHeadline;
  }


  public CreateLeadFormBody allowOrganicLead(@javax.annotation.Nullable Boolean allowOrganicLead) {
    this.allowOrganicLead = allowOrganicLead;
    return this;
  }

  /**
   * Get allowOrganicLead
   * @return allowOrganicLead
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ALLOW_ORGANIC_LEAD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getAllowOrganicLead() {
    return allowOrganicLead;
  }


  @JsonProperty(value = JSON_PROPERTY_ALLOW_ORGANIC_LEAD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAllowOrganicLead(@javax.annotation.Nullable Boolean allowOrganicLead) {
    this.allowOrganicLead = allowOrganicLead;
  }


  public CreateLeadFormBody blockDisplayForNonTargetedViewer(@javax.annotation.Nullable Boolean blockDisplayForNonTargetedViewer) {
    this.blockDisplayForNonTargetedViewer = blockDisplayForNonTargetedViewer;
    return this;
  }

  /**
   * Get blockDisplayForNonTargetedViewer
   * @return blockDisplayForNonTargetedViewer
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BLOCK_DISPLAY_FOR_NON_TARGETED_VIEWER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getBlockDisplayForNonTargetedViewer() {
    return blockDisplayForNonTargetedViewer;
  }


  @JsonProperty(value = JSON_PROPERTY_BLOCK_DISPLAY_FOR_NON_TARGETED_VIEWER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBlockDisplayForNonTargetedViewer(@javax.annotation.Nullable Boolean blockDisplayForNonTargetedViewer) {
    this.blockDisplayForNonTargetedViewer = blockDisplayForNonTargetedViewer;
  }


  /**
   * Return true if this CreateLeadFormBody object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateLeadFormBody createLeadFormBody = (CreateLeadFormBody) o;
    return Objects.equals(this.accountId, createLeadFormBody.accountId) &&
        Objects.equals(this.name, createLeadFormBody.name) &&
        Objects.equals(this.questions, createLeadFormBody.questions) &&
        Objects.equals(this.privacyPolicyUrl, createLeadFormBody.privacyPolicyUrl) &&
        Objects.equals(this.privacyPolicyLinkText, createLeadFormBody.privacyPolicyLinkText) &&
        Objects.equals(this.followUpActionUrl, createLeadFormBody.followUpActionUrl) &&
        Objects.equals(this.locale, createLeadFormBody.locale) &&
        Objects.equals(this.thankYouTitle, createLeadFormBody.thankYouTitle) &&
        Objects.equals(this.thankYouBody, createLeadFormBody.thankYouBody) &&
        Objects.equals(this.thankYouButtonText, createLeadFormBody.thankYouButtonText) &&
        Objects.equals(this.thankYouButtonType, createLeadFormBody.thankYouButtonType) &&
        Objects.equals(this.thankYouWebsiteUrl, createLeadFormBody.thankYouWebsiteUrl) &&
        Objects.equals(this.isOptimizedForQuality, createLeadFormBody.isOptimizedForQuality) &&
        Objects.equals(this.contextCard, createLeadFormBody.contextCard) &&
        Objects.equals(this.legalContent, createLeadFormBody.legalContent) &&
        Objects.equals(this.trackingParameters, createLeadFormBody.trackingParameters) &&
        Objects.equals(this.questionPageCustomHeadline, createLeadFormBody.questionPageCustomHeadline) &&
        Objects.equals(this.allowOrganicLead, createLeadFormBody.allowOrganicLead) &&
        Objects.equals(this.blockDisplayForNonTargetedViewer, createLeadFormBody.blockDisplayForNonTargetedViewer);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountId, name, questions, privacyPolicyUrl, privacyPolicyLinkText, followUpActionUrl, locale, thankYouTitle, thankYouBody, thankYouButtonText, thankYouButtonType, thankYouWebsiteUrl, isOptimizedForQuality, contextCard, legalContent, trackingParameters, questionPageCustomHeadline, allowOrganicLead, blockDisplayForNonTargetedViewer);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateLeadFormBody {\n");
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    questions: ").append(toIndentedString(questions)).append("\n");
    sb.append("    privacyPolicyUrl: ").append(toIndentedString(privacyPolicyUrl)).append("\n");
    sb.append("    privacyPolicyLinkText: ").append(toIndentedString(privacyPolicyLinkText)).append("\n");
    sb.append("    followUpActionUrl: ").append(toIndentedString(followUpActionUrl)).append("\n");
    sb.append("    locale: ").append(toIndentedString(locale)).append("\n");
    sb.append("    thankYouTitle: ").append(toIndentedString(thankYouTitle)).append("\n");
    sb.append("    thankYouBody: ").append(toIndentedString(thankYouBody)).append("\n");
    sb.append("    thankYouButtonText: ").append(toIndentedString(thankYouButtonText)).append("\n");
    sb.append("    thankYouButtonType: ").append(toIndentedString(thankYouButtonType)).append("\n");
    sb.append("    thankYouWebsiteUrl: ").append(toIndentedString(thankYouWebsiteUrl)).append("\n");
    sb.append("    isOptimizedForQuality: ").append(toIndentedString(isOptimizedForQuality)).append("\n");
    sb.append("    contextCard: ").append(toIndentedString(contextCard)).append("\n");
    sb.append("    legalContent: ").append(toIndentedString(legalContent)).append("\n");
    sb.append("    trackingParameters: ").append(toIndentedString(trackingParameters)).append("\n");
    sb.append("    questionPageCustomHeadline: ").append(toIndentedString(questionPageCustomHeadline)).append("\n");
    sb.append("    allowOrganicLead: ").append(toIndentedString(allowOrganicLead)).append("\n");
    sb.append("    blockDisplayForNonTargetedViewer: ").append(toIndentedString(blockDisplayForNonTargetedViewer)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `accountId` to the URL query string
    if (getAccountId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%saccountId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAccountId()))));
    }

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sname%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getName()))));
    }

    // add `questions` to the URL query string
    if (getQuestions() != null) {
      for (int i = 0; i < getQuestions().size(); i++) {
        if (getQuestions().get(i) != null) {
          joiner.add(getQuestions().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%squestions%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `privacyPolicyUrl` to the URL query string
    if (getPrivacyPolicyUrl() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sprivacyPolicyUrl%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPrivacyPolicyUrl()))));
    }

    // add `privacyPolicyLinkText` to the URL query string
    if (getPrivacyPolicyLinkText() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sprivacyPolicyLinkText%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPrivacyPolicyLinkText()))));
    }

    // add `followUpActionUrl` to the URL query string
    if (getFollowUpActionUrl() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sfollowUpActionUrl%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFollowUpActionUrl()))));
    }

    // add `locale` to the URL query string
    if (getLocale() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%slocale%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLocale()))));
    }

    // add `thankYouTitle` to the URL query string
    if (getThankYouTitle() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sthankYouTitle%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getThankYouTitle()))));
    }

    // add `thankYouBody` to the URL query string
    if (getThankYouBody() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sthankYouBody%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getThankYouBody()))));
    }

    // add `thankYouButtonText` to the URL query string
    if (getThankYouButtonText() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sthankYouButtonText%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getThankYouButtonText()))));
    }

    // add `thankYouButtonType` to the URL query string
    if (getThankYouButtonType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sthankYouButtonType%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getThankYouButtonType()))));
    }

    // add `thankYouWebsiteUrl` to the URL query string
    if (getThankYouWebsiteUrl() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sthankYouWebsiteUrl%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getThankYouWebsiteUrl()))));
    }

    // add `isOptimizedForQuality` to the URL query string
    if (getIsOptimizedForQuality() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sisOptimizedForQuality%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIsOptimizedForQuality()))));
    }

    // add `contextCard` to the URL query string
    if (getContextCard() != null) {
      joiner.add(getContextCard().toUrlQueryString(prefix + "contextCard" + suffix));
    }

    // add `legalContent` to the URL query string
    if (getLegalContent() != null) {
      joiner.add(getLegalContent().toUrlQueryString(prefix + "legalContent" + suffix));
    }

    // add `trackingParameters` to the URL query string
    if (getTrackingParameters() != null) {
      for (String _key : getTrackingParameters().keySet()) {
        joiner.add(String.format(java.util.Locale.ROOT, "%strackingParameters%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, _key, containerSuffix),
            getTrackingParameters().get(_key), ApiClient.urlEncode(ApiClient.valueToString(getTrackingParameters().get(_key)))));
      }
    }

    // add `questionPageCustomHeadline` to the URL query string
    if (getQuestionPageCustomHeadline() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%squestionPageCustomHeadline%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getQuestionPageCustomHeadline()))));
    }

    // add `allowOrganicLead` to the URL query string
    if (getAllowOrganicLead() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sallowOrganicLead%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAllowOrganicLead()))));
    }

    // add `blockDisplayForNonTargetedViewer` to the URL query string
    if (getBlockDisplayForNonTargetedViewer() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sblockDisplayForNonTargetedViewer%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBlockDisplayForNonTargetedViewer()))));
    }

    return joiner.toString();
  }
}

