/*
 * Zernio API
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.zernio.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.zernio.model.CreateLeadFormBodyLegalContentCustomDisclaimer;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import dev.zernio.ApiClient;
/**
 * CreateLeadFormBodyLegalContent
 */
@JsonPropertyOrder({
  CreateLeadFormBodyLegalContent.JSON_PROPERTY_CUSTOM_DISCLAIMER
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-03T11:25:43.942041687Z[Etc/UTC]", comments = "Generator version: 7.19.0")
public class CreateLeadFormBodyLegalContent {
  public static final String JSON_PROPERTY_CUSTOM_DISCLAIMER = "customDisclaimer";
  @javax.annotation.Nullable
  private CreateLeadFormBodyLegalContentCustomDisclaimer customDisclaimer;

  public CreateLeadFormBodyLegalContent() { 
  }

  public CreateLeadFormBodyLegalContent customDisclaimer(@javax.annotation.Nullable CreateLeadFormBodyLegalContentCustomDisclaimer customDisclaimer) {
    this.customDisclaimer = customDisclaimer;
    return this;
  }

  /**
   * Get customDisclaimer
   * @return customDisclaimer
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CUSTOM_DISCLAIMER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public CreateLeadFormBodyLegalContentCustomDisclaimer getCustomDisclaimer() {
    return customDisclaimer;
  }


  @JsonProperty(value = JSON_PROPERTY_CUSTOM_DISCLAIMER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCustomDisclaimer(@javax.annotation.Nullable CreateLeadFormBodyLegalContentCustomDisclaimer customDisclaimer) {
    this.customDisclaimer = customDisclaimer;
  }


  /**
   * Return true if this CreateLeadFormBody_legalContent object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateLeadFormBodyLegalContent createLeadFormBodyLegalContent = (CreateLeadFormBodyLegalContent) o;
    return Objects.equals(this.customDisclaimer, createLeadFormBodyLegalContent.customDisclaimer);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customDisclaimer);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateLeadFormBodyLegalContent {\n");
    sb.append("    customDisclaimer: ").append(toIndentedString(customDisclaimer)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `customDisclaimer` to the URL query string
    if (getCustomDisclaimer() != null) {
      joiner.add(getCustomDisclaimer().toUrlQueryString(prefix + "customDisclaimer" + suffix));
    }

    return joiner.toString();
  }
}

