/*
 * Zernio API
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package dev.zernio.api;

import dev.zernio.ApiClient;
import dev.zernio.ApiException;
import dev.zernio.ApiResponse;
import dev.zernio.Configuration;
import dev.zernio.Pair;

import dev.zernio.model.CreateLeadForm201Response;
import dev.zernio.model.CreateLeadFormBody;
import dev.zernio.model.CreateLeadFormTestLead200Response;
import dev.zernio.model.CreateLeadFormTestLeadRequest;
import dev.zernio.model.DeleteLeadForm200Response;
import dev.zernio.model.GetLeadForm200Response;
import dev.zernio.model.InlineObject;
import dev.zernio.model.ListLeadFormLeads200Response;
import dev.zernio.model.ListLeadForms200Response;
import dev.zernio.model.UpdateLeadFormRequest;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-05-03T11:25:43.942041687Z[Etc/UTC]", comments = "Generator version: 7.19.0")
public class LeadFormsApi {
  /**
   * Utility class for extending HttpRequest.Builder functionality.
   */
  private static class HttpRequestBuilderExtensions {
    /**
     * Adds additional headers to the provided HttpRequest.Builder. Useful for adding method/endpoint specific headers.
     *
     * @param builder the HttpRequest.Builder to which headers will be added
     * @param headers a map of header names and values to add; may be null
     * @return the same HttpRequest.Builder instance with the additional headers set
     */
    static HttpRequest.Builder withAdditionalHeaders(HttpRequest.Builder builder, Map<String, String> headers) {
        if (headers != null) {
            for (Map.Entry<String, String> entry : headers.entrySet()) {
                builder.header(entry.getKey(), entry.getValue());
            }
        }
        return builder;
    }
  }
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<InputStream>> memberVarAsyncResponseInterceptor;

  public LeadFormsApi() {
    this(Configuration.getDefaultApiClient());
  }

  public LeadFormsApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }


  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    InputStream responseBody = ApiClient.getResponseBody(response);
    String body = null;
    try {
      body = responseBody == null ? null : new String(responseBody.readAllBytes());
    } finally {
      if (responseBody != null) {
        responseBody.close();
      }
    }
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Download file from the given response.
   *
   * @param response Response
   * @return File
   * @throws ApiException If fail to read file content from response and write to disk
   */
  public File downloadFileFromResponse(HttpResponse<InputStream> response, InputStream responseBody) throws ApiException {
    if (responseBody == null) {
      throw new ApiException(new IOException("Response body is empty"));
    }
    try {
      File file = prepareDownloadFile(response);
      java.nio.file.Files.copy(responseBody, file.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
      return file;
    } catch (IOException e) {
      throw new ApiException(e);
    }
  }

  /**
   * <p>Prepare the file for download from the response.</p>
   *
   * @param response a {@link java.net.http.HttpResponse} object.
   * @return a {@link java.io.File} object.
   * @throws java.io.IOException if any.
   */
  private File prepareDownloadFile(HttpResponse<InputStream> response) throws IOException {
    String filename = null;
    java.util.Optional<String> contentDisposition = response.headers().firstValue("Content-Disposition");
    if (contentDisposition.isPresent() && !"".equals(contentDisposition.get())) {
      // Get filename from the Content-Disposition header.
      java.util.regex.Pattern pattern = java.util.regex.Pattern.compile("filename=['\"]?([^'\"\\s]+)['\"]?");
      java.util.regex.Matcher matcher = pattern.matcher(contentDisposition.get());
      if (matcher.find())
        filename = matcher.group(1);
    }
    File file = null;
    if (filename != null) {
      java.nio.file.Path tempDir = java.nio.file.Files.createTempDirectory("swagger-gen-native");
      java.nio.file.Path filePath = java.nio.file.Files.createFile(tempDir.resolve(filename));
      file = filePath.toFile();
      tempDir.toFile().deleteOnExit();   // best effort cleanup
      file.deleteOnExit(); // best effort cleanup
    } else {
      file = java.nio.file.Files.createTempFile("download-", "").toFile();
      file.deleteOnExit(); // best effort cleanup
    }
    return file;
  }

  /**
   * Create a Meta Lead Gen Form
   * Creates a new Instant Form on the Facebook Page tied to the given social account. The form is created in &#x60;ACTIVE&#x60; status and is immediately attachable to ads (see &#x60;leadGenFormId&#x60; on POST /v1/ads/create).  Once a form has received any leads, its questions / privacy policy / thank-you page become immutable on Meta&#39;s side; only &#x60;status&#x60; may be changed via PATCH. 
   * @param createLeadFormBody  (required)
   * @return CreateLeadForm201Response
   * @throws ApiException if fails to make API call
   */
  public CreateLeadForm201Response createLeadForm(@javax.annotation.Nonnull CreateLeadFormBody createLeadFormBody) throws ApiException {
    return createLeadForm(createLeadFormBody, null);
  }

  /**
   * Create a Meta Lead Gen Form
   * Creates a new Instant Form on the Facebook Page tied to the given social account. The form is created in &#x60;ACTIVE&#x60; status and is immediately attachable to ads (see &#x60;leadGenFormId&#x60; on POST /v1/ads/create).  Once a form has received any leads, its questions / privacy policy / thank-you page become immutable on Meta&#39;s side; only &#x60;status&#x60; may be changed via PATCH. 
   * @param createLeadFormBody  (required)
   * @param headers Optional headers to include in the request
   * @return CreateLeadForm201Response
   * @throws ApiException if fails to make API call
   */
  public CreateLeadForm201Response createLeadForm(@javax.annotation.Nonnull CreateLeadFormBody createLeadFormBody, Map<String, String> headers) throws ApiException {
    ApiResponse<CreateLeadForm201Response> localVarResponse = createLeadFormWithHttpInfo(createLeadFormBody, headers);
    return localVarResponse.getData();
  }

  /**
   * Create a Meta Lead Gen Form
   * Creates a new Instant Form on the Facebook Page tied to the given social account. The form is created in &#x60;ACTIVE&#x60; status and is immediately attachable to ads (see &#x60;leadGenFormId&#x60; on POST /v1/ads/create).  Once a form has received any leads, its questions / privacy policy / thank-you page become immutable on Meta&#39;s side; only &#x60;status&#x60; may be changed via PATCH. 
   * @param createLeadFormBody  (required)
   * @return ApiResponse&lt;CreateLeadForm201Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<CreateLeadForm201Response> createLeadFormWithHttpInfo(@javax.annotation.Nonnull CreateLeadFormBody createLeadFormBody) throws ApiException {
    return createLeadFormWithHttpInfo(createLeadFormBody, null);
  }

  /**
   * Create a Meta Lead Gen Form
   * Creates a new Instant Form on the Facebook Page tied to the given social account. The form is created in &#x60;ACTIVE&#x60; status and is immediately attachable to ads (see &#x60;leadGenFormId&#x60; on POST /v1/ads/create).  Once a form has received any leads, its questions / privacy policy / thank-you page become immutable on Meta&#39;s side; only &#x60;status&#x60; may be changed via PATCH. 
   * @param createLeadFormBody  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;CreateLeadForm201Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<CreateLeadForm201Response> createLeadFormWithHttpInfo(@javax.annotation.Nonnull CreateLeadFormBody createLeadFormBody, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = createLeadFormRequestBuilder(createLeadFormBody, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("createLeadForm", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<CreateLeadForm201Response>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        CreateLeadForm201Response responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<CreateLeadForm201Response>() {});
        

        return new ApiResponse<CreateLeadForm201Response>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder createLeadFormRequestBuilder(@javax.annotation.Nonnull CreateLeadFormBody createLeadFormBody, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'createLeadFormBody' is set
    if (createLeadFormBody == null) {
      throw new ApiException(400, "Missing the required parameter 'createLeadFormBody' when calling createLeadForm");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/ads/lead-forms";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(createLeadFormBody);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Create a synthetic test lead
   * Submits a fake lead against a form. Useful for QA, App Review demos, and exercising webhook subscribers without waiting for real ad impressions. Meta caps a form to one outstanding test lead — call DELETE on the returned id before re-submitting. 
   * @param formId  (required)
   * @param createLeadFormTestLeadRequest  (required)
   * @return CreateLeadFormTestLead200Response
   * @throws ApiException if fails to make API call
   */
  public CreateLeadFormTestLead200Response createLeadFormTestLead(@javax.annotation.Nonnull String formId, @javax.annotation.Nonnull CreateLeadFormTestLeadRequest createLeadFormTestLeadRequest) throws ApiException {
    return createLeadFormTestLead(formId, createLeadFormTestLeadRequest, null);
  }

  /**
   * Create a synthetic test lead
   * Submits a fake lead against a form. Useful for QA, App Review demos, and exercising webhook subscribers without waiting for real ad impressions. Meta caps a form to one outstanding test lead — call DELETE on the returned id before re-submitting. 
   * @param formId  (required)
   * @param createLeadFormTestLeadRequest  (required)
   * @param headers Optional headers to include in the request
   * @return CreateLeadFormTestLead200Response
   * @throws ApiException if fails to make API call
   */
  public CreateLeadFormTestLead200Response createLeadFormTestLead(@javax.annotation.Nonnull String formId, @javax.annotation.Nonnull CreateLeadFormTestLeadRequest createLeadFormTestLeadRequest, Map<String, String> headers) throws ApiException {
    ApiResponse<CreateLeadFormTestLead200Response> localVarResponse = createLeadFormTestLeadWithHttpInfo(formId, createLeadFormTestLeadRequest, headers);
    return localVarResponse.getData();
  }

  /**
   * Create a synthetic test lead
   * Submits a fake lead against a form. Useful for QA, App Review demos, and exercising webhook subscribers without waiting for real ad impressions. Meta caps a form to one outstanding test lead — call DELETE on the returned id before re-submitting. 
   * @param formId  (required)
   * @param createLeadFormTestLeadRequest  (required)
   * @return ApiResponse&lt;CreateLeadFormTestLead200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<CreateLeadFormTestLead200Response> createLeadFormTestLeadWithHttpInfo(@javax.annotation.Nonnull String formId, @javax.annotation.Nonnull CreateLeadFormTestLeadRequest createLeadFormTestLeadRequest) throws ApiException {
    return createLeadFormTestLeadWithHttpInfo(formId, createLeadFormTestLeadRequest, null);
  }

  /**
   * Create a synthetic test lead
   * Submits a fake lead against a form. Useful for QA, App Review demos, and exercising webhook subscribers without waiting for real ad impressions. Meta caps a form to one outstanding test lead — call DELETE on the returned id before re-submitting. 
   * @param formId  (required)
   * @param createLeadFormTestLeadRequest  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;CreateLeadFormTestLead200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<CreateLeadFormTestLead200Response> createLeadFormTestLeadWithHttpInfo(@javax.annotation.Nonnull String formId, @javax.annotation.Nonnull CreateLeadFormTestLeadRequest createLeadFormTestLeadRequest, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = createLeadFormTestLeadRequestBuilder(formId, createLeadFormTestLeadRequest, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("createLeadFormTestLead", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<CreateLeadFormTestLead200Response>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        CreateLeadFormTestLead200Response responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<CreateLeadFormTestLead200Response>() {});
        

        return new ApiResponse<CreateLeadFormTestLead200Response>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder createLeadFormTestLeadRequestBuilder(@javax.annotation.Nonnull String formId, @javax.annotation.Nonnull CreateLeadFormTestLeadRequest createLeadFormTestLeadRequest, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'formId' is set
    if (formId == null) {
      throw new ApiException(400, "Missing the required parameter 'formId' when calling createLeadFormTestLead");
    }
    // verify the required parameter 'createLeadFormTestLeadRequest' is set
    if (createLeadFormTestLeadRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'createLeadFormTestLeadRequest' when calling createLeadFormTestLead");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/ads/lead-forms/{formId}/test-leads"
        .replace("{formId}", ApiClient.urlEncode(formId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(createLeadFormTestLeadRequest);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Delete a Lead Gen Form
   * Deletes the form from Meta. If the form has already received leads, Meta archives it instead of hard-deleting; the response is the same either way. 
   * @param formId  (required)
   * @param accountId  (required)
   * @return DeleteLeadForm200Response
   * @throws ApiException if fails to make API call
   */
  public DeleteLeadForm200Response deleteLeadForm(@javax.annotation.Nonnull String formId, @javax.annotation.Nonnull String accountId) throws ApiException {
    return deleteLeadForm(formId, accountId, null);
  }

  /**
   * Delete a Lead Gen Form
   * Deletes the form from Meta. If the form has already received leads, Meta archives it instead of hard-deleting; the response is the same either way. 
   * @param formId  (required)
   * @param accountId  (required)
   * @param headers Optional headers to include in the request
   * @return DeleteLeadForm200Response
   * @throws ApiException if fails to make API call
   */
  public DeleteLeadForm200Response deleteLeadForm(@javax.annotation.Nonnull String formId, @javax.annotation.Nonnull String accountId, Map<String, String> headers) throws ApiException {
    ApiResponse<DeleteLeadForm200Response> localVarResponse = deleteLeadFormWithHttpInfo(formId, accountId, headers);
    return localVarResponse.getData();
  }

  /**
   * Delete a Lead Gen Form
   * Deletes the form from Meta. If the form has already received leads, Meta archives it instead of hard-deleting; the response is the same either way. 
   * @param formId  (required)
   * @param accountId  (required)
   * @return ApiResponse&lt;DeleteLeadForm200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<DeleteLeadForm200Response> deleteLeadFormWithHttpInfo(@javax.annotation.Nonnull String formId, @javax.annotation.Nonnull String accountId) throws ApiException {
    return deleteLeadFormWithHttpInfo(formId, accountId, null);
  }

  /**
   * Delete a Lead Gen Form
   * Deletes the form from Meta. If the form has already received leads, Meta archives it instead of hard-deleting; the response is the same either way. 
   * @param formId  (required)
   * @param accountId  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;DeleteLeadForm200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<DeleteLeadForm200Response> deleteLeadFormWithHttpInfo(@javax.annotation.Nonnull String formId, @javax.annotation.Nonnull String accountId, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = deleteLeadFormRequestBuilder(formId, accountId, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("deleteLeadForm", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<DeleteLeadForm200Response>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        DeleteLeadForm200Response responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<DeleteLeadForm200Response>() {});
        

        return new ApiResponse<DeleteLeadForm200Response>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder deleteLeadFormRequestBuilder(@javax.annotation.Nonnull String formId, @javax.annotation.Nonnull String accountId, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'formId' is set
    if (formId == null) {
      throw new ApiException(400, "Missing the required parameter 'formId' when calling deleteLeadForm");
    }
    // verify the required parameter 'accountId' is set
    if (accountId == null) {
      throw new ApiException(400, "Missing the required parameter 'accountId' when calling deleteLeadForm");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/ads/lead-forms/{formId}"
        .replace("{formId}", ApiClient.urlEncode(formId.toString()));

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "accountId";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("accountId", accountId));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("DELETE", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Delete a (test) lead
   * Deletes a single lead by ID. Primarily used to clear the outstanding test lead so you can submit a new one. The same Graph API call works on real leads too; for production lead deletion (GDPR/CCPA) prefer a dedicated flow. 
   * @param formId  (required)
   * @param leadId  (required)
   * @param accountId  (required)
   * @return DeleteLeadForm200Response
   * @throws ApiException if fails to make API call
   */
  public DeleteLeadForm200Response deleteLeadFormTestLead(@javax.annotation.Nonnull String formId, @javax.annotation.Nonnull String leadId, @javax.annotation.Nonnull String accountId) throws ApiException {
    return deleteLeadFormTestLead(formId, leadId, accountId, null);
  }

  /**
   * Delete a (test) lead
   * Deletes a single lead by ID. Primarily used to clear the outstanding test lead so you can submit a new one. The same Graph API call works on real leads too; for production lead deletion (GDPR/CCPA) prefer a dedicated flow. 
   * @param formId  (required)
   * @param leadId  (required)
   * @param accountId  (required)
   * @param headers Optional headers to include in the request
   * @return DeleteLeadForm200Response
   * @throws ApiException if fails to make API call
   */
  public DeleteLeadForm200Response deleteLeadFormTestLead(@javax.annotation.Nonnull String formId, @javax.annotation.Nonnull String leadId, @javax.annotation.Nonnull String accountId, Map<String, String> headers) throws ApiException {
    ApiResponse<DeleteLeadForm200Response> localVarResponse = deleteLeadFormTestLeadWithHttpInfo(formId, leadId, accountId, headers);
    return localVarResponse.getData();
  }

  /**
   * Delete a (test) lead
   * Deletes a single lead by ID. Primarily used to clear the outstanding test lead so you can submit a new one. The same Graph API call works on real leads too; for production lead deletion (GDPR/CCPA) prefer a dedicated flow. 
   * @param formId  (required)
   * @param leadId  (required)
   * @param accountId  (required)
   * @return ApiResponse&lt;DeleteLeadForm200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<DeleteLeadForm200Response> deleteLeadFormTestLeadWithHttpInfo(@javax.annotation.Nonnull String formId, @javax.annotation.Nonnull String leadId, @javax.annotation.Nonnull String accountId) throws ApiException {
    return deleteLeadFormTestLeadWithHttpInfo(formId, leadId, accountId, null);
  }

  /**
   * Delete a (test) lead
   * Deletes a single lead by ID. Primarily used to clear the outstanding test lead so you can submit a new one. The same Graph API call works on real leads too; for production lead deletion (GDPR/CCPA) prefer a dedicated flow. 
   * @param formId  (required)
   * @param leadId  (required)
   * @param accountId  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;DeleteLeadForm200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<DeleteLeadForm200Response> deleteLeadFormTestLeadWithHttpInfo(@javax.annotation.Nonnull String formId, @javax.annotation.Nonnull String leadId, @javax.annotation.Nonnull String accountId, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = deleteLeadFormTestLeadRequestBuilder(formId, leadId, accountId, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("deleteLeadFormTestLead", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<DeleteLeadForm200Response>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        DeleteLeadForm200Response responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<DeleteLeadForm200Response>() {});
        

        return new ApiResponse<DeleteLeadForm200Response>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder deleteLeadFormTestLeadRequestBuilder(@javax.annotation.Nonnull String formId, @javax.annotation.Nonnull String leadId, @javax.annotation.Nonnull String accountId, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'formId' is set
    if (formId == null) {
      throw new ApiException(400, "Missing the required parameter 'formId' when calling deleteLeadFormTestLead");
    }
    // verify the required parameter 'leadId' is set
    if (leadId == null) {
      throw new ApiException(400, "Missing the required parameter 'leadId' when calling deleteLeadFormTestLead");
    }
    // verify the required parameter 'accountId' is set
    if (accountId == null) {
      throw new ApiException(400, "Missing the required parameter 'accountId' when calling deleteLeadFormTestLead");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/ads/lead-forms/{formId}/test-leads/{leadId}"
        .replace("{formId}", ApiClient.urlEncode(formId.toString()))
        .replace("{leadId}", ApiClient.urlEncode(leadId.toString()));

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "accountId";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("accountId", accountId));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("DELETE", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get a Lead Gen Form
   * Returns full details for a single form, including questions, privacy policy, and lead counts.
   * @param formId Meta lead form ID (numeric string) (required)
   * @param accountId  (required)
   * @return GetLeadForm200Response
   * @throws ApiException if fails to make API call
   */
  public GetLeadForm200Response getLeadForm(@javax.annotation.Nonnull String formId, @javax.annotation.Nonnull String accountId) throws ApiException {
    return getLeadForm(formId, accountId, null);
  }

  /**
   * Get a Lead Gen Form
   * Returns full details for a single form, including questions, privacy policy, and lead counts.
   * @param formId Meta lead form ID (numeric string) (required)
   * @param accountId  (required)
   * @param headers Optional headers to include in the request
   * @return GetLeadForm200Response
   * @throws ApiException if fails to make API call
   */
  public GetLeadForm200Response getLeadForm(@javax.annotation.Nonnull String formId, @javax.annotation.Nonnull String accountId, Map<String, String> headers) throws ApiException {
    ApiResponse<GetLeadForm200Response> localVarResponse = getLeadFormWithHttpInfo(formId, accountId, headers);
    return localVarResponse.getData();
  }

  /**
   * Get a Lead Gen Form
   * Returns full details for a single form, including questions, privacy policy, and lead counts.
   * @param formId Meta lead form ID (numeric string) (required)
   * @param accountId  (required)
   * @return ApiResponse&lt;GetLeadForm200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<GetLeadForm200Response> getLeadFormWithHttpInfo(@javax.annotation.Nonnull String formId, @javax.annotation.Nonnull String accountId) throws ApiException {
    return getLeadFormWithHttpInfo(formId, accountId, null);
  }

  /**
   * Get a Lead Gen Form
   * Returns full details for a single form, including questions, privacy policy, and lead counts.
   * @param formId Meta lead form ID (numeric string) (required)
   * @param accountId  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;GetLeadForm200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<GetLeadForm200Response> getLeadFormWithHttpInfo(@javax.annotation.Nonnull String formId, @javax.annotation.Nonnull String accountId, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getLeadFormRequestBuilder(formId, accountId, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getLeadForm", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<GetLeadForm200Response>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        GetLeadForm200Response responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<GetLeadForm200Response>() {});
        

        return new ApiResponse<GetLeadForm200Response>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getLeadFormRequestBuilder(@javax.annotation.Nonnull String formId, @javax.annotation.Nonnull String accountId, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'formId' is set
    if (formId == null) {
      throw new ApiException(400, "Missing the required parameter 'formId' when calling getLeadForm");
    }
    // verify the required parameter 'accountId' is set
    if (accountId == null) {
      throw new ApiException(400, "Missing the required parameter 'accountId' when calling getLeadForm");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/ads/lead-forms/{formId}"
        .replace("{formId}", ApiClient.urlEncode(formId.toString()));

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "accountId";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("accountId", accountId));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * List submitted leads for a form
   * Returns leads submitted against a Lead Gen Form. The page access token on the connected account must have the &#x60;leads_retrieval&#x60; permission — if the token was minted before that scope was approved, this endpoint returns &#x60;code: scope_reconnect_required&#x60; (HTTP 422) and the customer must reconnect the Facebook account.  For real-time delivery without polling, subscribe a webhook to the &#x60;lead.received&#x60; event. 
   * @param formId  (required)
   * @param accountId  (required)
   * @param limit  (optional, default to 25)
   * @param cursor  (optional)
   * @param since Unix timestamp; only return leads created strictly after this. (optional)
   * @return ListLeadFormLeads200Response
   * @throws ApiException if fails to make API call
   */
  public ListLeadFormLeads200Response listLeadFormLeads(@javax.annotation.Nonnull String formId, @javax.annotation.Nonnull String accountId, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable String cursor, @javax.annotation.Nullable Integer since) throws ApiException {
    return listLeadFormLeads(formId, accountId, limit, cursor, since, null);
  }

  /**
   * List submitted leads for a form
   * Returns leads submitted against a Lead Gen Form. The page access token on the connected account must have the &#x60;leads_retrieval&#x60; permission — if the token was minted before that scope was approved, this endpoint returns &#x60;code: scope_reconnect_required&#x60; (HTTP 422) and the customer must reconnect the Facebook account.  For real-time delivery without polling, subscribe a webhook to the &#x60;lead.received&#x60; event. 
   * @param formId  (required)
   * @param accountId  (required)
   * @param limit  (optional, default to 25)
   * @param cursor  (optional)
   * @param since Unix timestamp; only return leads created strictly after this. (optional)
   * @param headers Optional headers to include in the request
   * @return ListLeadFormLeads200Response
   * @throws ApiException if fails to make API call
   */
  public ListLeadFormLeads200Response listLeadFormLeads(@javax.annotation.Nonnull String formId, @javax.annotation.Nonnull String accountId, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable String cursor, @javax.annotation.Nullable Integer since, Map<String, String> headers) throws ApiException {
    ApiResponse<ListLeadFormLeads200Response> localVarResponse = listLeadFormLeadsWithHttpInfo(formId, accountId, limit, cursor, since, headers);
    return localVarResponse.getData();
  }

  /**
   * List submitted leads for a form
   * Returns leads submitted against a Lead Gen Form. The page access token on the connected account must have the &#x60;leads_retrieval&#x60; permission — if the token was minted before that scope was approved, this endpoint returns &#x60;code: scope_reconnect_required&#x60; (HTTP 422) and the customer must reconnect the Facebook account.  For real-time delivery without polling, subscribe a webhook to the &#x60;lead.received&#x60; event. 
   * @param formId  (required)
   * @param accountId  (required)
   * @param limit  (optional, default to 25)
   * @param cursor  (optional)
   * @param since Unix timestamp; only return leads created strictly after this. (optional)
   * @return ApiResponse&lt;ListLeadFormLeads200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<ListLeadFormLeads200Response> listLeadFormLeadsWithHttpInfo(@javax.annotation.Nonnull String formId, @javax.annotation.Nonnull String accountId, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable String cursor, @javax.annotation.Nullable Integer since) throws ApiException {
    return listLeadFormLeadsWithHttpInfo(formId, accountId, limit, cursor, since, null);
  }

  /**
   * List submitted leads for a form
   * Returns leads submitted against a Lead Gen Form. The page access token on the connected account must have the &#x60;leads_retrieval&#x60; permission — if the token was minted before that scope was approved, this endpoint returns &#x60;code: scope_reconnect_required&#x60; (HTTP 422) and the customer must reconnect the Facebook account.  For real-time delivery without polling, subscribe a webhook to the &#x60;lead.received&#x60; event. 
   * @param formId  (required)
   * @param accountId  (required)
   * @param limit  (optional, default to 25)
   * @param cursor  (optional)
   * @param since Unix timestamp; only return leads created strictly after this. (optional)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;ListLeadFormLeads200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<ListLeadFormLeads200Response> listLeadFormLeadsWithHttpInfo(@javax.annotation.Nonnull String formId, @javax.annotation.Nonnull String accountId, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable String cursor, @javax.annotation.Nullable Integer since, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = listLeadFormLeadsRequestBuilder(formId, accountId, limit, cursor, since, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("listLeadFormLeads", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<ListLeadFormLeads200Response>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        ListLeadFormLeads200Response responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<ListLeadFormLeads200Response>() {});
        

        return new ApiResponse<ListLeadFormLeads200Response>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder listLeadFormLeadsRequestBuilder(@javax.annotation.Nonnull String formId, @javax.annotation.Nonnull String accountId, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable String cursor, @javax.annotation.Nullable Integer since, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'formId' is set
    if (formId == null) {
      throw new ApiException(400, "Missing the required parameter 'formId' when calling listLeadFormLeads");
    }
    // verify the required parameter 'accountId' is set
    if (accountId == null) {
      throw new ApiException(400, "Missing the required parameter 'accountId' when calling listLeadFormLeads");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/ads/lead-forms/{formId}/leads"
        .replace("{formId}", ApiClient.urlEncode(formId.toString()));

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "accountId";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("accountId", accountId));
    localVarQueryParameterBaseName = "limit";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("limit", limit));
    localVarQueryParameterBaseName = "cursor";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("cursor", cursor));
    localVarQueryParameterBaseName = "since";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("since", since));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * List Meta Lead Gen Forms
   * Returns Meta Instant Forms attached to the Facebook Page connected via the given social account. Forms live on Facebook Pages — Instagram lead ads reuse the linked Page under the hood, so even Instagram-only ad accounts list forms from the linked Facebook Page. Requires the Ads add-on. 
   * @param accountId Facebook social account ID (Late SocialAccount _id) (required)
   * @param limit  (optional, default to 25)
   * @param cursor Meta &#x60;paging.cursors.after&#x60; from a prior page (optional)
   * @return ListLeadForms200Response
   * @throws ApiException if fails to make API call
   */
  public ListLeadForms200Response listLeadForms(@javax.annotation.Nonnull String accountId, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable String cursor) throws ApiException {
    return listLeadForms(accountId, limit, cursor, null);
  }

  /**
   * List Meta Lead Gen Forms
   * Returns Meta Instant Forms attached to the Facebook Page connected via the given social account. Forms live on Facebook Pages — Instagram lead ads reuse the linked Page under the hood, so even Instagram-only ad accounts list forms from the linked Facebook Page. Requires the Ads add-on. 
   * @param accountId Facebook social account ID (Late SocialAccount _id) (required)
   * @param limit  (optional, default to 25)
   * @param cursor Meta &#x60;paging.cursors.after&#x60; from a prior page (optional)
   * @param headers Optional headers to include in the request
   * @return ListLeadForms200Response
   * @throws ApiException if fails to make API call
   */
  public ListLeadForms200Response listLeadForms(@javax.annotation.Nonnull String accountId, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable String cursor, Map<String, String> headers) throws ApiException {
    ApiResponse<ListLeadForms200Response> localVarResponse = listLeadFormsWithHttpInfo(accountId, limit, cursor, headers);
    return localVarResponse.getData();
  }

  /**
   * List Meta Lead Gen Forms
   * Returns Meta Instant Forms attached to the Facebook Page connected via the given social account. Forms live on Facebook Pages — Instagram lead ads reuse the linked Page under the hood, so even Instagram-only ad accounts list forms from the linked Facebook Page. Requires the Ads add-on. 
   * @param accountId Facebook social account ID (Late SocialAccount _id) (required)
   * @param limit  (optional, default to 25)
   * @param cursor Meta &#x60;paging.cursors.after&#x60; from a prior page (optional)
   * @return ApiResponse&lt;ListLeadForms200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<ListLeadForms200Response> listLeadFormsWithHttpInfo(@javax.annotation.Nonnull String accountId, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable String cursor) throws ApiException {
    return listLeadFormsWithHttpInfo(accountId, limit, cursor, null);
  }

  /**
   * List Meta Lead Gen Forms
   * Returns Meta Instant Forms attached to the Facebook Page connected via the given social account. Forms live on Facebook Pages — Instagram lead ads reuse the linked Page under the hood, so even Instagram-only ad accounts list forms from the linked Facebook Page. Requires the Ads add-on. 
   * @param accountId Facebook social account ID (Late SocialAccount _id) (required)
   * @param limit  (optional, default to 25)
   * @param cursor Meta &#x60;paging.cursors.after&#x60; from a prior page (optional)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;ListLeadForms200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<ListLeadForms200Response> listLeadFormsWithHttpInfo(@javax.annotation.Nonnull String accountId, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable String cursor, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = listLeadFormsRequestBuilder(accountId, limit, cursor, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("listLeadForms", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<ListLeadForms200Response>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        ListLeadForms200Response responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<ListLeadForms200Response>() {});
        

        return new ApiResponse<ListLeadForms200Response>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder listLeadFormsRequestBuilder(@javax.annotation.Nonnull String accountId, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable String cursor, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'accountId' is set
    if (accountId == null) {
      throw new ApiException(400, "Missing the required parameter 'accountId' when calling listLeadForms");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/ads/lead-forms";

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "accountId";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("accountId", accountId));
    localVarQueryParameterBaseName = "limit";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("limit", limit));
    localVarQueryParameterBaseName = "cursor";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("cursor", cursor));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Update a Lead Gen Form (status only)
   * Update mutable fields on an existing form. Today only &#x60;status&#x60; is mutable on Meta&#39;s side — questions / privacy_policy / thank_you_page are immutable once a form has received any leads. 
   * @param formId  (required)
   * @param updateLeadFormRequest  (required)
   * @return DeleteLeadForm200Response
   * @throws ApiException if fails to make API call
   */
  public DeleteLeadForm200Response updateLeadForm(@javax.annotation.Nonnull String formId, @javax.annotation.Nonnull UpdateLeadFormRequest updateLeadFormRequest) throws ApiException {
    return updateLeadForm(formId, updateLeadFormRequest, null);
  }

  /**
   * Update a Lead Gen Form (status only)
   * Update mutable fields on an existing form. Today only &#x60;status&#x60; is mutable on Meta&#39;s side — questions / privacy_policy / thank_you_page are immutable once a form has received any leads. 
   * @param formId  (required)
   * @param updateLeadFormRequest  (required)
   * @param headers Optional headers to include in the request
   * @return DeleteLeadForm200Response
   * @throws ApiException if fails to make API call
   */
  public DeleteLeadForm200Response updateLeadForm(@javax.annotation.Nonnull String formId, @javax.annotation.Nonnull UpdateLeadFormRequest updateLeadFormRequest, Map<String, String> headers) throws ApiException {
    ApiResponse<DeleteLeadForm200Response> localVarResponse = updateLeadFormWithHttpInfo(formId, updateLeadFormRequest, headers);
    return localVarResponse.getData();
  }

  /**
   * Update a Lead Gen Form (status only)
   * Update mutable fields on an existing form. Today only &#x60;status&#x60; is mutable on Meta&#39;s side — questions / privacy_policy / thank_you_page are immutable once a form has received any leads. 
   * @param formId  (required)
   * @param updateLeadFormRequest  (required)
   * @return ApiResponse&lt;DeleteLeadForm200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<DeleteLeadForm200Response> updateLeadFormWithHttpInfo(@javax.annotation.Nonnull String formId, @javax.annotation.Nonnull UpdateLeadFormRequest updateLeadFormRequest) throws ApiException {
    return updateLeadFormWithHttpInfo(formId, updateLeadFormRequest, null);
  }

  /**
   * Update a Lead Gen Form (status only)
   * Update mutable fields on an existing form. Today only &#x60;status&#x60; is mutable on Meta&#39;s side — questions / privacy_policy / thank_you_page are immutable once a form has received any leads. 
   * @param formId  (required)
   * @param updateLeadFormRequest  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;DeleteLeadForm200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<DeleteLeadForm200Response> updateLeadFormWithHttpInfo(@javax.annotation.Nonnull String formId, @javax.annotation.Nonnull UpdateLeadFormRequest updateLeadFormRequest, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = updateLeadFormRequestBuilder(formId, updateLeadFormRequest, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("updateLeadForm", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<DeleteLeadForm200Response>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        DeleteLeadForm200Response responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<DeleteLeadForm200Response>() {});
        

        return new ApiResponse<DeleteLeadForm200Response>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder updateLeadFormRequestBuilder(@javax.annotation.Nonnull String formId, @javax.annotation.Nonnull UpdateLeadFormRequest updateLeadFormRequest, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'formId' is set
    if (formId == null) {
      throw new ApiException(400, "Missing the required parameter 'formId' when calling updateLeadForm");
    }
    // verify the required parameter 'updateLeadFormRequest' is set
    if (updateLeadFormRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'updateLeadFormRequest' when calling updateLeadForm");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/ads/lead-forms/{formId}"
        .replace("{formId}", ApiClient.urlEncode(formId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(updateLeadFormRequest);
      localVarRequestBuilder.method("PATCH", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
