/*
 * Zernio API
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.zernio.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AdCreative
 */
class AdCreativeTest {
    private final AdCreative model = new AdCreative();

    /**
     * Model tests for AdCreative
     */
    @Test
    void testAdCreative() {
        // TODO: test AdCreative
    }

    /**
     * Test the property 'thumbnailUrl'
     */
    @Test
    void thumbnailUrlTest() {
        // TODO: test thumbnailUrl
    }

    /**
     * Test the property 'imageUrl'
     */
    @Test
    void imageUrlTest() {
        // TODO: test imageUrl
    }

    /**
     * Test the property 'mediaUrls'
     */
    @Test
    void mediaUrlsTest() {
        // TODO: test mediaUrls
    }

    /**
     * Test the property 'body'
     */
    @Test
    void bodyTest() {
        // TODO: test body
    }

    /**
     * Test the property 'googleHeadline'
     */
    @Test
    void googleHeadlineTest() {
        // TODO: test googleHeadline
    }

    /**
     * Test the property 'googleDescription'
     */
    @Test
    void googleDescriptionTest() {
        // TODO: test googleDescription
    }

    /**
     * Test the property 'linkUrl'
     */
    @Test
    void linkUrlTest() {
        // TODO: test linkUrl
    }

    /**
     * Test the property 'pinterestImageUrl'
     */
    @Test
    void pinterestImageUrlTest() {
        // TODO: test pinterestImageUrl
    }

    /**
     * Test the property 'pinterestTitle'
     */
    @Test
    void pinterestTitleTest() {
        // TODO: test pinterestTitle
    }

    /**
     * Test the property 'pinterestDescription'
     */
    @Test
    void pinterestDescriptionTest() {
        // TODO: test pinterestDescription
    }

}
