/*
 * Zernio API
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.zernio.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AddBroadcastRecipients200Response
 */
class AddBroadcastRecipients200ResponseTest {
    private final AddBroadcastRecipients200Response model = new AddBroadcastRecipients200Response();

    /**
     * Model tests for AddBroadcastRecipients200Response
     */
    @Test
    void testAddBroadcastRecipients200Response() {
        // TODO: test AddBroadcastRecipients200Response
    }

    /**
     * Test the property 'success'
     */
    @Test
    void successTest() {
        // TODO: test success
    }

    /**
     * Test the property 'added'
     */
    @Test
    void addedTest() {
        // TODO: test added
    }

    /**
     * Test the property 'skipped'
     */
    @Test
    void skippedTest() {
        // TODO: test skipped
    }

}
