/*
 * Zernio API
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.zernio.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.zernio.model.ConversionEventItemsInner;
import dev.zernio.model.ConversionEventUser;
import java.math.BigDecimal;
import java.net.URI;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ConversionEvent
 */
class ConversionEventTest {
    private final ConversionEvent model = new ConversionEvent();

    /**
     * Model tests for ConversionEvent
     */
    @Test
    void testConversionEvent() {
        // TODO: test ConversionEvent
    }

    /**
     * Test the property 'eventName'
     */
    @Test
    void eventNameTest() {
        // TODO: test eventName
    }

    /**
     * Test the property 'eventTime'
     */
    @Test
    void eventTimeTest() {
        // TODO: test eventTime
    }

    /**
     * Test the property 'eventId'
     */
    @Test
    void eventIdTest() {
        // TODO: test eventId
    }

    /**
     * Test the property 'value'
     */
    @Test
    void valueTest() {
        // TODO: test value
    }

    /**
     * Test the property 'currency'
     */
    @Test
    void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'user'
     */
    @Test
    void userTest() {
        // TODO: test user
    }

    /**
     * Test the property 'items'
     */
    @Test
    void itemsTest() {
        // TODO: test items
    }

    /**
     * Test the property 'sourceUrl'
     */
    @Test
    void sourceUrlTest() {
        // TODO: test sourceUrl
    }

    /**
     * Test the property 'actionSource'
     */
    @Test
    void actionSourceTest() {
        // TODO: test actionSource
    }

    /**
     * Test the property 'platformData'
     */
    @Test
    void platformDataTest() {
        // TODO: test platformData
    }

}
