/*
 * Zernio API
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.zernio.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.zernio.model.CreateCtwaAdRequestInterestsInner;
import dev.zernio.model.CreateCtwaAdRequestVideo;
import java.math.BigDecimal;
import java.net.URI;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateCtwaAdRequest
 */
class CreateCtwaAdRequestTest {
    private final CreateCtwaAdRequest model = new CreateCtwaAdRequest();

    /**
     * Model tests for CreateCtwaAdRequest
     */
    @Test
    void testCreateCtwaAdRequest() {
        // TODO: test CreateCtwaAdRequest
    }

    /**
     * Test the property 'accountId'
     */
    @Test
    void accountIdTest() {
        // TODO: test accountId
    }

    /**
     * Test the property 'adAccountId'
     */
    @Test
    void adAccountIdTest() {
        // TODO: test adAccountId
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'headline'
     */
    @Test
    void headlineTest() {
        // TODO: test headline
    }

    /**
     * Test the property 'body'
     */
    @Test
    void bodyTest() {
        // TODO: test body
    }

    /**
     * Test the property 'imageUrl'
     */
    @Test
    void imageUrlTest() {
        // TODO: test imageUrl
    }

    /**
     * Test the property 'video'
     */
    @Test
    void videoTest() {
        // TODO: test video
    }

    /**
     * Test the property 'budgetAmount'
     */
    @Test
    void budgetAmountTest() {
        // TODO: test budgetAmount
    }

    /**
     * Test the property 'budgetType'
     */
    @Test
    void budgetTypeTest() {
        // TODO: test budgetType
    }

    /**
     * Test the property 'currency'
     */
    @Test
    void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'endDate'
     */
    @Test
    void endDateTest() {
        // TODO: test endDate
    }

    /**
     * Test the property 'countries'
     */
    @Test
    void countriesTest() {
        // TODO: test countries
    }

    /**
     * Test the property 'ageMin'
     */
    @Test
    void ageMinTest() {
        // TODO: test ageMin
    }

    /**
     * Test the property 'ageMax'
     */
    @Test
    void ageMaxTest() {
        // TODO: test ageMax
    }

    /**
     * Test the property 'interests'
     */
    @Test
    void interestsTest() {
        // TODO: test interests
    }

    /**
     * Test the property 'audienceId'
     */
    @Test
    void audienceIdTest() {
        // TODO: test audienceId
    }

    /**
     * Test the property 'advantageAudience'
     */
    @Test
    void advantageAudienceTest() {
        // TODO: test advantageAudience
    }

    /**
     * Test the property 'objective'
     */
    @Test
    void objectiveTest() {
        // TODO: test objective
    }

}
