/*
 * Zernio API
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.zernio.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.zernio.model.CreateSequenceRequestStepsInnerTemplateVariableMappingValue;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateSequenceRequestStepsInnerTemplate
 */
class CreateSequenceRequestStepsInnerTemplateTest {
    private final CreateSequenceRequestStepsInnerTemplate model = new CreateSequenceRequestStepsInnerTemplate();

    /**
     * Model tests for CreateSequenceRequestStepsInnerTemplate
     */
    @Test
    void testCreateSequenceRequestStepsInnerTemplate() {
        // TODO: test CreateSequenceRequestStepsInnerTemplate
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'language'
     */
    @Test
    void languageTest() {
        // TODO: test language
    }

    /**
     * Test the property 'variableMapping'
     */
    @Test
    void variableMappingTest() {
        // TODO: test variableMapping
    }

}
