/*
 * Zernio API
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.zernio.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.zernio.model.CreateSequenceRequestStepsInnerMessage;
import dev.zernio.model.GetWhatsAppBroadcasts200ResponseBroadcastsInnerTemplate;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateSequenceRequestStepsInner
 */
class CreateSequenceRequestStepsInnerTest {
    private final CreateSequenceRequestStepsInner model = new CreateSequenceRequestStepsInner();

    /**
     * Model tests for CreateSequenceRequestStepsInner
     */
    @Test
    void testCreateSequenceRequestStepsInner() {
        // TODO: test CreateSequenceRequestStepsInner
    }

    /**
     * Test the property 'order'
     */
    @Test
    void orderTest() {
        // TODO: test order
    }

    /**
     * Test the property 'delayMinutes'
     */
    @Test
    void delayMinutesTest() {
        // TODO: test delayMinutes
    }

    /**
     * Test the property 'message'
     */
    @Test
    void messageTest() {
        // TODO: test message
    }

    /**
     * Test the property 'template'
     */
    @Test
    void templateTest() {
        // TODO: test template
    }

}
