/*
 * Zernio API
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.zernio.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.net.URI;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateStandaloneAdRequestCreativesInner
 */
class CreateStandaloneAdRequestCreativesInnerTest {
    private final CreateStandaloneAdRequestCreativesInner model = new CreateStandaloneAdRequestCreativesInner();

    /**
     * Model tests for CreateStandaloneAdRequestCreativesInner
     */
    @Test
    void testCreateStandaloneAdRequestCreativesInner() {
        // TODO: test CreateStandaloneAdRequestCreativesInner
    }

    /**
     * Test the property 'headline'
     */
    @Test
    void headlineTest() {
        // TODO: test headline
    }

    /**
     * Test the property 'body'
     */
    @Test
    void bodyTest() {
        // TODO: test body
    }

    /**
     * Test the property 'imageUrl'
     */
    @Test
    void imageUrlTest() {
        // TODO: test imageUrl
    }

    /**
     * Test the property 'linkUrl'
     */
    @Test
    void linkUrlTest() {
        // TODO: test linkUrl
    }

    /**
     * Test the property 'callToAction'
     */
    @Test
    void callToActionTest() {
        // TODO: test callToAction
    }

}
