/*
 * Zernio API
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.zernio.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.zernio.model.GetBroadcast200ResponseBroadcastMessage;
import dev.zernio.model.GetSequence200ResponseSequenceStepsInnerTemplate;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetSequence200ResponseSequenceStepsInner
 */
class GetSequence200ResponseSequenceStepsInnerTest {
    private final GetSequence200ResponseSequenceStepsInner model = new GetSequence200ResponseSequenceStepsInner();

    /**
     * Model tests for GetSequence200ResponseSequenceStepsInner
     */
    @Test
    void testGetSequence200ResponseSequenceStepsInner() {
        // TODO: test GetSequence200ResponseSequenceStepsInner
    }

    /**
     * Test the property 'order'
     */
    @Test
    void orderTest() {
        // TODO: test order
    }

    /**
     * Test the property 'delayMinutes'
     */
    @Test
    void delayMinutesTest() {
        // TODO: test delayMinutes
    }

    /**
     * Test the property 'message'
     */
    @Test
    void messageTest() {
        // TODO: test message
    }

    /**
     * Test the property 'template'
     */
    @Test
    void templateTest() {
        // TODO: test template
    }

}
