/*
 * Zernio API
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.zernio.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.zernio.model.GetWhatsAppFlow200ResponseFlowPreview;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetWhatsAppFlow200ResponseFlow
 */
class GetWhatsAppFlow200ResponseFlowTest {
    private final GetWhatsAppFlow200ResponseFlow model = new GetWhatsAppFlow200ResponseFlow();

    /**
     * Model tests for GetWhatsAppFlow200ResponseFlow
     */
    @Test
    void testGetWhatsAppFlow200ResponseFlow() {
        // TODO: test GetWhatsAppFlow200ResponseFlow
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'status'
     */
    @Test
    void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'categories'
     */
    @Test
    void categoriesTest() {
        // TODO: test categories
    }

    /**
     * Test the property 'validationErrors'
     */
    @Test
    void validationErrorsTest() {
        // TODO: test validationErrors
    }

    /**
     * Test the property 'jsonVersion'
     */
    @Test
    void jsonVersionTest() {
        // TODO: test jsonVersion
    }

    /**
     * Test the property 'preview'
     */
    @Test
    void previewTest() {
        // TODO: test preview
    }

}
