/*
 * Zernio API
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.zernio.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.zernio.model.GetWhatsAppGroupChat200ResponseGroup;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetWhatsAppGroupChat200Response
 */
class GetWhatsAppGroupChat200ResponseTest {
    private final GetWhatsAppGroupChat200Response model = new GetWhatsAppGroupChat200Response();

    /**
     * Model tests for GetWhatsAppGroupChat200Response
     */
    @Test
    void testGetWhatsAppGroupChat200Response() {
        // TODO: test GetWhatsAppGroupChat200Response
    }

    /**
     * Test the property 'success'
     */
    @Test
    void successTest() {
        // TODO: test success
    }

    /**
     * Test the property 'group'
     */
    @Test
    void groupTest() {
        // TODO: test group
    }

}
