/*
 * Zernio API
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.zernio.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.net.URI;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GoogleBusinessPlatformDataOffer
 */
class GoogleBusinessPlatformDataOfferTest {
    private final GoogleBusinessPlatformDataOffer model = new GoogleBusinessPlatformDataOffer();

    /**
     * Model tests for GoogleBusinessPlatformDataOffer
     */
    @Test
    void testGoogleBusinessPlatformDataOffer() {
        // TODO: test GoogleBusinessPlatformDataOffer
    }

    /**
     * Test the property 'offerType'
     */
    @Test
    void offerTypeTest() {
        // TODO: test offerType
    }

    /**
     * Test the property 'redeemOnlineUrl'
     */
    @Test
    void redeemOnlineUrlTest() {
        // TODO: test redeemOnlineUrl
    }

    /**
     * Test the property 'termsConditions'
     */
    @Test
    void termsConditionsTest() {
        // TODO: test termsConditions
    }

    /**
     * Test the property 'couponCode'
     */
    @Test
    void couponCodeTest() {
        // TODO: test couponCode
    }

}
