/*
 * Zernio API
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.zernio.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.zernio.model.GoogleBusinessPlatformDataEventScheduleEndDate;
import dev.zernio.model.GoogleBusinessPlatformDataEventScheduleEndTime;
import dev.zernio.model.GoogleBusinessPlatformDataEventScheduleStartDate;
import dev.zernio.model.GoogleBusinessPlatformDataEventScheduleStartTime;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GoogleBusinessPlatformDataEventSchedule
 */
class GoogleBusinessPlatformDataEventScheduleTest {
    private final GoogleBusinessPlatformDataEventSchedule model = new GoogleBusinessPlatformDataEventSchedule();

    /**
     * Model tests for GoogleBusinessPlatformDataEventSchedule
     */
    @Test
    void testGoogleBusinessPlatformDataEventSchedule() {
        // TODO: test GoogleBusinessPlatformDataEventSchedule
    }

    /**
     * Test the property 'startDate'
     */
    @Test
    void startDateTest() {
        // TODO: test startDate
    }

    /**
     * Test the property 'startTime'
     */
    @Test
    void startTimeTest() {
        // TODO: test startTime
    }

    /**
     * Test the property 'endDate'
     */
    @Test
    void endDateTest() {
        // TODO: test endDate
    }

    /**
     * Test the property 'endTime'
     */
    @Test
    void endTimeTest() {
        // TODO: test endTime
    }

}
