/*
 * Zernio API
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.zernio.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.zernio.model.LeadGenFormQuestion;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for LeadGenForm
 */
class LeadGenFormTest {
    private final LeadGenForm model = new LeadGenForm();

    /**
     * Model tests for LeadGenForm
     */
    @Test
    void testLeadGenForm() {
        // TODO: test LeadGenForm
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'status'
     */
    @Test
    void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'locale'
     */
    @Test
    void localeTest() {
        // TODO: test locale
    }

    /**
     * Test the property 'createdTime'
     */
    @Test
    void createdTimeTest() {
        // TODO: test createdTime
    }

    /**
     * Test the property 'leadsCount'
     */
    @Test
    void leadsCountTest() {
        // TODO: test leadsCount
    }

    /**
     * Test the property 'organicLeadsCount'
     */
    @Test
    void organicLeadsCountTest() {
        // TODO: test organicLeadsCount
    }

    /**
     * Test the property 'expiredLeadsCount'
     */
    @Test
    void expiredLeadsCountTest() {
        // TODO: test expiredLeadsCount
    }

    /**
     * Test the property 'questions'
     */
    @Test
    void questionsTest() {
        // TODO: test questions
    }

    /**
     * Test the property 'privacyPolicyUrl'
     */
    @Test
    void privacyPolicyUrlTest() {
        // TODO: test privacyPolicyUrl
    }

    /**
     * Test the property 'followUpActionUrl'
     */
    @Test
    void followUpActionUrlTest() {
        // TODO: test followUpActionUrl
    }

    /**
     * Test the property 'thankYouPage'
     */
    @Test
    void thankYouPageTest() {
        // TODO: test thankYouPage
    }

    /**
     * Test the property 'contextCard'
     */
    @Test
    void contextCardTest() {
        // TODO: test contextCard
    }

    /**
     * Test the property 'questionPageCustomHeadline'
     */
    @Test
    void questionPageCustomHeadlineTest() {
        // TODO: test questionPageCustomHeadline
    }

    /**
     * Test the property 'isOptimizedForQuality'
     */
    @Test
    void isOptimizedForQualityTest() {
        // TODO: test isOptimizedForQuality
    }

    /**
     * Test the property 'pageId'
     */
    @Test
    void pageIdTest() {
        // TODO: test pageId
    }

}
