/*
 * Zernio API
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.zernio.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for LeadFormResponseMeta
 */
class LeadFormResponseMetaTest {
    private final LeadFormResponseMeta model = new LeadFormResponseMeta();

    /**
     * Model tests for LeadFormResponseMeta
     */
    @Test
    void testLeadFormResponseMeta() {
        // TODO: test LeadFormResponseMeta
    }

    /**
     * Test the property 'platform'
     */
    @Test
    void platformTest() {
        // TODO: test platform
    }

    /**
     * Test the property 'accountId'
     */
    @Test
    void accountIdTest() {
        // TODO: test accountId
    }

    /**
     * Test the property 'formId'
     */
    @Test
    void formIdTest() {
        // TODO: test formId
    }

    /**
     * Test the property 'leadId'
     */
    @Test
    void leadIdTest() {
        // TODO: test leadId
    }

    /**
     * Test the property 'pageId'
     */
    @Test
    void pageIdTest() {
        // TODO: test pageId
    }

    /**
     * Test the property 'lastUpdated'
     */
    @Test
    void lastUpdatedTest() {
        // TODO: test lastUpdated
    }

}
