/*
 * Zernio API
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.zernio.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ListSequenceEnrollments200ResponseEnrollmentsInner
 */
class ListSequenceEnrollments200ResponseEnrollmentsInnerTest {
    private final ListSequenceEnrollments200ResponseEnrollmentsInner model = new ListSequenceEnrollments200ResponseEnrollmentsInner();

    /**
     * Model tests for ListSequenceEnrollments200ResponseEnrollmentsInner
     */
    @Test
    void testListSequenceEnrollments200ResponseEnrollmentsInner() {
        // TODO: test ListSequenceEnrollments200ResponseEnrollmentsInner
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'contactId'
     */
    @Test
    void contactIdTest() {
        // TODO: test contactId
    }

    /**
     * Test the property 'channelId'
     */
    @Test
    void channelIdTest() {
        // TODO: test channelId
    }

    /**
     * Test the property 'platformIdentifier'
     */
    @Test
    void platformIdentifierTest() {
        // TODO: test platformIdentifier
    }

    /**
     * Test the property 'contactName'
     */
    @Test
    void contactNameTest() {
        // TODO: test contactName
    }

    /**
     * Test the property 'currentStepIndex'
     */
    @Test
    void currentStepIndexTest() {
        // TODO: test currentStepIndex
    }

    /**
     * Test the property 'status'
     */
    @Test
    void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'exitReason'
     */
    @Test
    void exitReasonTest() {
        // TODO: test exitReason
    }

    /**
     * Test the property 'nextStepAt'
     */
    @Test
    void nextStepAtTest() {
        // TODO: test nextStepAt
    }

    /**
     * Test the property 'stepsSent'
     */
    @Test
    void stepsSentTest() {
        // TODO: test stepsSent
    }

    /**
     * Test the property 'lastStepSentAt'
     */
    @Test
    void lastStepSentAtTest() {
        // TODO: test lastStepSentAt
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    void createdAtTest() {
        // TODO: test createdAt
    }

}
