/*
 * Zernio API
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.zernio.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.zernio.model.ListWhatsAppPhoneNumbers200ResponsePhoneNumbersInner;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ListWhatsAppPhoneNumbers200Response
 */
class ListWhatsAppPhoneNumbers200ResponseTest {
    private final ListWhatsAppPhoneNumbers200Response model = new ListWhatsAppPhoneNumbers200Response();

    /**
     * Model tests for ListWhatsAppPhoneNumbers200Response
     */
    @Test
    void testListWhatsAppPhoneNumbers200Response() {
        // TODO: test ListWhatsAppPhoneNumbers200Response
    }

    /**
     * Test the property 'phoneNumbers'
     */
    @Test
    void phoneNumbersTest() {
        // TODO: test phoneNumbers
    }

}
