/*
 * Zernio API
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.zernio.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.zernio.model.ListWhatsAppGroupChats200ResponseGroupsInner;
import dev.zernio.model.ListWhatsAppGroupChats200ResponsePaging;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ListWhatsAppGroupChats200Response
 */
class ListWhatsAppGroupChats200ResponseTest {
    private final ListWhatsAppGroupChats200Response model = new ListWhatsAppGroupChats200Response();

    /**
     * Model tests for ListWhatsAppGroupChats200Response
     */
    @Test
    void testListWhatsAppGroupChats200Response() {
        // TODO: test ListWhatsAppGroupChats200Response
    }

    /**
     * Test the property 'groups'
     */
    @Test
    void groupsTest() {
        // TODO: test groups
    }

    /**
     * Test the property 'paging'
     */
    @Test
    void pagingTest() {
        // TODO: test paging
    }

}
