/*
 * Zernio API
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.zernio.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SendWhatsAppConversionRequest
 */
class SendWhatsAppConversionRequestTest {
    private final SendWhatsAppConversionRequest model = new SendWhatsAppConversionRequest();

    /**
     * Model tests for SendWhatsAppConversionRequest
     */
    @Test
    void testSendWhatsAppConversionRequest() {
        // TODO: test SendWhatsAppConversionRequest
    }

    /**
     * Test the property 'accountId'
     */
    @Test
    void accountIdTest() {
        // TODO: test accountId
    }

    /**
     * Test the property 'eventName'
     */
    @Test
    void eventNameTest() {
        // TODO: test eventName
    }

    /**
     * Test the property 'eventTime'
     */
    @Test
    void eventTimeTest() {
        // TODO: test eventTime
    }

    /**
     * Test the property 'eventId'
     */
    @Test
    void eventIdTest() {
        // TODO: test eventId
    }

    /**
     * Test the property 'conversationId'
     */
    @Test
    void conversationIdTest() {
        // TODO: test conversationId
    }

    /**
     * Test the property 'phoneE164'
     */
    @Test
    void phoneE164Test() {
        // TODO: test phoneE164
    }

    /**
     * Test the property 'value'
     */
    @Test
    void valueTest() {
        // TODO: test value
    }

    /**
     * Test the property 'currency'
     */
    @Test
    void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'contentIds'
     */
    @Test
    void contentIdsTest() {
        // TODO: test contentIds
    }

    /**
     * Test the property 'email'
     */
    @Test
    void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'externalId'
     */
    @Test
    void externalIdTest() {
        // TODO: test externalId
    }

    /**
     * Test the property 'testCode'
     */
    @Test
    void testCodeTest() {
        // TODO: test testCode
    }

}
