/*
 * Zernio API
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.zernio.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.zernio.model.SendConversions200ResponseFailuresInner;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SendWhatsAppConversion200Response
 */
class SendWhatsAppConversion200ResponseTest {
    private final SendWhatsAppConversion200Response model = new SendWhatsAppConversion200Response();

    /**
     * Model tests for SendWhatsAppConversion200Response
     */
    @Test
    void testSendWhatsAppConversion200Response() {
        // TODO: test SendWhatsAppConversion200Response
    }

    /**
     * Test the property 'platform'
     */
    @Test
    void platformTest() {
        // TODO: test platform
    }

    /**
     * Test the property 'eventsReceived'
     */
    @Test
    void eventsReceivedTest() {
        // TODO: test eventsReceived
    }

    /**
     * Test the property 'eventsFailed'
     */
    @Test
    void eventsFailedTest() {
        // TODO: test eventsFailed
    }

    /**
     * Test the property 'failures'
     */
    @Test
    void failuresTest() {
        // TODO: test failures
    }

    /**
     * Test the property 'traceId'
     */
    @Test
    void traceIdTest() {
        // TODO: test traceId
    }

}
