/*
 * Zernio API
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.zernio.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.zernio.model.SendInboxMessageRequestInteractiveActionOneOfSectionsInner;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SendInboxMessageRequestInteractiveActionOneOf
 */
class SendInboxMessageRequestInteractiveActionOneOfTest {
    private final SendInboxMessageRequestInteractiveActionOneOf model = new SendInboxMessageRequestInteractiveActionOneOf();

    /**
     * Model tests for SendInboxMessageRequestInteractiveActionOneOf
     */
    @Test
    void testSendInboxMessageRequestInteractiveActionOneOf() {
        // TODO: test SendInboxMessageRequestInteractiveActionOneOf
    }

    /**
     * Test the property 'button'
     */
    @Test
    void buttonTest() {
        // TODO: test button
    }

    /**
     * Test the property 'sections'
     */
    @Test
    void sectionsTest() {
        // TODO: test sections
    }

}
