/*
 * Zernio API
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.zernio.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.zernio.model.SendWhatsAppFlowMessageRequestFlowActionPayload;
import dev.zernio.model.SendWhatsAppFlowMessageRequestHeader;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SendWhatsAppFlowMessageRequest
 */
class SendWhatsAppFlowMessageRequestTest {
    private final SendWhatsAppFlowMessageRequest model = new SendWhatsAppFlowMessageRequest();

    /**
     * Model tests for SendWhatsAppFlowMessageRequest
     */
    @Test
    void testSendWhatsAppFlowMessageRequest() {
        // TODO: test SendWhatsAppFlowMessageRequest
    }

    /**
     * Test the property 'accountId'
     */
    @Test
    void accountIdTest() {
        // TODO: test accountId
    }

    /**
     * Test the property 'to'
     */
    @Test
    void toTest() {
        // TODO: test to
    }

    /**
     * Test the property 'flowId'
     */
    @Test
    void flowIdTest() {
        // TODO: test flowId
    }

    /**
     * Test the property 'flowCta'
     */
    @Test
    void flowCtaTest() {
        // TODO: test flowCta
    }

    /**
     * Test the property 'flowAction'
     */
    @Test
    void flowActionTest() {
        // TODO: test flowAction
    }

    /**
     * Test the property 'flowToken'
     */
    @Test
    void flowTokenTest() {
        // TODO: test flowToken
    }

    /**
     * Test the property 'flowActionPayload'
     */
    @Test
    void flowActionPayloadTest() {
        // TODO: test flowActionPayload
    }

    /**
     * Test the property 'body'
     */
    @Test
    void bodyTest() {
        // TODO: test body
    }

    /**
     * Test the property 'header'
     */
    @Test
    void headerTest() {
        // TODO: test header
    }

    /**
     * Test the property 'footer'
     */
    @Test
    void footerTest() {
        // TODO: test footer
    }

    /**
     * Test the property 'draft'
     */
    @Test
    void draftTest() {
        // TODO: test draft
    }

}
