/*
 * Zernio API
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.zernio.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SendInboxMessageRequestInteractiveActionOneOf2ParametersFlowActionPayload
 */
class SendInboxMessageRequestInteractiveActionOneOf2ParametersFlowActionPayloadTest {
    private final SendInboxMessageRequestInteractiveActionOneOf2ParametersFlowActionPayload model = new SendInboxMessageRequestInteractiveActionOneOf2ParametersFlowActionPayload();

    /**
     * Model tests for SendInboxMessageRequestInteractiveActionOneOf2ParametersFlowActionPayload
     */
    @Test
    void testSendInboxMessageRequestInteractiveActionOneOf2ParametersFlowActionPayload() {
        // TODO: test SendInboxMessageRequestInteractiveActionOneOf2ParametersFlowActionPayload
    }

    /**
     * Test the property 'screen'
     */
    @Test
    void screenTest() {
        // TODO: test screen
    }

    /**
     * Test the property 'data'
     */
    @Test
    void dataTest() {
        // TODO: test data
    }

}
