/*
 * Zernio API
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.zernio.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.zernio.model.SendInboxMessageRequestInteractiveAction;
import dev.zernio.model.SendInboxMessageRequestInteractiveBody;
import dev.zernio.model.SendInboxMessageRequestInteractiveFooter;
import dev.zernio.model.SendInboxMessageRequestInteractiveHeader;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SendInboxMessageRequestInteractive
 */
class SendInboxMessageRequestInteractiveTest {
    private final SendInboxMessageRequestInteractive model = new SendInboxMessageRequestInteractive();

    /**
     * Model tests for SendInboxMessageRequestInteractive
     */
    @Test
    void testSendInboxMessageRequestInteractive() {
        // TODO: test SendInboxMessageRequestInteractive
    }

    /**
     * Test the property 'type'
     */
    @Test
    void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'header'
     */
    @Test
    void headerTest() {
        // TODO: test header
    }

    /**
     * Test the property 'body'
     */
    @Test
    void bodyTest() {
        // TODO: test body
    }

    /**
     * Test the property 'footer'
     */
    @Test
    void footerTest() {
        // TODO: test footer
    }

    /**
     * Test the property 'action'
     */
    @Test
    void actionTest() {
        // TODO: test action
    }

}
