/*
 * Zernio API
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.zernio.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for UpdateSequence200ResponseSequence
 */
class UpdateSequence200ResponseSequenceTest {
    private final UpdateSequence200ResponseSequence model = new UpdateSequence200ResponseSequence();

    /**
     * Model tests for UpdateSequence200ResponseSequence
     */
    @Test
    void testUpdateSequence200ResponseSequence() {
        // TODO: test UpdateSequence200ResponseSequence
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'description'
     */
    @Test
    void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'status'
     */
    @Test
    void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'steps'
     */
    @Test
    void stepsTest() {
        // TODO: test steps
    }

    /**
     * Test the property 'exitOnReply'
     */
    @Test
    void exitOnReplyTest() {
        // TODO: test exitOnReply
    }

    /**
     * Test the property 'exitOnUnsubscribe'
     */
    @Test
    void exitOnUnsubscribeTest() {
        // TODO: test exitOnUnsubscribe
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    void updatedAtTest() {
        // TODO: test updatedAt
    }

}
