/*
 * Zernio API
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.zernio.model;

import com.fasterxml.jackson.annotation.JsonTypeName;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for UploadWhatsAppFlowJsonRequestFlowJson
 */
class UploadWhatsAppFlowJsonRequestFlowJsonTest {
    private final UploadWhatsAppFlowJsonRequestFlowJson model = new UploadWhatsAppFlowJsonRequestFlowJson();

    /**
     * Model tests for UploadWhatsAppFlowJsonRequestFlowJson
     */
    @Test
    void testUploadWhatsAppFlowJsonRequestFlowJson() {
        // TODO: test UploadWhatsAppFlowJsonRequestFlowJson
    }

}
