/*
 * Zernio API
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.zernio.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.zernio.model.GetInboxConversationMessages200ResponseMessagesInnerEditHistoryInnerAttachmentsInner;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for WebhookPayloadMessageEditedEditHistoryInner
 */
class WebhookPayloadMessageEditedEditHistoryInnerTest {
    private final WebhookPayloadMessageEditedEditHistoryInner model = new WebhookPayloadMessageEditedEditHistoryInner();

    /**
     * Model tests for WebhookPayloadMessageEditedEditHistoryInner
     */
    @Test
    void testWebhookPayloadMessageEditedEditHistoryInner() {
        // TODO: test WebhookPayloadMessageEditedEditHistoryInner
    }

    /**
     * Test the property 'text'
     */
    @Test
    void textTest() {
        // TODO: test text
    }

    /**
     * Test the property 'attachments'
     */
    @Test
    void attachmentsTest() {
        // TODO: test attachments
    }

    /**
     * Test the property 'editedAt'
     */
    @Test
    void editedAtTest() {
        // TODO: test editedAt
    }

}
