/*
 * Zernio API
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.zernio.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.zernio.model.WebhookPayloadMessageAccount;
import dev.zernio.model.WebhookPayloadMessageConversation;
import dev.zernio.model.WebhookPayloadMessageMessage;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for WebhookPayloadMessageDeleted
 */
class WebhookPayloadMessageDeletedTest {
    private final WebhookPayloadMessageDeleted model = new WebhookPayloadMessageDeleted();

    /**
     * Model tests for WebhookPayloadMessageDeleted
     */
    @Test
    void testWebhookPayloadMessageDeleted() {
        // TODO: test WebhookPayloadMessageDeleted
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'event'
     */
    @Test
    void eventTest() {
        // TODO: test event
    }

    /**
     * Test the property 'message'
     */
    @Test
    void messageTest() {
        // TODO: test message
    }

    /**
     * Test the property 'deletedAt'
     */
    @Test
    void deletedAtTest() {
        // TODO: test deletedAt
    }

    /**
     * Test the property 'conversation'
     */
    @Test
    void conversationTest() {
        // TODO: test conversation
    }

    /**
     * Test the property 'account'
     */
    @Test
    void accountTest() {
        // TODO: test account
    }

    /**
     * Test the property 'timestamp'
     */
    @Test
    void timestampTest() {
        // TODO: test timestamp
    }

}
