/*
 * Zernio API
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.zernio.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for WebhookPayloadMessageMetadataReferral
 */
class WebhookPayloadMessageMetadataReferralTest {
    private final WebhookPayloadMessageMetadataReferral model = new WebhookPayloadMessageMetadataReferral();

    /**
     * Model tests for WebhookPayloadMessageMetadataReferral
     */
    @Test
    void testWebhookPayloadMessageMetadataReferral() {
        // TODO: test WebhookPayloadMessageMetadataReferral
    }

    /**
     * Test the property 'ctwaClid'
     */
    @Test
    void ctwaClidTest() {
        // TODO: test ctwaClid
    }

    /**
     * Test the property 'sourceId'
     */
    @Test
    void sourceIdTest() {
        // TODO: test sourceId
    }

    /**
     * Test the property 'sourceType'
     */
    @Test
    void sourceTypeTest() {
        // TODO: test sourceType
    }

    /**
     * Test the property 'sourceUrl'
     */
    @Test
    void sourceUrlTest() {
        // TODO: test sourceUrl
    }

    /**
     * Test the property 'headline'
     */
    @Test
    void headlineTest() {
        // TODO: test headline
    }

    /**
     * Test the property 'body'
     */
    @Test
    void bodyTest() {
        // TODO: test body
    }

    /**
     * Test the property 'mediaType'
     */
    @Test
    void mediaTypeTest() {
        // TODO: test mediaType
    }

    /**
     * Test the property 'imageUrl'
     */
    @Test
    void imageUrlTest() {
        // TODO: test imageUrl
    }

    /**
     * Test the property 'videoUrl'
     */
    @Test
    void videoUrlTest() {
        // TODO: test videoUrl
    }

    /**
     * Test the property 'thumbnailUrl'
     */
    @Test
    void thumbnailUrlTest() {
        // TODO: test thumbnailUrl
    }

}
