/*
 * Late API
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.getlate.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.getlate.model.CreatePostRequestMediaItemsInner;
import dev.getlate.model.CreatePostRequestPlatformsInnerPlatformSpecificData;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreatePostRequestPlatformsInner
 */
class CreatePostRequestPlatformsInnerTest {
    private final CreatePostRequestPlatformsInner model = new CreatePostRequestPlatformsInner();

    /**
     * Model tests for CreatePostRequestPlatformsInner
     */
    @Test
    void testCreatePostRequestPlatformsInner() {
        // TODO: test CreatePostRequestPlatformsInner
    }

    /**
     * Test the property 'platform'
     */
    @Test
    void platformTest() {
        // TODO: test platform
    }

    /**
     * Test the property 'accountId'
     */
    @Test
    void accountIdTest() {
        // TODO: test accountId
    }

    /**
     * Test the property 'customContent'
     */
    @Test
    void customContentTest() {
        // TODO: test customContent
    }

    /**
     * Test the property 'customMedia'
     */
    @Test
    void customMediaTest() {
        // TODO: test customMedia
    }

    /**
     * Test the property 'scheduledFor'
     */
    @Test
    void scheduledForTest() {
        // TODO: test scheduledFor
    }

    /**
     * Test the property 'platformSpecificData'
     */
    @Test
    void platformSpecificDataTest() {
        // TODO: test platformSpecificData
    }

}
