/*
 * Late API
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.getlate.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.getlate.model.FacebookPlatformData;
import dev.getlate.model.InstagramPlatformData;
import dev.getlate.model.InstagramPlatformDataTrialParams;
import dev.getlate.model.InstagramPlatformDataUserTagsInner;
import dev.getlate.model.LinkedInPlatformData;
import dev.getlate.model.PinterestPlatformData;
import dev.getlate.model.SnapchatPlatformData;
import dev.getlate.model.TelegramPlatformData;
import dev.getlate.model.ThreadsPlatformData;
import dev.getlate.model.TikTokPlatformData;
import dev.getlate.model.TwitterPlatformData;
import dev.getlate.model.TwitterPlatformDataThreadItemsInner;
import dev.getlate.model.YouTubePlatformData;
import java.net.URI;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreatePostRequestPlatformsInnerPlatformSpecificData
 */
class CreatePostRequestPlatformsInnerPlatformSpecificDataTest {
    private final CreatePostRequestPlatformsInnerPlatformSpecificData model = new CreatePostRequestPlatformsInnerPlatformSpecificData();

    /**
     * Model tests for CreatePostRequestPlatformsInnerPlatformSpecificData
     */
    @Test
    void testCreatePostRequestPlatformsInnerPlatformSpecificData() {
        // TODO: test CreatePostRequestPlatformsInnerPlatformSpecificData
    }

    /**
     * Test the property 'threadItems'
     */
    @Test
    void threadItemsTest() {
        // TODO: test threadItems
    }

    /**
     * Test the property 'contentType'
     */
    @Test
    void contentTypeTest() {
        // TODO: test contentType
    }

    /**
     * Test the property 'firstComment'
     */
    @Test
    void firstCommentTest() {
        // TODO: test firstComment
    }

    /**
     * Test the property 'pageId'
     */
    @Test
    void pageIdTest() {
        // TODO: test pageId
    }

    /**
     * Test the property 'shareToFeed'
     */
    @Test
    void shareToFeedTest() {
        // TODO: test shareToFeed
    }

    /**
     * Test the property 'collaborators'
     */
    @Test
    void collaboratorsTest() {
        // TODO: test collaborators
    }

    /**
     * Test the property 'trialParams'
     */
    @Test
    void trialParamsTest() {
        // TODO: test trialParams
    }

    /**
     * Test the property 'userTags'
     */
    @Test
    void userTagsTest() {
        // TODO: test userTags
    }

    /**
     * Test the property 'audioName'
     */
    @Test
    void audioNameTest() {
        // TODO: test audioName
    }

    /**
     * Test the property 'thumbOffset'
     */
    @Test
    void thumbOffsetTest() {
        // TODO: test thumbOffset
    }

    /**
     * Test the property 'organizationUrn'
     */
    @Test
    void organizationUrnTest() {
        // TODO: test organizationUrn
    }

    /**
     * Test the property 'disableLinkPreview'
     */
    @Test
    void disableLinkPreviewTest() {
        // TODO: test disableLinkPreview
    }

    /**
     * Test the property 'title'
     */
    @Test
    void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'boardId'
     */
    @Test
    void boardIdTest() {
        // TODO: test boardId
    }

    /**
     * Test the property 'link'
     */
    @Test
    void linkTest() {
        // TODO: test link
    }

    /**
     * Test the property 'coverImageUrl'
     */
    @Test
    void coverImageUrlTest() {
        // TODO: test coverImageUrl
    }

    /**
     * Test the property 'coverImageKeyFrameTime'
     */
    @Test
    void coverImageKeyFrameTimeTest() {
        // TODO: test coverImageKeyFrameTime
    }

    /**
     * Test the property 'visibility'
     */
    @Test
    void visibilityTest() {
        // TODO: test visibility
    }

    /**
     * Test the property 'madeForKids'
     */
    @Test
    void madeForKidsTest() {
        // TODO: test madeForKids
    }

    /**
     * Test the property 'containsSyntheticMedia'
     */
    @Test
    void containsSyntheticMediaTest() {
        // TODO: test containsSyntheticMedia
    }

    /**
     * Test the property 'categoryId'
     */
    @Test
    void categoryIdTest() {
        // TODO: test categoryId
    }

    /**
     * Test the property 'draft'
     */
    @Test
    void draftTest() {
        // TODO: test draft
    }

    /**
     * Test the property 'privacyLevel'
     */
    @Test
    void privacyLevelTest() {
        // TODO: test privacyLevel
    }

    /**
     * Test the property 'allowComment'
     */
    @Test
    void allowCommentTest() {
        // TODO: test allowComment
    }

    /**
     * Test the property 'allowDuet'
     */
    @Test
    void allowDuetTest() {
        // TODO: test allowDuet
    }

    /**
     * Test the property 'allowStitch'
     */
    @Test
    void allowStitchTest() {
        // TODO: test allowStitch
    }

    /**
     * Test the property 'commercialContentType'
     */
    @Test
    void commercialContentTypeTest() {
        // TODO: test commercialContentType
    }

    /**
     * Test the property 'brandPartnerPromote'
     */
    @Test
    void brandPartnerPromoteTest() {
        // TODO: test brandPartnerPromote
    }

    /**
     * Test the property 'isBrandOrganicPost'
     */
    @Test
    void isBrandOrganicPostTest() {
        // TODO: test isBrandOrganicPost
    }

    /**
     * Test the property 'contentPreviewConfirmed'
     */
    @Test
    void contentPreviewConfirmedTest() {
        // TODO: test contentPreviewConfirmed
    }

    /**
     * Test the property 'expressConsentGiven'
     */
    @Test
    void expressConsentGivenTest() {
        // TODO: test expressConsentGiven
    }

    /**
     * Test the property 'mediaType'
     */
    @Test
    void mediaTypeTest() {
        // TODO: test mediaType
    }

    /**
     * Test the property 'videoCoverTimestampMs'
     */
    @Test
    void videoCoverTimestampMsTest() {
        // TODO: test videoCoverTimestampMs
    }

    /**
     * Test the property 'photoCoverIndex'
     */
    @Test
    void photoCoverIndexTest() {
        // TODO: test photoCoverIndex
    }

    /**
     * Test the property 'autoAddMusic'
     */
    @Test
    void autoAddMusicTest() {
        // TODO: test autoAddMusic
    }

    /**
     * Test the property 'videoMadeWithAi'
     */
    @Test
    void videoMadeWithAiTest() {
        // TODO: test videoMadeWithAi
    }

    /**
     * Test the property 'description'
     */
    @Test
    void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'parseMode'
     */
    @Test
    void parseModeTest() {
        // TODO: test parseMode
    }

    /**
     * Test the property 'disableWebPagePreview'
     */
    @Test
    void disableWebPagePreviewTest() {
        // TODO: test disableWebPagePreview
    }

    /**
     * Test the property 'disableNotification'
     */
    @Test
    void disableNotificationTest() {
        // TODO: test disableNotification
    }

    /**
     * Test the property 'protectContent'
     */
    @Test
    void protectContentTest() {
        // TODO: test protectContent
    }

}
