/*
 * Late API
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.getlate.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.getlate.model.DeleteAccountGroup200Response;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for DeleteInboxComment200Response
 */
class DeleteInboxComment200ResponseTest {
    private final DeleteInboxComment200Response model = new DeleteInboxComment200Response();

    /**
     * Model tests for DeleteInboxComment200Response
     */
    @Test
    void testDeleteInboxComment200Response() {
        // TODO: test DeleteInboxComment200Response
    }

    /**
     * Test the property 'success'
     */
    @Test
    void successTest() {
        // TODO: test success
    }

    /**
     * Test the property 'data'
     */
    @Test
    void dataTest() {
        // TODO: test data
    }

}
