/*
 * Late API
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.getlate.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.getlate.model.FoodMenuItemAttributes;
import dev.getlate.model.FoodMenuLabel;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for FoodMenuItemOptionsInner
 */
class FoodMenuItemOptionsInnerTest {
    private final FoodMenuItemOptionsInner model = new FoodMenuItemOptionsInner();

    /**
     * Model tests for FoodMenuItemOptionsInner
     */
    @Test
    void testFoodMenuItemOptionsInner() {
        // TODO: test FoodMenuItemOptionsInner
    }

    /**
     * Test the property 'labels'
     */
    @Test
    void labelsTest() {
        // TODO: test labels
    }

    /**
     * Test the property 'attributes'
     */
    @Test
    void attributesTest() {
        // TODO: test attributes
    }

}
