/*
 * Late API
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.getlate.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.getlate.model.AnalyticsListResponse;
import dev.getlate.model.AnalyticsListResponsePostsInner;
import dev.getlate.model.AnalyticsOverview;
import dev.getlate.model.AnalyticsSinglePostResponse;
import dev.getlate.model.Pagination;
import dev.getlate.model.PlatformAnalytics;
import dev.getlate.model.PostAnalytics;
import dev.getlate.model.SocialAccount;
import java.net.URI;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetAnalytics200Response
 */
class GetAnalytics200ResponseTest {
    private final GetAnalytics200Response model = new GetAnalytics200Response();

    /**
     * Model tests for GetAnalytics200Response
     */
    @Test
    void testGetAnalytics200Response() {
        // TODO: test GetAnalytics200Response
    }

    /**
     * Test the property 'postId'
     */
    @Test
    void postIdTest() {
        // TODO: test postId
    }

    /**
     * Test the property 'status'
     */
    @Test
    void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'content'
     */
    @Test
    void contentTest() {
        // TODO: test content
    }

    /**
     * Test the property 'scheduledFor'
     */
    @Test
    void scheduledForTest() {
        // TODO: test scheduledFor
    }

    /**
     * Test the property 'publishedAt'
     */
    @Test
    void publishedAtTest() {
        // TODO: test publishedAt
    }

    /**
     * Test the property 'analytics'
     */
    @Test
    void analyticsTest() {
        // TODO: test analytics
    }

    /**
     * Test the property 'platformAnalytics'
     */
    @Test
    void platformAnalyticsTest() {
        // TODO: test platformAnalytics
    }

    /**
     * Test the property 'platform'
     */
    @Test
    void platformTest() {
        // TODO: test platform
    }

    /**
     * Test the property 'platformPostUrl'
     */
    @Test
    void platformPostUrlTest() {
        // TODO: test platformPostUrl
    }

    /**
     * Test the property 'isExternal'
     */
    @Test
    void isExternalTest() {
        // TODO: test isExternal
    }

    /**
     * Test the property 'overview'
     */
    @Test
    void overviewTest() {
        // TODO: test overview
    }

    /**
     * Test the property 'posts'
     */
    @Test
    void postsTest() {
        // TODO: test posts
    }

    /**
     * Test the property 'pagination'
     */
    @Test
    void paginationTest() {
        // TODO: test pagination
    }

    /**
     * Test the property 'accounts'
     */
    @Test
    void accountsTest() {
        // TODO: test accounts
    }

    /**
     * Test the property 'hasAnalyticsAccess'
     */
    @Test
    void hasAnalyticsAccessTest() {
        // TODO: test hasAnalyticsAccess
    }

}
