/*
 * Late API
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.getlate.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetNextQueueSlot200Response
 */
class GetNextQueueSlot200ResponseTest {
    private final GetNextQueueSlot200Response model = new GetNextQueueSlot200Response();

    /**
     * Model tests for GetNextQueueSlot200Response
     */
    @Test
    void testGetNextQueueSlot200Response() {
        // TODO: test GetNextQueueSlot200Response
    }

    /**
     * Test the property 'profileId'
     */
    @Test
    void profileIdTest() {
        // TODO: test profileId
    }

    /**
     * Test the property 'nextSlot'
     */
    @Test
    void nextSlotTest() {
        // TODO: test nextSlot
    }

    /**
     * Test the property 'timezone'
     */
    @Test
    void timezoneTest() {
        // TODO: test timezone
    }

    /**
     * Test the property 'queueId'
     */
    @Test
    void queueIdTest() {
        // TODO: test queueId
    }

    /**
     * Test the property 'queueName'
     */
    @Test
    void queueNameTest() {
        // TODO: test queueName
    }

}
