/*
 * Late API
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@getlate.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.getlate.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetPreverifiedWhatsAppNumbers200ResponseNumbersInner
 */
class GetPreverifiedWhatsAppNumbers200ResponseNumbersInnerTest {
    private final GetPreverifiedWhatsAppNumbers200ResponseNumbersInner model = new GetPreverifiedWhatsAppNumbers200ResponseNumbersInner();

    /**
     * Model tests for GetPreverifiedWhatsAppNumbers200ResponseNumbersInner
     */
    @Test
    void testGetPreverifiedWhatsAppNumbers200ResponseNumbersInner() {
        // TODO: test GetPreverifiedWhatsAppNumbers200ResponseNumbersInner
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'phoneNumber'
     */
    @Test
    void phoneNumberTest() {
        // TODO: test phoneNumber
    }

    /**
     * Test the property 'metaPreverifiedId'
     */
    @Test
    void metaPreverifiedIdTest() {
        // TODO: test metaPreverifiedId
    }

    /**
     * Test the property 'metaVerifiedAt'
     */
    @Test
    void metaVerifiedAtTest() {
        // TODO: test metaVerifiedAt
    }

    /**
     * Test the property 'metaVerificationExpiresAt'
     */
    @Test
    void metaVerificationExpiresAtTest() {
        // TODO: test metaVerificationExpiresAt
    }

}
