/*
 * Late API
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@getlate.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.getlate.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.getlate.model.GetPreverifiedWhatsAppNumbers200ResponseNumbersInner;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetPreverifiedWhatsAppNumbers200Response
 */
class GetPreverifiedWhatsAppNumbers200ResponseTest {
    private final GetPreverifiedWhatsAppNumbers200Response model = new GetPreverifiedWhatsAppNumbers200Response();

    /**
     * Model tests for GetPreverifiedWhatsAppNumbers200Response
     */
    @Test
    void testGetPreverifiedWhatsAppNumbers200Response() {
        // TODO: test GetPreverifiedWhatsAppNumbers200Response
    }

    /**
     * Test the property 'preVerifiedIds'
     */
    @Test
    void preVerifiedIdsTest() {
        // TODO: test preVerifiedIds
    }

    /**
     * Test the property 'numbers'
     */
    @Test
    void numbersTest() {
        // TODO: test numbers
    }

}
