/*
 * Late API
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.getlate.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.getlate.model.ListGoogleBusinessLocations200ResponseLocationsInner;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ListGoogleBusinessLocations200Response
 */
class ListGoogleBusinessLocations200ResponseTest {
    private final ListGoogleBusinessLocations200Response model = new ListGoogleBusinessLocations200Response();

    /**
     * Model tests for ListGoogleBusinessLocations200Response
     */
    @Test
    void testListGoogleBusinessLocations200Response() {
        // TODO: test ListGoogleBusinessLocations200Response
    }

    /**
     * Test the property 'locations'
     */
    @Test
    void locationsTest() {
        // TODO: test locations
    }

}
