/*
 * Late API
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.getlate.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ListInboxReviews200ResponseSummary
 */
class ListInboxReviews200ResponseSummaryTest {
    private final ListInboxReviews200ResponseSummary model = new ListInboxReviews200ResponseSummary();

    /**
     * Model tests for ListInboxReviews200ResponseSummary
     */
    @Test
    void testListInboxReviews200ResponseSummary() {
        // TODO: test ListInboxReviews200ResponseSummary
    }

    /**
     * Test the property 'totalReviews'
     */
    @Test
    void totalReviewsTest() {
        // TODO: test totalReviews
    }

    /**
     * Test the property 'averageRating'
     */
    @Test
    void averageRatingTest() {
        // TODO: test averageRating
    }

}
