/*
 * Late API
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.getlate.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.getlate.model.PlatformAnalyticsAccountMetrics;
import dev.getlate.model.PostAnalytics;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PlatformAnalytics
 */
class PlatformAnalyticsTest {
    private final PlatformAnalytics model = new PlatformAnalytics();

    /**
     * Model tests for PlatformAnalytics
     */
    @Test
    void testPlatformAnalytics() {
        // TODO: test PlatformAnalytics
    }

    /**
     * Test the property 'platform'
     */
    @Test
    void platformTest() {
        // TODO: test platform
    }

    /**
     * Test the property 'status'
     */
    @Test
    void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'accountId'
     */
    @Test
    void accountIdTest() {
        // TODO: test accountId
    }

    /**
     * Test the property 'accountUsername'
     */
    @Test
    void accountUsernameTest() {
        // TODO: test accountUsername
    }

    /**
     * Test the property 'analytics'
     */
    @Test
    void analyticsTest() {
        // TODO: test analytics
    }

    /**
     * Test the property 'accountMetrics'
     */
    @Test
    void accountMetricsTest() {
        // TODO: test accountMetrics
    }

}
