/*
 * Late API
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.getlate.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.getlate.model.PostLogDetailAllOfAccountId;
import dev.getlate.model.PostLogDetailAllOfPostId;
import dev.getlate.model.PostLogRequest;
import dev.getlate.model.PostLogResponse;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PostLogDetail
 */
class PostLogDetailTest {
    private final PostLogDetail model = new PostLogDetail();

    /**
     * Model tests for PostLogDetail
     */
    @Test
    void testPostLogDetail() {
        // TODO: test PostLogDetail
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'postId'
     */
    @Test
    void postIdTest() {
        // TODO: test postId
    }

    /**
     * Test the property 'userId'
     */
    @Test
    void userIdTest() {
        // TODO: test userId
    }

    /**
     * Test the property 'profileId'
     */
    @Test
    void profileIdTest() {
        // TODO: test profileId
    }

    /**
     * Test the property 'platform'
     */
    @Test
    void platformTest() {
        // TODO: test platform
    }

    /**
     * Test the property 'accountId'
     */
    @Test
    void accountIdTest() {
        // TODO: test accountId
    }

    /**
     * Test the property 'accountUsername'
     */
    @Test
    void accountUsernameTest() {
        // TODO: test accountUsername
    }

    /**
     * Test the property 'action'
     */
    @Test
    void actionTest() {
        // TODO: test action
    }

    /**
     * Test the property 'status'
     */
    @Test
    void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'statusCode'
     */
    @Test
    void statusCodeTest() {
        // TODO: test statusCode
    }

    /**
     * Test the property 'endpoint'
     */
    @Test
    void endpointTest() {
        // TODO: test endpoint
    }

    /**
     * Test the property 'request'
     */
    @Test
    void requestTest() {
        // TODO: test request
    }

    /**
     * Test the property 'response'
     */
    @Test
    void responseTest() {
        // TODO: test response
    }

    /**
     * Test the property 'durationMs'
     */
    @Test
    void durationMsTest() {
        // TODO: test durationMs
    }

    /**
     * Test the property 'attemptNumber'
     */
    @Test
    void attemptNumberTest() {
        // TODO: test attemptNumber
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    void metadataTest() {
        // TODO: test metadata
    }

}
