/*
 * Late API
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.getlate.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.getlate.model.QueueSchedule;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for QueueSlotsResponse
 */
class QueueSlotsResponseTest {
    private final QueueSlotsResponse model = new QueueSlotsResponse();

    /**
     * Model tests for QueueSlotsResponse
     */
    @Test
    void testQueueSlotsResponse() {
        // TODO: test QueueSlotsResponse
    }

    /**
     * Test the property 'exists'
     */
    @Test
    void existsTest() {
        // TODO: test exists
    }

    /**
     * Test the property 'schedule'
     */
    @Test
    void scheduleTest() {
        // TODO: test schedule
    }

    /**
     * Test the property 'nextSlots'
     */
    @Test
    void nextSlotsTest() {
        // TODO: test nextSlots
    }

}
