/*
 * Late API
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.getlate.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for UnlikeInboxComment200Response
 */
class UnlikeInboxComment200ResponseTest {
    private final UnlikeInboxComment200Response model = new UnlikeInboxComment200Response();

    /**
     * Model tests for UnlikeInboxComment200Response
     */
    @Test
    void testUnlikeInboxComment200Response() {
        // TODO: test UnlikeInboxComment200Response
    }

    /**
     * Test the property 'status'
     */
    @Test
    void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'commentId'
     */
    @Test
    void commentIdTest() {
        // TODO: test commentId
    }

    /**
     * Test the property 'liked'
     */
    @Test
    void likedTest() {
        // TODO: test liked
    }

    /**
     * Test the property 'platform'
     */
    @Test
    void platformTest() {
        // TODO: test platform
    }

}
