/*
 * Late API
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.getlate.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.getlate.model.GetGoogleBusinessLocationDetails200ResponsePhoneNumbers;
import dev.getlate.model.GetGoogleBusinessLocationDetails200ResponseSpecialHours;
import dev.getlate.model.UpdateGoogleBusinessLocationDetailsRequestProfile;
import dev.getlate.model.UpdateGoogleBusinessLocationDetailsRequestRegularHours;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for UpdateGoogleBusinessLocationDetailsRequest
 */
class UpdateGoogleBusinessLocationDetailsRequestTest {
    private final UpdateGoogleBusinessLocationDetailsRequest model = new UpdateGoogleBusinessLocationDetailsRequest();

    /**
     * Model tests for UpdateGoogleBusinessLocationDetailsRequest
     */
    @Test
    void testUpdateGoogleBusinessLocationDetailsRequest() {
        // TODO: test UpdateGoogleBusinessLocationDetailsRequest
    }

    /**
     * Test the property 'updateMask'
     */
    @Test
    void updateMaskTest() {
        // TODO: test updateMask
    }

    /**
     * Test the property 'regularHours'
     */
    @Test
    void regularHoursTest() {
        // TODO: test regularHours
    }

    /**
     * Test the property 'specialHours'
     */
    @Test
    void specialHoursTest() {
        // TODO: test specialHours
    }

    /**
     * Test the property 'profile'
     */
    @Test
    void profileTest() {
        // TODO: test profile
    }

    /**
     * Test the property 'websiteUri'
     */
    @Test
    void websiteUriTest() {
        // TODO: test websiteUri
    }

    /**
     * Test the property 'phoneNumbers'
     */
    @Test
    void phoneNumbersTest() {
        // TODO: test phoneNumbers
    }

}
