/*
 * Late API
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.getlate.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for UpdateRedditSubredditsRequest
 */
class UpdateRedditSubredditsRequestTest {
    private final UpdateRedditSubredditsRequest model = new UpdateRedditSubredditsRequest();

    /**
     * Model tests for UpdateRedditSubredditsRequest
     */
    @Test
    void testUpdateRedditSubredditsRequest() {
        // TODO: test UpdateRedditSubredditsRequest
    }

    /**
     * Test the property 'defaultSubreddit'
     */
    @Test
    void defaultSubredditTest() {
        // TODO: test defaultSubreddit
    }

}
