/*
 * Late API
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.getlate.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.getlate.model.UpdateGoogleBusinessAttributesRequestAttributesInner;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for UpdateGoogleBusinessAttributesRequest
 */
class UpdateGoogleBusinessAttributesRequestTest {
    private final UpdateGoogleBusinessAttributesRequest model = new UpdateGoogleBusinessAttributesRequest();

    /**
     * Model tests for UpdateGoogleBusinessAttributesRequest
     */
    @Test
    void testUpdateGoogleBusinessAttributesRequest() {
        // TODO: test UpdateGoogleBusinessAttributesRequest
    }

    /**
     * Test the property 'attributes'
     */
    @Test
    void attributesTest() {
        // TODO: test attributes
    }

    /**
     * Test the property 'attributeMask'
     */
    @Test
    void attributeMaskTest() {
        // TODO: test attributeMask
    }

}
