/*
 * Late API
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@getlate.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.getlate.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for VerifyWhatsAppPhoneNumber200Response
 */
class VerifyWhatsAppPhoneNumber200ResponseTest {
    private final VerifyWhatsAppPhoneNumber200Response model = new VerifyWhatsAppPhoneNumber200Response();

    /**
     * Model tests for VerifyWhatsAppPhoneNumber200Response
     */
    @Test
    void testVerifyWhatsAppPhoneNumber200Response() {
        // TODO: test VerifyWhatsAppPhoneNumber200Response
    }

    /**
     * Test the property 'message'
     */
    @Test
    void messageTest() {
        // TODO: test message
    }

    /**
     * Test the property 'metaVerifiedAt'
     */
    @Test
    void metaVerifiedAtTest() {
        // TODO: test metaVerifiedAt
    }

    /**
     * Test the property 'metaVerificationExpiresAt'
     */
    @Test
    void metaVerificationExpiresAtTest() {
        // TODO: test metaVerificationExpiresAt
    }

}
