/*
 * Late API
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@getlate.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.getlate.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.getlate.model.WebhookPayloadCommentAccount;
import dev.getlate.model.WebhookPayloadCommentComment;
import dev.getlate.model.WebhookPayloadCommentPost;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for WebhookPayloadComment
 */
class WebhookPayloadCommentTest {
    private final WebhookPayloadComment model = new WebhookPayloadComment();

    /**
     * Model tests for WebhookPayloadComment
     */
    @Test
    void testWebhookPayloadComment() {
        // TODO: test WebhookPayloadComment
    }

    /**
     * Test the property 'event'
     */
    @Test
    void eventTest() {
        // TODO: test event
    }

    /**
     * Test the property 'comment'
     */
    @Test
    void commentTest() {
        // TODO: test comment
    }

    /**
     * Test the property 'post'
     */
    @Test
    void postTest() {
        // TODO: test post
    }

    /**
     * Test the property 'account'
     */
    @Test
    void accountTest() {
        // TODO: test account
    }

    /**
     * Test the property 'timestamp'
     */
    @Test
    void timestampTest() {
        // TODO: test timestamp
    }

}
