/*
 * Late API
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.getlate.api;

import dev.getlate.ApiException;
import dev.getlate.model.DeleteAccountGroup200Response;
import dev.getlate.model.GetAccountHealth200Response;
import dev.getlate.model.GetAllAccountsHealth200Response;
import dev.getlate.model.GetFollowerStats200Response;
import dev.getlate.model.GetFollowerStats403Response;
import dev.getlate.model.InlineObject;
import dev.getlate.model.InlineObject1;
import dev.getlate.model.ListAccounts200Response;
import java.time.LocalDate;
import dev.getlate.model.UpdateAccount200Response;
import dev.getlate.model.UpdateAccountRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for AccountsApi
 */
@Disabled
public class AccountsApiTest {

    private final AccountsApi api = new AccountsApi();

    
    /**
     * Disconnect a social account
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteAccountTest() throws ApiException {
        String accountId = null;
        DeleteAccountGroup200Response response = 
        api.deleteAccount(accountId);
        
        // TODO: test validations
    }
    
    /**
     * Check health of a specific account
     *
     * Returns detailed health information for a specific social account, including token status, granted permissions, missing permissions, and actionable recommendations. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAccountHealthTest() throws ApiException {
        String accountId = null;
        GetAccountHealth200Response response = 
        api.getAccountHealth(accountId);
        
        // TODO: test validations
    }
    
    /**
     * Check health of all connected accounts
     *
     * Returns the health status of all connected social accounts, including token validity, permissions status, and any issues that need attention. Useful for monitoring account connections and identifying accounts that need reconnection. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllAccountsHealthTest() throws ApiException {
        String profileId = null;
        String platform = null;
        String status = null;
        GetAllAccountsHealth200Response response = 
        api.getAllAccountsHealth(profileId, platform, status);
        
        // TODO: test validations
    }
    
    /**
     * Get follower stats and growth metrics
     *
     * Returns follower count history and growth metrics for connected social accounts. **Requires analytics add-on subscription.**  **Data Freshness:** Follower counts are automatically refreshed once per day. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getFollowerStatsTest() throws ApiException {
        String accountIds = null;
        String profileId = null;
        LocalDate fromDate = null;
        LocalDate toDate = null;
        String granularity = null;
        GetFollowerStats200Response response = 
        api.getFollowerStats(accountIds, profileId, fromDate, toDate, granularity);
        
        // TODO: test validations
    }
    
    /**
     * List connected social accounts
     *
     * Returns list of connected social accounts. By default, only returns accounts from profiles within the user&#39;s plan limit. Follower count data (followersCount, followersLastUpdated) is only included if user has analytics add-on. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listAccountsTest() throws ApiException {
        String profileId = null;
        Boolean includeOverLimit = null;
        ListAccounts200Response response = 
        api.listAccounts(profileId, includeOverLimit);
        
        // TODO: test validations
    }
    
    /**
     * Update a social account
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateAccountTest() throws ApiException {
        String accountId = null;
        UpdateAccountRequest updateAccountRequest = null;
        UpdateAccount200Response response = 
        api.updateAccount(accountId, updateAccountRequest);
        
        // TODO: test validations
    }
    
}
