/*
 * Late API
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.getlate.api;

import dev.getlate.ApiException;
import dev.getlate.model.CreateApiKey201Response;
import dev.getlate.model.CreateApiKeyRequest;
import dev.getlate.model.DeleteAccountGroup200Response;
import dev.getlate.model.InlineObject;
import dev.getlate.model.InlineObject1;
import dev.getlate.model.ListApiKeys200Response;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for ApiKeysApi
 */
@Disabled
public class ApiKeysApiTest {

    private final ApiKeysApi api = new ApiKeysApi();

    
    /**
     * Create a new API key
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createApiKeyTest() throws ApiException {
        CreateApiKeyRequest createApiKeyRequest = null;
        CreateApiKey201Response response = 
        api.createApiKey(createApiKeyRequest);
        
        // TODO: test validations
    }
    
    /**
     * Delete an API key
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteApiKeyTest() throws ApiException {
        String keyId = null;
        DeleteAccountGroup200Response response = 
        api.deleteApiKey(keyId);
        
        // TODO: test validations
    }
    
    /**
     * List API keys for the current user
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listApiKeysTest() throws ApiException {
        ListApiKeys200Response response = 
        api.listApiKeys();
        
        // TODO: test validations
    }
    
}
