/*
 * Late API
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.getlate.api;

import dev.getlate.ApiException;
import dev.getlate.model.ErrorResponse;
import dev.getlate.model.GetGoogleBusinessAttributes200Response;
import dev.getlate.model.UpdateGoogleBusinessAttributes200Response;
import dev.getlate.model.UpdateGoogleBusinessAttributesRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for GmbAttributesApi
 */
@Disabled
public class GmbAttributesApiTest {

    private final GmbAttributesApi api = new GmbAttributesApi();

    
    /**
     * Get Google Business Profile location attributes
     *
     * Fetches location attributes such as amenities, services, and accessibility features.  Common attributes for restaurants include: - Dining options: has_dine_in, has_takeout, has_delivery - Amenities: has_outdoor_seating, has_wifi, has_parking - Accessibility: has_wheelchair_accessible_entrance - Payments: pay_credit_card_types_accepted  Available attributes vary by business category. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getGoogleBusinessAttributesTest() throws ApiException {
        String accountId = null;
        GetGoogleBusinessAttributes200Response response = 
        api.getGoogleBusinessAttributes(accountId);
        
        // TODO: test validations
    }
    
    /**
     * Update Google Business Profile location attributes
     *
     * Updates location attributes (amenities, services, etc.).  The &#x60;attributeMask&#x60; specifies which attributes to update (comma-separated). 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateGoogleBusinessAttributesTest() throws ApiException {
        String accountId = null;
        UpdateGoogleBusinessAttributesRequest updateGoogleBusinessAttributesRequest = null;
        UpdateGoogleBusinessAttributes200Response response = 
        api.updateGoogleBusinessAttributes(accountId, updateGoogleBusinessAttributesRequest);
        
        // TODO: test validations
    }
    
}
