/*
 * Late API
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.getlate.api;

import dev.getlate.ApiException;
import dev.getlate.model.ErrorResponse;
import dev.getlate.model.GetGoogleBusinessLocationDetails200Response;
import dev.getlate.model.InlineObject1;
import dev.getlate.model.UpdateGoogleBusinessLocationDetails200Response;
import dev.getlate.model.UpdateGoogleBusinessLocationDetailsRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for GmbLocationDetailsApi
 */
@Disabled
public class GmbLocationDetailsApiTest {

    private final GmbLocationDetailsApi api = new GmbLocationDetailsApi();

    
    /**
     * Get Google Business Profile location details
     *
     * Fetches detailed location information including opening hours, special hours, business description, phone numbers, website, categories, and more.  Use the &#x60;readMask&#x60; query parameter to request specific fields. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getGoogleBusinessLocationDetailsTest() throws ApiException {
        String accountId = null;
        String readMask = null;
        GetGoogleBusinessLocationDetails200Response response = 
        api.getGoogleBusinessLocationDetails(accountId, readMask);
        
        // TODO: test validations
    }
    
    /**
     * Update Google Business Profile location details
     *
     * Updates location details such as opening hours, special hours, business description, phone, and website.  The &#x60;updateMask&#x60; field is required and specifies which fields to update.  Common update masks: - &#x60;regularHours&#x60; - Update opening hours - &#x60;specialHours&#x60; - Update holiday/special hours - &#x60;profile.description&#x60; - Update business description - &#x60;websiteUri&#x60; - Update website URL - &#x60;phoneNumbers&#x60; - Update phone numbers - &#x60;regularHours,specialHours&#x60; - Update both at once 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateGoogleBusinessLocationDetailsTest() throws ApiException {
        String accountId = null;
        UpdateGoogleBusinessLocationDetailsRequest updateGoogleBusinessLocationDetailsRequest = null;
        UpdateGoogleBusinessLocationDetails200Response response = 
        api.updateGoogleBusinessLocationDetails(accountId, updateGoogleBusinessLocationDetailsRequest);
        
        // TODO: test validations
    }
    
}
