/*
 * Late API
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.getlate.api;

import dev.getlate.ApiException;
import dev.getlate.model.CreateGoogleBusinessMedia200Response;
import dev.getlate.model.CreateGoogleBusinessMediaRequest;
import dev.getlate.model.DeleteGoogleBusinessMedia200Response;
import dev.getlate.model.ErrorResponse;
import dev.getlate.model.ListGoogleBusinessMedia200Response;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for GmbMediaApi
 */
@Disabled
public class GmbMediaApiTest {

    private final GmbMediaApi api = new GmbMediaApi();

    
    /**
     * Upload a photo to Google Business Profile
     *
     * Creates a media item (photo) for a location from a publicly accessible URL.  Categories determine where the photo appears: - &#x60;COVER&#x60; - Cover photo - &#x60;PROFILE&#x60; - Profile photo - &#x60;LOGO&#x60; - Business logo - &#x60;EXTERIOR&#x60; - Exterior shots - &#x60;INTERIOR&#x60; - Interior shots - &#x60;FOOD_AND_DRINK&#x60; - Food and drink photos - &#x60;MENU&#x60; - Menu photos - &#x60;PRODUCT&#x60; - Product photos - &#x60;TEAMS&#x60; - Team/staff photos - &#x60;ADDITIONAL&#x60; - Other photos 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createGoogleBusinessMediaTest() throws ApiException {
        String accountId = null;
        CreateGoogleBusinessMediaRequest createGoogleBusinessMediaRequest = null;
        CreateGoogleBusinessMedia200Response response = 
        api.createGoogleBusinessMedia(accountId, createGoogleBusinessMediaRequest);
        
        // TODO: test validations
    }
    
    /**
     * Delete a photo from Google Business Profile
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteGoogleBusinessMediaTest() throws ApiException {
        String accountId = null;
        String mediaId = null;
        DeleteGoogleBusinessMedia200Response response = 
        api.deleteGoogleBusinessMedia(accountId, mediaId);
        
        // TODO: test validations
    }
    
    /**
     * List Google Business Profile media (photos)
     *
     * Lists media items (photos) for a Google Business Profile location. Returns photo URLs, descriptions, categories, and metadata. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listGoogleBusinessMediaTest() throws ApiException {
        String accountId = null;
        Integer pageSize = null;
        String pageToken = null;
        ListGoogleBusinessMedia200Response response = 
        api.listGoogleBusinessMedia(accountId, pageSize, pageToken);
        
        // TODO: test validations
    }
    
}
