/*
 * Late API
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.getlate.api;

import dev.getlate.ApiException;
import dev.getlate.model.CreateGoogleBusinessPlaceAction200Response;
import dev.getlate.model.CreateGoogleBusinessPlaceActionRequest;
import dev.getlate.model.DeleteGoogleBusinessPlaceAction200Response;
import dev.getlate.model.ErrorResponse;
import dev.getlate.model.ListGoogleBusinessPlaceActions200Response;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for GmbPlaceActionsApi
 */
@Disabled
public class GmbPlaceActionsApiTest {

    private final GmbPlaceActionsApi api = new GmbPlaceActionsApi();

    
    /**
     * Create a place action link (booking, ordering, reservation)
     *
     * Creates a place action link for a location.  Available action types: - &#x60;APPOINTMENT&#x60; - Booking an appointment - &#x60;ONLINE_APPOINTMENT&#x60; - Booking an online appointment - &#x60;DINING_RESERVATION&#x60; - Making a dining reservation (OpenTable, Resy, etc.) - &#x60;FOOD_ORDERING&#x60; - Ordering food for delivery and/or takeout (DoorDash, Uber Eats, etc.) - &#x60;FOOD_DELIVERY&#x60; - Ordering food for delivery only - &#x60;FOOD_TAKEOUT&#x60; - Ordering food for takeout only - &#x60;SHOP_ONLINE&#x60; - Shopping with delivery and/or pickup 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createGoogleBusinessPlaceActionTest() throws ApiException {
        String accountId = null;
        CreateGoogleBusinessPlaceActionRequest createGoogleBusinessPlaceActionRequest = null;
        CreateGoogleBusinessPlaceAction200Response response = 
        api.createGoogleBusinessPlaceAction(accountId, createGoogleBusinessPlaceActionRequest);
        
        // TODO: test validations
    }
    
    /**
     * Delete a place action link
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteGoogleBusinessPlaceActionTest() throws ApiException {
        String accountId = null;
        String name = null;
        DeleteGoogleBusinessPlaceAction200Response response = 
        api.deleteGoogleBusinessPlaceAction(accountId, name);
        
        // TODO: test validations
    }
    
    /**
     * List place action links (booking, ordering, reservations)
     *
     * Lists place action links for a Google Business Profile location.  Place actions are the booking, ordering, and reservation buttons that appear on your listing. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listGoogleBusinessPlaceActionsTest() throws ApiException {
        String accountId = null;
        Integer pageSize = null;
        String pageToken = null;
        ListGoogleBusinessPlaceActions200Response response = 
        api.listGoogleBusinessPlaceActions(accountId, pageSize, pageToken);
        
        // TODO: test validations
    }
    
}
