/*
 * Late API
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.getlate.api;

import dev.getlate.ApiException;
import dev.getlate.model.ErrorResponse;
import dev.getlate.model.GetGoogleBusinessReviews200Response;
import dev.getlate.model.InlineObject1;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for GmbReviewsApi
 */
@Disabled
public class GmbReviewsApiTest {

    private final GmbReviewsApi api = new GmbReviewsApi();

    
    /**
     * Get Google Business Profile reviews
     *
     * Fetches reviews for a connected Google Business Profile account.  Returns all reviews for the business location, including: - Reviewer information (name, profile photo) - Star rating (1-5) - Review comment/text - Business owner&#39;s reply (if any) - Review timestamps  Use pagination via &#x60;nextPageToken&#x60; to fetch all reviews for locations with many reviews. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getGoogleBusinessReviewsTest() throws ApiException {
        String accountId = null;
        Integer pageSize = null;
        String pageToken = null;
        GetGoogleBusinessReviews200Response response = 
        api.getGoogleBusinessReviews(accountId, pageSize, pageToken);
        
        // TODO: test validations
    }
    
}
