/*
 * Late API
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.getlate.api;

import dev.getlate.ApiException;
import dev.getlate.model.CreateInviteToken201Response;
import dev.getlate.model.CreateInviteTokenRequest;
import dev.getlate.model.InlineObject;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for InvitesApi
 */
@Disabled
public class InvitesApiTest {

    private final InvitesApi api = new InvitesApi();

    
    /**
     * Create a team member invite token
     *
     * Generate a secure invite link to grant team members access to your profiles. Invites expire after 7 days and are single-use. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createInviteTokenTest() throws ApiException {
        CreateInviteTokenRequest createInviteTokenRequest = null;
        CreateInviteToken201Response response = 
        api.createInviteToken(createInviteTokenRequest);
        
        // TODO: test validations
    }
    
}
