/*
 * Late API
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.getlate.api;

import dev.getlate.ApiException;
import dev.getlate.model.GetLinkedInMentions200Response;
import dev.getlate.model.GetYouTubeDailyViews400Response;
import dev.getlate.model.InlineObject;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for LinkedInMentionsApi
 */
@Disabled
public class LinkedInMentionsApiTest {

    private final LinkedInMentionsApi api = new LinkedInMentionsApi();

    
    /**
     * Resolve a LinkedIn profile or company URL to a URN for @mentions
     *
     * Converts a LinkedIn profile URL (person) or company page URL (organization) to a URN that can be used to @mention them in posts.  **Supports both:** - **Person mentions:** &#x60;linkedin.com/in/username&#x60; or just &#x60;username&#x60; - **Organization mentions:** &#x60;linkedin.com/company/company-name&#x60; or &#x60;company/company-name&#x60;  **⚠️ Organization Admin Required for Person Mentions Only:** Person mentions require the connected LinkedIn account to have admin access to at least one LinkedIn Organization (Company Page). Organization mentions do NOT have this requirement - any LinkedIn account can tag companies.  **IMPORTANT - Display Name Requirement:** For **person mentions** to be clickable, the display name must **exactly match** what appears on their LinkedIn profile. - Organization mentions automatically retrieve the company name from LinkedIn API - Person mentions require the exact name, so provide the &#x60;displayName&#x60; parameter  **Mention Format:** Use the returned &#x60;mentionFormat&#x60; value directly in your post content: &#x60;&#x60;&#x60; Great insights from @[Miquel Palet](urn:li:person:4qj5ox-agD) on this topic! Excited to partner with @[Microsoft](urn:li:organization:1035)! &#x60;&#x60;&#x60; 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getLinkedInMentionsTest() throws ApiException {
        String accountId = null;
        String url = null;
        String displayName = null;
        GetLinkedInMentions200Response response = 
        api.getLinkedInMentions(accountId, url, displayName);
        
        // TODO: test validations
    }
    
}
