/*
 * Late API
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@getlate.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.getlate.api;

import dev.getlate.ApiException;
import dev.getlate.model.AddWhatsAppBroadcastRecipients200Response;
import dev.getlate.model.AddWhatsAppBroadcastRecipientsRequest;
import dev.getlate.model.BulkDeleteWhatsAppContacts200Response;
import dev.getlate.model.BulkDeleteWhatsAppContactsRequest;
import dev.getlate.model.BulkUpdateWhatsAppContacts200Response;
import dev.getlate.model.BulkUpdateWhatsAppContactsRequest;
import dev.getlate.model.CancelWhatsAppBroadcastSchedule200Response;
import dev.getlate.model.CreateWhatsAppBroadcast200Response;
import dev.getlate.model.CreateWhatsAppBroadcastRequest;
import dev.getlate.model.CreateWhatsAppContact200Response;
import dev.getlate.model.CreateWhatsAppContactRequest;
import dev.getlate.model.CreateWhatsAppTemplate200Response;
import dev.getlate.model.CreateWhatsAppTemplateRequest;
import dev.getlate.model.DeleteWhatsAppGroupRequest;
import dev.getlate.model.GetWhatsAppBroadcast200Response;
import dev.getlate.model.GetWhatsAppBroadcastRecipients200Response;
import dev.getlate.model.GetWhatsAppBroadcasts200Response;
import dev.getlate.model.GetWhatsAppBusinessProfile200Response;
import dev.getlate.model.GetWhatsAppContact200Response;
import dev.getlate.model.GetWhatsAppContacts200Response;
import dev.getlate.model.GetWhatsAppGroups200Response;
import dev.getlate.model.GetWhatsAppTemplate200Response;
import dev.getlate.model.GetWhatsAppTemplates200Response;
import dev.getlate.model.ImportWhatsAppContacts200Response;
import dev.getlate.model.ImportWhatsAppContactsRequest;
import dev.getlate.model.InlineObject;
import dev.getlate.model.InlineObject1;
import dev.getlate.model.RemoveWhatsAppBroadcastRecipients200Response;
import dev.getlate.model.RemoveWhatsAppBroadcastRecipientsRequest;
import dev.getlate.model.RenameWhatsAppGroup200Response;
import dev.getlate.model.RenameWhatsAppGroupRequest;
import dev.getlate.model.ScheduleWhatsAppBroadcast200Response;
import dev.getlate.model.ScheduleWhatsAppBroadcastRequest;
import dev.getlate.model.SendWhatsAppBroadcast200Response;
import dev.getlate.model.SendWhatsAppBulk200Response;
import dev.getlate.model.SendWhatsAppBulkRequest;
import dev.getlate.model.UnpublishPost200Response;
import dev.getlate.model.UpdateWhatsAppBusinessProfileRequest;
import dev.getlate.model.UpdateWhatsAppContact200Response;
import dev.getlate.model.UpdateWhatsAppContactRequest;
import dev.getlate.model.UpdateWhatsAppTemplate200Response;
import dev.getlate.model.UpdateWhatsAppTemplateRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for WhatsAppApi
 */
@Disabled
public class WhatsAppApiTest {

    private final WhatsAppApi api = new WhatsAppApi();

    
    /**
     * Add recipients
     *
     * Add recipients to a draft broadcast. Maximum 1000 recipients per request. Duplicate phone numbers are automatically skipped. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addWhatsAppBroadcastRecipientsTest() throws ApiException {
        String broadcastId = null;
        AddWhatsAppBroadcastRecipientsRequest addWhatsAppBroadcastRecipientsRequest = null;
        AddWhatsAppBroadcastRecipients200Response response = 
        api.addWhatsAppBroadcastRecipients(broadcastId, addWhatsAppBroadcastRecipientsRequest);
        
        // TODO: test validations
    }
    
    /**
     * Bulk delete contacts
     *
     * Permanently delete multiple contacts at once (max 500 per request).
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void bulkDeleteWhatsAppContactsTest() throws ApiException {
        BulkDeleteWhatsAppContactsRequest bulkDeleteWhatsAppContactsRequest = null;
        BulkDeleteWhatsAppContacts200Response response = 
        api.bulkDeleteWhatsAppContacts(bulkDeleteWhatsAppContactsRequest);
        
        // TODO: test validations
    }
    
    /**
     * Bulk update contacts
     *
     * Perform bulk operations on multiple contacts (max 500 per request). Supported actions: addTags, removeTags, addGroups, removeGroups, optIn, optOut, block, unblock. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void bulkUpdateWhatsAppContactsTest() throws ApiException {
        BulkUpdateWhatsAppContactsRequest bulkUpdateWhatsAppContactsRequest = null;
        BulkUpdateWhatsAppContacts200Response response = 
        api.bulkUpdateWhatsAppContacts(bulkUpdateWhatsAppContactsRequest);
        
        // TODO: test validations
    }
    
    /**
     * Cancel scheduled broadcast
     *
     * Cancel a scheduled broadcast and return it to draft status. Only broadcasts in scheduled status can be cancelled. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void cancelWhatsAppBroadcastScheduleTest() throws ApiException {
        String broadcastId = null;
        CancelWhatsAppBroadcastSchedule200Response response = 
        api.cancelWhatsAppBroadcastSchedule(broadcastId);
        
        // TODO: test validations
    }
    
    /**
     * Create broadcast
     *
     * Create a new draft broadcast. Optionally include initial recipients. After creation, add recipients and then send or schedule the broadcast. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createWhatsAppBroadcastTest() throws ApiException {
        CreateWhatsAppBroadcastRequest createWhatsAppBroadcastRequest = null;
        CreateWhatsAppBroadcast200Response response = 
        api.createWhatsAppBroadcast(createWhatsAppBroadcastRequest);
        
        // TODO: test validations
    }
    
    /**
     * Create contact
     *
     * Create a new WhatsApp contact. Phone number must be unique per account and in E.164 format (e.g., +1234567890). 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createWhatsAppContactTest() throws ApiException {
        CreateWhatsAppContactRequest createWhatsAppContactRequest = null;
        CreateWhatsAppContact200Response response = 
        api.createWhatsAppContact(createWhatsAppContactRequest);
        
        // TODO: test validations
    }
    
    /**
     * Create template
     *
     * Create a new message template. Template names must be lowercase, start with a letter, and contain only letters, numbers, and underscores. Templates are submitted to Meta for review. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createWhatsAppTemplateTest() throws ApiException {
        CreateWhatsAppTemplateRequest createWhatsAppTemplateRequest = null;
        CreateWhatsAppTemplate200Response response = 
        api.createWhatsAppTemplate(createWhatsAppTemplateRequest);
        
        // TODO: test validations
    }
    
    /**
     * Delete broadcast
     *
     * Delete a broadcast. Only draft or cancelled broadcasts can be deleted.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteWhatsAppBroadcastTest() throws ApiException {
        String broadcastId = null;
        UnpublishPost200Response response = 
        api.deleteWhatsAppBroadcast(broadcastId);
        
        // TODO: test validations
    }
    
    /**
     * Delete contact
     *
     * Permanently delete a WhatsApp contact.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteWhatsAppContactTest() throws ApiException {
        String contactId = null;
        UnpublishPost200Response response = 
        api.deleteWhatsAppContact(contactId);
        
        // TODO: test validations
    }
    
    /**
     * Delete group
     *
     * Delete a contact group. This removes the group from all contacts but does not delete the contacts themselves.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteWhatsAppGroupTest() throws ApiException {
        DeleteWhatsAppGroupRequest deleteWhatsAppGroupRequest = null;
        RenameWhatsAppGroup200Response response = 
        api.deleteWhatsAppGroup(deleteWhatsAppGroupRequest);
        
        // TODO: test validations
    }
    
    /**
     * Delete template
     *
     * Permanently delete a message template by name.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteWhatsAppTemplateTest() throws ApiException {
        String templateName = null;
        String accountId = null;
        UnpublishPost200Response response = 
        api.deleteWhatsAppTemplate(templateName, accountId);
        
        // TODO: test validations
    }
    
    /**
     * Get broadcast
     *
     * Retrieve detailed information about a single broadcast including delivery statistics.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getWhatsAppBroadcastTest() throws ApiException {
        String broadcastId = null;
        GetWhatsAppBroadcast200Response response = 
        api.getWhatsAppBroadcast(broadcastId);
        
        // TODO: test validations
    }
    
    /**
     * List recipients
     *
     * List recipients of a broadcast with their delivery status. Supports filtering by delivery status and pagination. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getWhatsAppBroadcastRecipientsTest() throws ApiException {
        String broadcastId = null;
        String status = null;
        Integer limit = null;
        Integer skip = null;
        GetWhatsAppBroadcastRecipients200Response response = 
        api.getWhatsAppBroadcastRecipients(broadcastId, status, limit, skip);
        
        // TODO: test validations
    }
    
    /**
     * List broadcasts
     *
     * List all WhatsApp broadcasts for an account. Returns broadcasts sorted by creation date (newest first) without the full recipients list for performance. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getWhatsAppBroadcastsTest() throws ApiException {
        String accountId = null;
        String status = null;
        Integer limit = null;
        Integer skip = null;
        GetWhatsAppBroadcasts200Response response = 
        api.getWhatsAppBroadcasts(accountId, status, limit, skip);
        
        // TODO: test validations
    }
    
    /**
     * Get business profile
     *
     * Retrieve the WhatsApp Business profile for the account (about, address, description, email, websites, etc.).
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getWhatsAppBusinessProfileTest() throws ApiException {
        String accountId = null;
        GetWhatsAppBusinessProfile200Response response = 
        api.getWhatsAppBusinessProfile(accountId);
        
        // TODO: test validations
    }
    
    /**
     * Get contact
     *
     * Retrieve a single WhatsApp contact by ID with full details.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getWhatsAppContactTest() throws ApiException {
        String contactId = null;
        GetWhatsAppContact200Response response = 
        api.getWhatsAppContact(contactId);
        
        // TODO: test validations
    }
    
    /**
     * List contacts
     *
     * List WhatsApp contacts for an account. Supports filtering by tags, groups, opt-in status, and text search. Returns contacts sorted by name with available filter options. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getWhatsAppContactsTest() throws ApiException {
        String accountId = null;
        String search = null;
        String tag = null;
        String group = null;
        String optedIn = null;
        Integer limit = null;
        Integer skip = null;
        GetWhatsAppContacts200Response response = 
        api.getWhatsAppContacts(accountId, search, tag, group, optedIn, limit, skip);
        
        // TODO: test validations
    }
    
    /**
     * List contact groups
     *
     * List all contact groups for a WhatsApp account with contact counts. Groups are derived from the groups field on contacts, not stored as separate documents. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getWhatsAppGroupsTest() throws ApiException {
        String accountId = null;
        GetWhatsAppGroups200Response response = 
        api.getWhatsAppGroups(accountId);
        
        // TODO: test validations
    }
    
    /**
     * Get template
     *
     * Retrieve a single message template by name.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getWhatsAppTemplateTest() throws ApiException {
        String templateName = null;
        String accountId = null;
        GetWhatsAppTemplate200Response response = 
        api.getWhatsAppTemplate(templateName, accountId);
        
        // TODO: test validations
    }
    
    /**
     * List templates
     *
     * List all message templates for the WhatsApp Business Account (WABA) associated with the given account. Templates are fetched directly from the WhatsApp Cloud API. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getWhatsAppTemplatesTest() throws ApiException {
        String accountId = null;
        GetWhatsAppTemplates200Response response = 
        api.getWhatsAppTemplates(accountId);
        
        // TODO: test validations
    }
    
    /**
     * Bulk import contacts
     *
     * Import up to 1000 contacts at once. Each contact requires a phone number and name. Duplicates are skipped by default. Supports default tags and groups applied to all imported contacts. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void importWhatsAppContactsTest() throws ApiException {
        ImportWhatsAppContactsRequest importWhatsAppContactsRequest = null;
        ImportWhatsAppContacts200Response response = 
        api.importWhatsAppContacts(importWhatsAppContactsRequest);
        
        // TODO: test validations
    }
    
    /**
     * Remove recipients
     *
     * Remove recipients from a draft broadcast by phone number.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void removeWhatsAppBroadcastRecipientsTest() throws ApiException {
        String broadcastId = null;
        RemoveWhatsAppBroadcastRecipientsRequest removeWhatsAppBroadcastRecipientsRequest = null;
        RemoveWhatsAppBroadcastRecipients200Response response = 
        api.removeWhatsAppBroadcastRecipients(broadcastId, removeWhatsAppBroadcastRecipientsRequest);
        
        // TODO: test validations
    }
    
    /**
     * Rename group
     *
     * Rename a contact group. This updates the group name on all contacts that belong to the group.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void renameWhatsAppGroupTest() throws ApiException {
        RenameWhatsAppGroupRequest renameWhatsAppGroupRequest = null;
        RenameWhatsAppGroup200Response response = 
        api.renameWhatsAppGroup(renameWhatsAppGroupRequest);
        
        // TODO: test validations
    }
    
    /**
     * Schedule broadcast
     *
     * Schedule a draft broadcast for future sending. The scheduled time must be in the future and no more than 30 days in advance. The broadcast must be in draft status and have recipients. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void scheduleWhatsAppBroadcastTest() throws ApiException {
        String broadcastId = null;
        ScheduleWhatsAppBroadcastRequest scheduleWhatsAppBroadcastRequest = null;
        ScheduleWhatsAppBroadcast200Response response = 
        api.scheduleWhatsAppBroadcast(broadcastId, scheduleWhatsAppBroadcastRequest);
        
        // TODO: test validations
    }
    
    /**
     * Send broadcast
     *
     * Start sending a broadcast immediately. The broadcast must be in draft or scheduled status and have at least one recipient. Messages are sent sequentially with rate limiting. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void sendWhatsAppBroadcastTest() throws ApiException {
        String broadcastId = null;
        SendWhatsAppBroadcast200Response response = 
        api.sendWhatsAppBroadcast(broadcastId);
        
        // TODO: test validations
    }
    
    /**
     * Bulk send template messages
     *
     * Send a template message to multiple recipients in a single request. Maximum 100 recipients per request. Only template messages are supported for bulk sending (not free-form text).  Each recipient can have optional per-recipient template variables for personalization. Returns detailed results for each recipient. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void sendWhatsAppBulkTest() throws ApiException {
        SendWhatsAppBulkRequest sendWhatsAppBulkRequest = null;
        SendWhatsAppBulk200Response response = 
        api.sendWhatsAppBulk(sendWhatsAppBulkRequest);
        
        // TODO: test validations
    }
    
    /**
     * Update business profile
     *
     * Update the WhatsApp Business profile. All fields are optional; only provided fields will be updated. Constraints: about max 139 chars, description max 512 chars, max 2 websites. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateWhatsAppBusinessProfileTest() throws ApiException {
        UpdateWhatsAppBusinessProfileRequest updateWhatsAppBusinessProfileRequest = null;
        UnpublishPost200Response response = 
        api.updateWhatsAppBusinessProfile(updateWhatsAppBusinessProfileRequest);
        
        // TODO: test validations
    }
    
    /**
     * Update contact
     *
     * Update an existing WhatsApp contact. All fields are optional; only provided fields will be updated. Custom fields are merged with existing values. Set a custom field to null to remove it. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateWhatsAppContactTest() throws ApiException {
        String contactId = null;
        UpdateWhatsAppContactRequest updateWhatsAppContactRequest = null;
        UpdateWhatsAppContact200Response response = 
        api.updateWhatsAppContact(contactId, updateWhatsAppContactRequest);
        
        // TODO: test validations
    }
    
    /**
     * Update template
     *
     * Update a message template&#39;s components. Only certain fields can be updated depending on the template&#39;s current approval state. Approved templates can only have components updated. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateWhatsAppTemplateTest() throws ApiException {
        String templateName = null;
        UpdateWhatsAppTemplateRequest updateWhatsAppTemplateRequest = null;
        UpdateWhatsAppTemplate200Response response = 
        api.updateWhatsAppTemplate(templateName, updateWhatsAppTemplateRequest);
        
        // TODO: test validations
    }
    
}
