/*
 * Late API
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@getlate.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.getlate.api;

import dev.getlate.ApiException;
import dev.getlate.model.GetPreverifiedWhatsAppNumbers200Response;
import dev.getlate.model.GetWhatsAppPhoneNumber200Response;
import dev.getlate.model.GetWhatsAppPhoneNumbers200Response;
import dev.getlate.model.InlineObject;
import dev.getlate.model.InlineObject1;
import dev.getlate.model.PurchaseWhatsAppPhoneNumber200Response;
import dev.getlate.model.PurchaseWhatsAppPhoneNumberRequest;
import dev.getlate.model.ReleaseWhatsAppPhoneNumber200Response;
import dev.getlate.model.RequestWhatsAppVerificationCode200Response;
import dev.getlate.model.RequestWhatsAppVerificationCodeRequest;
import dev.getlate.model.SearchAvailableWhatsAppNumbers200Response;
import dev.getlate.model.VerifyWhatsAppPhoneNumber200Response;
import dev.getlate.model.VerifyWhatsAppPhoneNumberRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for WhatsAppPhoneNumbersApi
 */
@Disabled
public class WhatsAppPhoneNumbersApiTest {

    private final WhatsAppPhoneNumbersApi api = new WhatsAppPhoneNumbersApi();

    
    /**
     * Get pre-verified numbers
     *
     * Returns the user&#39;s pre-verified phone number IDs that are ready for OTP-free Embedded Signup. Only returns numbers with verified Meta status and non-expired verification. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getPreverifiedWhatsAppNumbersTest() throws ApiException {
        String profileId = null;
        GetPreverifiedWhatsAppNumbers200Response response = 
        api.getPreverifiedWhatsAppNumbers(profileId);
        
        // TODO: test validations
    }
    
    /**
     * Get phone number
     *
     * Retrieve the current status of a purchased phone number. Used to poll for Meta pre-verification completion after purchase. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getWhatsAppPhoneNumberTest() throws ApiException {
        String phoneNumberId = null;
        GetWhatsAppPhoneNumber200Response response = 
        api.getWhatsAppPhoneNumber(phoneNumberId);
        
        // TODO: test validations
    }
    
    /**
     * List phone numbers
     *
     * List all WhatsApp phone numbers purchased by the authenticated user. By default, released numbers are excluded. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getWhatsAppPhoneNumbersTest() throws ApiException {
        String status = null;
        String profileId = null;
        GetWhatsAppPhoneNumbers200Response response = 
        api.getWhatsAppPhoneNumbers(status, profileId);
        
        // TODO: test validations
    }
    
    /**
     * Purchase phone number
     *
     * Initiate purchasing a WhatsApp phone number. Payment-first flow: the user does not pick a specific number. The system either creates a Stripe Checkout Session (first number) or increments the existing subscription quantity and provisions inline (subsequent numbers).  Requires a paid plan. The maximum number of phone numbers is determined by the user&#39;s plan. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void purchaseWhatsAppPhoneNumberTest() throws ApiException {
        PurchaseWhatsAppPhoneNumberRequest purchaseWhatsAppPhoneNumberRequest = null;
        PurchaseWhatsAppPhoneNumber200Response response = 
        api.purchaseWhatsAppPhoneNumber(purchaseWhatsAppPhoneNumberRequest);
        
        // TODO: test validations
    }
    
    /**
     * Release phone number
     *
     * Release a purchased phone number. This will: 1. Disconnect any linked WhatsApp social account 2. Decrement the Stripe subscription quantity (or cancel if last number) 3. Release the number from Telnyx 4. Mark the number as released 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void releaseWhatsAppPhoneNumberTest() throws ApiException {
        String phoneNumberId = null;
        ReleaseWhatsAppPhoneNumber200Response response = 
        api.releaseWhatsAppPhoneNumber(phoneNumberId);
        
        // TODO: test validations
    }
    
    /**
     * Request OTP
     *
     * Request a new OTP verification code from Meta for a pre-verified phone number. Useful when the initial SMS did not arrive or when re-verifying before the 90-day expiry. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void requestWhatsAppVerificationCodeTest() throws ApiException {
        String phoneNumberId = null;
        RequestWhatsAppVerificationCodeRequest requestWhatsAppVerificationCodeRequest = null;
        RequestWhatsAppVerificationCode200Response response = 
        api.requestWhatsAppVerificationCode(phoneNumberId, requestWhatsAppVerificationCodeRequest);
        
        // TODO: test validations
    }
    
    /**
     * Search available numbers
     *
     * Search for available US phone numbers that can be purchased for WhatsApp Business. Requires a paid plan. Numbers are sourced from Telnyx. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void searchAvailableWhatsAppNumbersTest() throws ApiException {
        String prefix = null;
        String locality = null;
        String contains = null;
        Integer limit = null;
        SearchAvailableWhatsAppNumbers200Response response = 
        api.searchAvailableWhatsAppNumbers(prefix, locality, contains, limit);
        
        // TODO: test validations
    }
    
    /**
     * Verify OTP
     *
     * Manually verify a phone number by entering the OTP code received via SMS or voice call. This is a fallback for when the auto-verification webhook does not capture the code. Verification is valid for 90 days. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void verifyWhatsAppPhoneNumberTest() throws ApiException {
        String phoneNumberId = null;
        VerifyWhatsAppPhoneNumberRequest verifyWhatsAppPhoneNumberRequest = null;
        VerifyWhatsAppPhoneNumber200Response response = 
        api.verifyWhatsAppPhoneNumber(phoneNumberId, verifyWhatsAppPhoneNumberRequest);
        
        // TODO: test validations
    }
    
}
