/*
 * Late API
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.getlate.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import dev.getlate.ApiClient;
/**
 * Constraints: - Posts cannot mix videos and images. - Multiple images supported via attached_media (up to 10 images for feed posts). - Multiple videos in the same post are not supported. - Stories require media (single image or video); text captions are not displayed with stories. - Stories are ephemeral (disappear after 24 hours). - Use pageId to post to multiple pages from the same account connection. 
 */
@JsonPropertyOrder({
  FacebookPlatformData.JSON_PROPERTY_CONTENT_TYPE,
  FacebookPlatformData.JSON_PROPERTY_FIRST_COMMENT,
  FacebookPlatformData.JSON_PROPERTY_PAGE_ID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-11T13:29:34.044983308Z[Etc/UTC]", comments = "Generator version: 7.19.0")
public class FacebookPlatformData {
  /**
   * Set to &#39;story&#39; to publish as a Facebook Page Story (24-hour ephemeral content). Requires media.
   */
  public enum ContentTypeEnum {
    STORY(String.valueOf("story"));

    private String value;

    ContentTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ContentTypeEnum fromValue(String value) {
      for (ContentTypeEnum b : ContentTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_CONTENT_TYPE = "contentType";
  @javax.annotation.Nullable
  private ContentTypeEnum contentType;

  public static final String JSON_PROPERTY_FIRST_COMMENT = "firstComment";
  @javax.annotation.Nullable
  private String firstComment;

  public static final String JSON_PROPERTY_PAGE_ID = "pageId";
  @javax.annotation.Nullable
  private String pageId;

  public FacebookPlatformData() { 
  }

  public FacebookPlatformData contentType(@javax.annotation.Nullable ContentTypeEnum contentType) {
    this.contentType = contentType;
    return this;
  }

  /**
   * Set to &#39;story&#39; to publish as a Facebook Page Story (24-hour ephemeral content). Requires media.
   * @return contentType
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CONTENT_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public ContentTypeEnum getContentType() {
    return contentType;
  }


  @JsonProperty(value = JSON_PROPERTY_CONTENT_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContentType(@javax.annotation.Nullable ContentTypeEnum contentType) {
    this.contentType = contentType;
  }


  public FacebookPlatformData firstComment(@javax.annotation.Nullable String firstComment) {
    this.firstComment = firstComment;
    return this;
  }

  /**
   * Optional first comment to post immediately after publishing (feed posts only, not stories)
   * @return firstComment
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FIRST_COMMENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getFirstComment() {
    return firstComment;
  }


  @JsonProperty(value = JSON_PROPERTY_FIRST_COMMENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFirstComment(@javax.annotation.Nullable String firstComment) {
    this.firstComment = firstComment;
  }


  public FacebookPlatformData pageId(@javax.annotation.Nullable String pageId) {
    this.pageId = pageId;
    return this;
  }

  /**
   * Target Facebook Page ID for multi-page posting. If omitted, uses the selected/default page on the connection. Use GET /api/v1/accounts/{id}/facebook-page to list available pages. 
   * @return pageId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PAGE_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getPageId() {
    return pageId;
  }


  @JsonProperty(value = JSON_PROPERTY_PAGE_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPageId(@javax.annotation.Nullable String pageId) {
    this.pageId = pageId;
  }


  /**
   * Return true if this FacebookPlatformData object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FacebookPlatformData facebookPlatformData = (FacebookPlatformData) o;
    return Objects.equals(this.contentType, facebookPlatformData.contentType) &&
        Objects.equals(this.firstComment, facebookPlatformData.firstComment) &&
        Objects.equals(this.pageId, facebookPlatformData.pageId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(contentType, firstComment, pageId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FacebookPlatformData {\n");
    sb.append("    contentType: ").append(toIndentedString(contentType)).append("\n");
    sb.append("    firstComment: ").append(toIndentedString(firstComment)).append("\n");
    sb.append("    pageId: ").append(toIndentedString(pageId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `contentType` to the URL query string
    if (getContentType() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scontentType%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getContentType()))));
    }

    // add `firstComment` to the URL query string
    if (getFirstComment() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sfirstComment%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFirstComment()))));
    }

    // add `pageId` to the URL query string
    if (getPageId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%spageId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPageId()))));
    }

    return joiner.toString();
  }
}

