/*
 * Late API
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@getlate.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.getlate.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import dev.getlate.ApiClient;
/**
 * GetPreverifiedWhatsAppNumbers200ResponseNumbersInner
 */
@JsonPropertyOrder({
  GetPreverifiedWhatsAppNumbers200ResponseNumbersInner.JSON_PROPERTY_ID,
  GetPreverifiedWhatsAppNumbers200ResponseNumbersInner.JSON_PROPERTY_PHONE_NUMBER,
  GetPreverifiedWhatsAppNumbers200ResponseNumbersInner.JSON_PROPERTY_META_PREVERIFIED_ID,
  GetPreverifiedWhatsAppNumbers200ResponseNumbersInner.JSON_PROPERTY_META_VERIFIED_AT,
  GetPreverifiedWhatsAppNumbers200ResponseNumbersInner.JSON_PROPERTY_META_VERIFICATION_EXPIRES_AT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-11T08:59:44.740089086Z[Etc/UTC]", comments = "Generator version: 7.19.0")
public class GetPreverifiedWhatsAppNumbers200ResponseNumbersInner {
  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nullable
  private String id;

  public static final String JSON_PROPERTY_PHONE_NUMBER = "phoneNumber";
  @javax.annotation.Nullable
  private String phoneNumber;

  public static final String JSON_PROPERTY_META_PREVERIFIED_ID = "metaPreverifiedId";
  @javax.annotation.Nullable
  private String metaPreverifiedId;

  public static final String JSON_PROPERTY_META_VERIFIED_AT = "metaVerifiedAt";
  @javax.annotation.Nullable
  private OffsetDateTime metaVerifiedAt;

  public static final String JSON_PROPERTY_META_VERIFICATION_EXPIRES_AT = "metaVerificationExpiresAt";
  @javax.annotation.Nullable
  private OffsetDateTime metaVerificationExpiresAt;

  public GetPreverifiedWhatsAppNumbers200ResponseNumbersInner() { 
  }

  public GetPreverifiedWhatsAppNumbers200ResponseNumbersInner id(@javax.annotation.Nullable String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }


  public GetPreverifiedWhatsAppNumbers200ResponseNumbersInner phoneNumber(@javax.annotation.Nullable String phoneNumber) {
    this.phoneNumber = phoneNumber;
    return this;
  }

  /**
   * Get phoneNumber
   * @return phoneNumber
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PHONE_NUMBER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getPhoneNumber() {
    return phoneNumber;
  }


  @JsonProperty(value = JSON_PROPERTY_PHONE_NUMBER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPhoneNumber(@javax.annotation.Nullable String phoneNumber) {
    this.phoneNumber = phoneNumber;
  }


  public GetPreverifiedWhatsAppNumbers200ResponseNumbersInner metaPreverifiedId(@javax.annotation.Nullable String metaPreverifiedId) {
    this.metaPreverifiedId = metaPreverifiedId;
    return this;
  }

  /**
   * Get metaPreverifiedId
   * @return metaPreverifiedId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_META_PREVERIFIED_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getMetaPreverifiedId() {
    return metaPreverifiedId;
  }


  @JsonProperty(value = JSON_PROPERTY_META_PREVERIFIED_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMetaPreverifiedId(@javax.annotation.Nullable String metaPreverifiedId) {
    this.metaPreverifiedId = metaPreverifiedId;
  }


  public GetPreverifiedWhatsAppNumbers200ResponseNumbersInner metaVerifiedAt(@javax.annotation.Nullable OffsetDateTime metaVerifiedAt) {
    this.metaVerifiedAt = metaVerifiedAt;
    return this;
  }

  /**
   * Get metaVerifiedAt
   * @return metaVerifiedAt
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_META_VERIFIED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getMetaVerifiedAt() {
    return metaVerifiedAt;
  }


  @JsonProperty(value = JSON_PROPERTY_META_VERIFIED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMetaVerifiedAt(@javax.annotation.Nullable OffsetDateTime metaVerifiedAt) {
    this.metaVerifiedAt = metaVerifiedAt;
  }


  public GetPreverifiedWhatsAppNumbers200ResponseNumbersInner metaVerificationExpiresAt(@javax.annotation.Nullable OffsetDateTime metaVerificationExpiresAt) {
    this.metaVerificationExpiresAt = metaVerificationExpiresAt;
    return this;
  }

  /**
   * Get metaVerificationExpiresAt
   * @return metaVerificationExpiresAt
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_META_VERIFICATION_EXPIRES_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getMetaVerificationExpiresAt() {
    return metaVerificationExpiresAt;
  }


  @JsonProperty(value = JSON_PROPERTY_META_VERIFICATION_EXPIRES_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMetaVerificationExpiresAt(@javax.annotation.Nullable OffsetDateTime metaVerificationExpiresAt) {
    this.metaVerificationExpiresAt = metaVerificationExpiresAt;
  }


  /**
   * Return true if this getPreverifiedWhatsAppNumbers_200_response_numbers_inner object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetPreverifiedWhatsAppNumbers200ResponseNumbersInner getPreverifiedWhatsAppNumbers200ResponseNumbersInner = (GetPreverifiedWhatsAppNumbers200ResponseNumbersInner) o;
    return Objects.equals(this.id, getPreverifiedWhatsAppNumbers200ResponseNumbersInner.id) &&
        Objects.equals(this.phoneNumber, getPreverifiedWhatsAppNumbers200ResponseNumbersInner.phoneNumber) &&
        Objects.equals(this.metaPreverifiedId, getPreverifiedWhatsAppNumbers200ResponseNumbersInner.metaPreverifiedId) &&
        Objects.equals(this.metaVerifiedAt, getPreverifiedWhatsAppNumbers200ResponseNumbersInner.metaVerifiedAt) &&
        Objects.equals(this.metaVerificationExpiresAt, getPreverifiedWhatsAppNumbers200ResponseNumbersInner.metaVerificationExpiresAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, phoneNumber, metaPreverifiedId, metaVerifiedAt, metaVerificationExpiresAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetPreverifiedWhatsAppNumbers200ResponseNumbersInner {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    phoneNumber: ").append(toIndentedString(phoneNumber)).append("\n");
    sb.append("    metaPreverifiedId: ").append(toIndentedString(metaPreverifiedId)).append("\n");
    sb.append("    metaVerifiedAt: ").append(toIndentedString(metaVerifiedAt)).append("\n");
    sb.append("    metaVerificationExpiresAt: ").append(toIndentedString(metaVerificationExpiresAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getId()))));
    }

    // add `phoneNumber` to the URL query string
    if (getPhoneNumber() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sphoneNumber%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPhoneNumber()))));
    }

    // add `metaPreverifiedId` to the URL query string
    if (getMetaPreverifiedId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smetaPreverifiedId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMetaPreverifiedId()))));
    }

    // add `metaVerifiedAt` to the URL query string
    if (getMetaVerifiedAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smetaVerifiedAt%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMetaVerifiedAt()))));
    }

    // add `metaVerificationExpiresAt` to the URL query string
    if (getMetaVerificationExpiresAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smetaVerificationExpiresAt%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMetaVerificationExpiresAt()))));
    }

    return joiner.toString();
  }
}

