/*
 * Late API
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@getlate.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.getlate.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.getlate.model.GetPreverifiedWhatsAppNumbers200ResponseNumbersInner;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import dev.getlate.ApiClient;
/**
 * GetPreverifiedWhatsAppNumbers200Response
 */
@JsonPropertyOrder({
  GetPreverifiedWhatsAppNumbers200Response.JSON_PROPERTY_PRE_VERIFIED_IDS,
  GetPreverifiedWhatsAppNumbers200Response.JSON_PROPERTY_NUMBERS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-11T08:59:44.740089086Z[Etc/UTC]", comments = "Generator version: 7.19.0")
public class GetPreverifiedWhatsAppNumbers200Response {
  public static final String JSON_PROPERTY_PRE_VERIFIED_IDS = "preVerifiedIds";
  @javax.annotation.Nullable
  private List<String> preVerifiedIds = new ArrayList<>();

  public static final String JSON_PROPERTY_NUMBERS = "numbers";
  @javax.annotation.Nullable
  private List<GetPreverifiedWhatsAppNumbers200ResponseNumbersInner> numbers = new ArrayList<>();

  public GetPreverifiedWhatsAppNumbers200Response() { 
  }

  public GetPreverifiedWhatsAppNumbers200Response preVerifiedIds(@javax.annotation.Nullable List<String> preVerifiedIds) {
    this.preVerifiedIds = preVerifiedIds;
    return this;
  }

  public GetPreverifiedWhatsAppNumbers200Response addPreVerifiedIdsItem(String preVerifiedIdsItem) {
    if (this.preVerifiedIds == null) {
      this.preVerifiedIds = new ArrayList<>();
    }
    this.preVerifiedIds.add(preVerifiedIdsItem);
    return this;
  }

  /**
   * IDs to pass in FB.login() extras.setup.preVerifiedPhone.ids
   * @return preVerifiedIds
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PRE_VERIFIED_IDS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<String> getPreVerifiedIds() {
    return preVerifiedIds;
  }


  @JsonProperty(value = JSON_PROPERTY_PRE_VERIFIED_IDS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPreVerifiedIds(@javax.annotation.Nullable List<String> preVerifiedIds) {
    this.preVerifiedIds = preVerifiedIds;
  }


  public GetPreverifiedWhatsAppNumbers200Response numbers(@javax.annotation.Nullable List<GetPreverifiedWhatsAppNumbers200ResponseNumbersInner> numbers) {
    this.numbers = numbers;
    return this;
  }

  public GetPreverifiedWhatsAppNumbers200Response addNumbersItem(GetPreverifiedWhatsAppNumbers200ResponseNumbersInner numbersItem) {
    if (this.numbers == null) {
      this.numbers = new ArrayList<>();
    }
    this.numbers.add(numbersItem);
    return this;
  }

  /**
   * Get numbers
   * @return numbers
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NUMBERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<GetPreverifiedWhatsAppNumbers200ResponseNumbersInner> getNumbers() {
    return numbers;
  }


  @JsonProperty(value = JSON_PROPERTY_NUMBERS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNumbers(@javax.annotation.Nullable List<GetPreverifiedWhatsAppNumbers200ResponseNumbersInner> numbers) {
    this.numbers = numbers;
  }


  /**
   * Return true if this getPreverifiedWhatsAppNumbers_200_response object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetPreverifiedWhatsAppNumbers200Response getPreverifiedWhatsAppNumbers200Response = (GetPreverifiedWhatsAppNumbers200Response) o;
    return Objects.equals(this.preVerifiedIds, getPreverifiedWhatsAppNumbers200Response.preVerifiedIds) &&
        Objects.equals(this.numbers, getPreverifiedWhatsAppNumbers200Response.numbers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(preVerifiedIds, numbers);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetPreverifiedWhatsAppNumbers200Response {\n");
    sb.append("    preVerifiedIds: ").append(toIndentedString(preVerifiedIds)).append("\n");
    sb.append("    numbers: ").append(toIndentedString(numbers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `preVerifiedIds` to the URL query string
    if (getPreVerifiedIds() != null) {
      for (int i = 0; i < getPreVerifiedIds().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%spreVerifiedIds%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getPreVerifiedIds().get(i)))));
      }
    }

    // add `numbers` to the URL query string
    if (getNumbers() != null) {
      for (int i = 0; i < getNumbers().size(); i++) {
        if (getNumbers().get(i) != null) {
          joiner.add(getNumbers().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%snumbers%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }
}

