/*
 * Late API
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.getlate.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import dev.getlate.ApiClient;
/**
 * YouTube video upload settings: - Videos ≤ 3 minutes are automatically detected as YouTube Shorts - Videos &gt; 3 minutes become regular YouTube videos - Custom thumbnails supported for regular videos (via mediaItem.thumbnail) - Custom thumbnails NOT supported for Shorts via API - Scheduled videos are uploaded immediately as the specified visibility and published at scheduled time - Visibility defaults to \&quot;public\&quot; if not specified - madeForKids defaults to false (not child-directed) - Set containsSyntheticMedia: true if your video contains AI-generated content 
 */
@JsonPropertyOrder({
  YouTubePlatformData.JSON_PROPERTY_TITLE,
  YouTubePlatformData.JSON_PROPERTY_VISIBILITY,
  YouTubePlatformData.JSON_PROPERTY_MADE_FOR_KIDS,
  YouTubePlatformData.JSON_PROPERTY_FIRST_COMMENT,
  YouTubePlatformData.JSON_PROPERTY_CONTAINS_SYNTHETIC_MEDIA,
  YouTubePlatformData.JSON_PROPERTY_CATEGORY_ID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-16T11:05:25.291910694Z[Etc/UTC]", comments = "Generator version: 7.19.0")
public class YouTubePlatformData {
  public static final String JSON_PROPERTY_TITLE = "title";
  @javax.annotation.Nullable
  private String title;

  /**
   * Video visibility setting: - public: Anyone can search for and watch (default) - unlisted: Only people with the link can watch - private: Only you and people you specifically share with can watch 
   */
  public enum VisibilityEnum {
    PUBLIC(String.valueOf("public")),
    
    PRIVATE(String.valueOf("private")),
    
    UNLISTED(String.valueOf("unlisted"));

    private String value;

    VisibilityEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static VisibilityEnum fromValue(String value) {
      for (VisibilityEnum b : VisibilityEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_VISIBILITY = "visibility";
  @javax.annotation.Nullable
  private VisibilityEnum visibility = VisibilityEnum.PUBLIC;

  public static final String JSON_PROPERTY_MADE_FOR_KIDS = "madeForKids";
  @javax.annotation.Nullable
  private Boolean madeForKids = false;

  public static final String JSON_PROPERTY_FIRST_COMMENT = "firstComment";
  @javax.annotation.Nullable
  private String firstComment;

  public static final String JSON_PROPERTY_CONTAINS_SYNTHETIC_MEDIA = "containsSyntheticMedia";
  @javax.annotation.Nullable
  private Boolean containsSyntheticMedia = false;

  public static final String JSON_PROPERTY_CATEGORY_ID = "categoryId";
  @javax.annotation.Nullable
  private String categoryId = "22";

  public YouTubePlatformData() { 
  }

  public YouTubePlatformData title(@javax.annotation.Nullable String title) {
    this.title = title;
    return this;
  }

  /**
   * Video title. Defaults to first line of content or \&quot;Untitled Video\&quot;. Must be ≤ 100 characters.
   * @return title
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TITLE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getTitle() {
    return title;
  }


  @JsonProperty(value = JSON_PROPERTY_TITLE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTitle(@javax.annotation.Nullable String title) {
    this.title = title;
  }


  public YouTubePlatformData visibility(@javax.annotation.Nullable VisibilityEnum visibility) {
    this.visibility = visibility;
    return this;
  }

  /**
   * Video visibility setting: - public: Anyone can search for and watch (default) - unlisted: Only people with the link can watch - private: Only you and people you specifically share with can watch 
   * @return visibility
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VISIBILITY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public VisibilityEnum getVisibility() {
    return visibility;
  }


  @JsonProperty(value = JSON_PROPERTY_VISIBILITY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVisibility(@javax.annotation.Nullable VisibilityEnum visibility) {
    this.visibility = visibility;
  }


  public YouTubePlatformData madeForKids(@javax.annotation.Nullable Boolean madeForKids) {
    this.madeForKids = madeForKids;
    return this;
  }

  /**
   * COPPA compliance: Audience designation for the video. - true: Video is made for kids (child-directed content) - false: Video is NOT made for kids (default)  This field maps to YouTube&#39;s &#x60;selfDeclaredMadeForKids&#x60; setting. Videos marked as made for kids have restricted features (no comments, no notifications, limited ad targeting).  IMPORTANT: If not specified, defaults to false. YouTube requires this to be explicitly set, otherwise the video may be blocked from views until configured in YouTube Studio. 
   * @return madeForKids
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MADE_FOR_KIDS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getMadeForKids() {
    return madeForKids;
  }


  @JsonProperty(value = JSON_PROPERTY_MADE_FOR_KIDS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMadeForKids(@javax.annotation.Nullable Boolean madeForKids) {
    this.madeForKids = madeForKids;
  }


  public YouTubePlatformData firstComment(@javax.annotation.Nullable String firstComment) {
    this.firstComment = firstComment;
    return this;
  }

  /**
   * Optional first comment to post immediately after video upload. Up to 10,000 characters (YouTube&#39;s comment limit).
   * @return firstComment
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FIRST_COMMENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getFirstComment() {
    return firstComment;
  }


  @JsonProperty(value = JSON_PROPERTY_FIRST_COMMENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFirstComment(@javax.annotation.Nullable String firstComment) {
    this.firstComment = firstComment;
  }


  public YouTubePlatformData containsSyntheticMedia(@javax.annotation.Nullable Boolean containsSyntheticMedia) {
    this.containsSyntheticMedia = containsSyntheticMedia;
    return this;
  }

  /**
   * AI-generated content disclosure flag. Set to true if your video contains AI-generated or synthetic content that could be mistaken for real people, places, or events. This helps viewers understand when realistic content has been created or altered using AI. YouTube may add a label to videos when this is set. Added to YouTube Data API in October 2024. 
   * @return containsSyntheticMedia
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CONTAINS_SYNTHETIC_MEDIA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getContainsSyntheticMedia() {
    return containsSyntheticMedia;
  }


  @JsonProperty(value = JSON_PROPERTY_CONTAINS_SYNTHETIC_MEDIA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContainsSyntheticMedia(@javax.annotation.Nullable Boolean containsSyntheticMedia) {
    this.containsSyntheticMedia = containsSyntheticMedia;
  }


  public YouTubePlatformData categoryId(@javax.annotation.Nullable String categoryId) {
    this.categoryId = categoryId;
    return this;
  }

  /**
   * YouTube video category ID. Defaults to &#39;22&#39; (People &amp; Blogs). Common categories: 1 (Film &amp; Animation), 2 (Autos &amp; Vehicles), 10 (Music), 15 (Pets &amp; Animals), 17 (Sports), 20 (Gaming), 22 (People &amp; Blogs), 23 (Comedy), 24 (Entertainment), 25 (News &amp; Politics), 26 (Howto &amp; Style), 27 (Education), 28 (Science &amp; Technology). 
   * @return categoryId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CATEGORY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCategoryId() {
    return categoryId;
  }


  @JsonProperty(value = JSON_PROPERTY_CATEGORY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCategoryId(@javax.annotation.Nullable String categoryId) {
    this.categoryId = categoryId;
  }


  /**
   * Return true if this YouTubePlatformData object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    YouTubePlatformData youTubePlatformData = (YouTubePlatformData) o;
    return Objects.equals(this.title, youTubePlatformData.title) &&
        Objects.equals(this.visibility, youTubePlatformData.visibility) &&
        Objects.equals(this.madeForKids, youTubePlatformData.madeForKids) &&
        Objects.equals(this.firstComment, youTubePlatformData.firstComment) &&
        Objects.equals(this.containsSyntheticMedia, youTubePlatformData.containsSyntheticMedia) &&
        Objects.equals(this.categoryId, youTubePlatformData.categoryId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(title, visibility, madeForKids, firstComment, containsSyntheticMedia, categoryId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class YouTubePlatformData {\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    visibility: ").append(toIndentedString(visibility)).append("\n");
    sb.append("    madeForKids: ").append(toIndentedString(madeForKids)).append("\n");
    sb.append("    firstComment: ").append(toIndentedString(firstComment)).append("\n");
    sb.append("    containsSyntheticMedia: ").append(toIndentedString(containsSyntheticMedia)).append("\n");
    sb.append("    categoryId: ").append(toIndentedString(categoryId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `title` to the URL query string
    if (getTitle() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%stitle%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTitle()))));
    }

    // add `visibility` to the URL query string
    if (getVisibility() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%svisibility%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getVisibility()))));
    }

    // add `madeForKids` to the URL query string
    if (getMadeForKids() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%smadeForKids%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMadeForKids()))));
    }

    // add `firstComment` to the URL query string
    if (getFirstComment() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sfirstComment%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFirstComment()))));
    }

    // add `containsSyntheticMedia` to the URL query string
    if (getContainsSyntheticMedia() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scontainsSyntheticMedia%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getContainsSyntheticMedia()))));
    }

    // add `categoryId` to the URL query string
    if (getCategoryId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scategoryId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCategoryId()))));
    }

    return joiner.toString();
  }
}

