/*
 * Zernio API
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.zernio.api;

import dev.zernio.ApiException;
import dev.zernio.model.CreateCommentAutomationRequest;
import dev.zernio.model.InlineObject;
import dev.zernio.model.InlineObject1;
import dev.zernio.model.ListCommentAutomations200Response;
import dev.zernio.model.UpdateCommentAutomationRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for CommentAutomationsApi
 */
@Disabled
public class CommentAutomationsApiTest {

    private final CommentAutomationsApi api = new CommentAutomationsApi();

    
    /**
     * Create a comment-to-DM automation
     *
     * Create a keyword-triggered DM automation on an Instagram or Facebook post. When someone comments a matching keyword, they automatically receive a DM. Only one active automation per post is allowed. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createCommentAutomationTest() throws ApiException {
        CreateCommentAutomationRequest createCommentAutomationRequest = null;
        
        api.createCommentAutomation(createCommentAutomationRequest);
        
        // TODO: test validations
    }
    
    /**
     * Delete automation and all logs
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteCommentAutomationTest() throws ApiException {
        String automationId = null;
        
        api.deleteCommentAutomation(automationId);
        
        // TODO: test validations
    }
    
    /**
     * Get automation details with recent logs
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCommentAutomationTest() throws ApiException {
        String automationId = null;
        
        api.getCommentAutomation(automationId);
        
        // TODO: test validations
    }
    
    /**
     * List trigger logs for an automation
     *
     * Paginated list of every comment that triggered this automation, with send status and commenter info.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listCommentAutomationLogsTest() throws ApiException {
        String automationId = null;
        String status = null;
        Integer limit = null;
        Integer skip = null;
        
        api.listCommentAutomationLogs(automationId, status, limit, skip);
        
        // TODO: test validations
    }
    
    /**
     * List comment-to-DM automations
     *
     * List all comment-to-DM automations for a profile. Returns automations with their stats.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listCommentAutomationsTest() throws ApiException {
        String profileId = null;
        ListCommentAutomations200Response response = 
        api.listCommentAutomations(profileId);
        
        // TODO: test validations
    }
    
    /**
     * Update automation settings
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateCommentAutomationTest() throws ApiException {
        String automationId = null;
        UpdateCommentAutomationRequest updateCommentAutomationRequest = null;
        
        api.updateCommentAutomation(automationId, updateCommentAutomationRequest);
        
        // TODO: test validations
    }
    
}
