/*
 * Zernio API
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.zernio.api;

import dev.zernio.ApiException;
import dev.zernio.model.CreateCustomFieldRequest;
import dev.zernio.model.InlineObject;
import dev.zernio.model.InlineObject1;
import dev.zernio.model.SetContactFieldValueRequest;
import dev.zernio.model.UpdateCustomFieldRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for CustomFieldsApi
 */
@Disabled
public class CustomFieldsApiTest {

    private final CustomFieldsApi api = new CustomFieldsApi();

    
    /**
     * Clear a custom field value
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void clearContactFieldValueTest() throws ApiException {
        String contactId = null;
        String slug = null;
        
        api.clearContactFieldValue(contactId, slug);
        
        // TODO: test validations
    }
    
    /**
     * Create a custom field definition
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createCustomFieldTest() throws ApiException {
        CreateCustomFieldRequest createCustomFieldRequest = null;
        
        api.createCustomField(createCustomFieldRequest);
        
        // TODO: test validations
    }
    
    /**
     * Delete a custom field definition
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteCustomFieldTest() throws ApiException {
        String fieldId = null;
        
        api.deleteCustomField(fieldId);
        
        // TODO: test validations
    }
    
    /**
     * List custom field definitions
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listCustomFieldsTest() throws ApiException {
        String profileId = null;
        
        api.listCustomFields(profileId);
        
        // TODO: test validations
    }
    
    /**
     * Set a custom field value
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void setContactFieldValueTest() throws ApiException {
        String contactId = null;
        String slug = null;
        SetContactFieldValueRequest setContactFieldValueRequest = null;
        
        api.setContactFieldValue(contactId, slug, setContactFieldValueRequest);
        
        // TODO: test validations
    }
    
    /**
     * Update a custom field definition
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateCustomFieldTest() throws ApiException {
        String fieldId = null;
        UpdateCustomFieldRequest updateCustomFieldRequest = null;
        
        api.updateCustomField(fieldId, updateCustomFieldRequest);
        
        // TODO: test validations
    }
    
}
