/*
 * Zernio API
 * API reference for Zernio. Authenticate with a Bearer API key. Base URL: https://zernio.com/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@zernio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.zernio.api;

import dev.zernio.ApiException;
import dev.zernio.model.CreateWhatsAppFlow200Response;
import dev.zernio.model.CreateWhatsAppFlowRequest;
import dev.zernio.model.GetWhatsAppFlow200Response;
import dev.zernio.model.GetWhatsAppFlowJson200Response;
import dev.zernio.model.InlineObject;
import dev.zernio.model.ListWhatsAppFlows200Response;
import dev.zernio.model.PublishWhatsAppFlowRequest;
import dev.zernio.model.SendWhatsAppFlowMessage200Response;
import dev.zernio.model.SendWhatsAppFlowMessageRequest;
import dev.zernio.model.UpdateWhatsAppFlowRequest;
import dev.zernio.model.UpdateYoutubeDefaultPlaylist200Response;
import dev.zernio.model.UploadWhatsAppFlowJson200Response;
import dev.zernio.model.UploadWhatsAppFlowJsonRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for WhatsAppFlowsApi
 */
@Disabled
public class WhatsAppFlowsApiTest {

    private final WhatsAppFlowsApi api = new WhatsAppFlowsApi();

    
    /**
     * Create flow
     *
     * Create a new WhatsApp Flow in DRAFT status. Optionally clone an existing flow. After creating, upload a Flow JSON definition, then publish to make it sendable. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createWhatsAppFlowTest() throws ApiException {
        CreateWhatsAppFlowRequest createWhatsAppFlowRequest = null;
        CreateWhatsAppFlow200Response response = 
        api.createWhatsAppFlow(createWhatsAppFlowRequest);
        
        // TODO: test validations
    }
    
    /**
     * Delete flow
     *
     * Delete a DRAFT flow. This is irreversible. Only flows in DRAFT status can be deleted. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteWhatsAppFlowTest() throws ApiException {
        String flowId = null;
        String accountId = null;
        UpdateYoutubeDefaultPlaylist200Response response = 
        api.deleteWhatsAppFlow(flowId, accountId);
        
        // TODO: test validations
    }
    
    /**
     * Deprecate flow
     *
     * Deprecate a PUBLISHED flow. **This is irreversible.** Deprecated flows cannot be sent or opened, but existing active sessions may continue until they complete. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deprecateWhatsAppFlowTest() throws ApiException {
        String flowId = null;
        PublishWhatsAppFlowRequest publishWhatsAppFlowRequest = null;
        UpdateYoutubeDefaultPlaylist200Response response = 
        api.deprecateWhatsAppFlow(flowId, publishWhatsAppFlowRequest);
        
        // TODO: test validations
    }
    
    /**
     * Get flow
     *
     * Get details for a specific flow, including status, categories, validation errors, and preview URL. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getWhatsAppFlowTest() throws ApiException {
        String flowId = null;
        String accountId = null;
        String fields = null;
        GetWhatsAppFlow200Response response = 
        api.getWhatsAppFlow(flowId, accountId, fields);
        
        // TODO: test validations
    }
    
    /**
     * Get flow JSON asset
     *
     * Get the flow JSON asset metadata, including a temporary download URL for the Flow JSON file. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getWhatsAppFlowJsonTest() throws ApiException {
        String flowId = null;
        String accountId = null;
        GetWhatsAppFlowJson200Response response = 
        api.getWhatsAppFlowJson(flowId, accountId);
        
        // TODO: test validations
    }
    
    /**
     * List flows
     *
     * List all WhatsApp Flows for the Business Account (WABA) associated with the given account. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listWhatsAppFlowsTest() throws ApiException {
        String accountId = null;
        ListWhatsAppFlows200Response response = 
        api.listWhatsAppFlows(accountId);
        
        // TODO: test validations
    }
    
    /**
     * Publish flow
     *
     * Publish a DRAFT flow. **This is irreversible.** Once published, the flow and its JSON become immutable and the flow can be sent to users. To update a published flow, create a new flow (optionally cloning this one via &#x60;cloneFlowId&#x60;). 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void publishWhatsAppFlowTest() throws ApiException {
        String flowId = null;
        PublishWhatsAppFlowRequest publishWhatsAppFlowRequest = null;
        UpdateYoutubeDefaultPlaylist200Response response = 
        api.publishWhatsAppFlow(flowId, publishWhatsAppFlowRequest);
        
        // TODO: test validations
    }
    
    /**
     * Send flow message
     *
     * Send a published flow as an interactive message with a CTA button. When the recipient taps the button, the flow opens natively in WhatsApp. Flow responses are received via webhooks. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void sendWhatsAppFlowMessageTest() throws ApiException {
        SendWhatsAppFlowMessageRequest sendWhatsAppFlowMessageRequest = null;
        SendWhatsAppFlowMessage200Response response = 
        api.sendWhatsAppFlowMessage(sendWhatsAppFlowMessageRequest);
        
        // TODO: test validations
    }
    
    /**
     * Update flow
     *
     * Update metadata (name, categories) of a DRAFT flow. Published flows are immutable. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateWhatsAppFlowTest() throws ApiException {
        String flowId = null;
        UpdateWhatsAppFlowRequest updateWhatsAppFlowRequest = null;
        UpdateYoutubeDefaultPlaylist200Response response = 
        api.updateWhatsAppFlow(flowId, updateWhatsAppFlowRequest);
        
        // TODO: test validations
    }
    
    /**
     * Upload flow JSON
     *
     * Upload or update the Flow JSON for a DRAFT flow. The Flow JSON defines all screens, components (text inputs, dropdowns, date pickers, etc.), and navigation.  Meta validates the JSON on upload and returns any validation errors. See: https://developers.facebook.com/docs/whatsapp/flows/reference/flowjson 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void uploadWhatsAppFlowJsonTest() throws ApiException {
        String flowId = null;
        UploadWhatsAppFlowJsonRequest uploadWhatsAppFlowJsonRequest = null;
        UploadWhatsAppFlowJson200Response response = 
        api.uploadWhatsAppFlowJson(flowId, uploadWhatsAppFlowJsonRequest);
        
        // TODO: test validations
    }
    
}
