/*
 * Late API
 * API reference for Late. Authenticate with a Bearer API key. Base URL: https://getlate.dev/api 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@getlate.dev
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package dev.getlate.api;

import dev.getlate.ApiClient;
import dev.getlate.ApiException;
import dev.getlate.ApiResponse;
import dev.getlate.Configuration;
import dev.getlate.Pair;

import dev.getlate.model.GetPreverifiedWhatsAppNumbers200Response;
import dev.getlate.model.GetWhatsAppPhoneNumber200Response;
import dev.getlate.model.GetWhatsAppPhoneNumbers200Response;
import dev.getlate.model.InlineObject;
import dev.getlate.model.InlineObject1;
import dev.getlate.model.PurchaseWhatsAppPhoneNumber200Response;
import dev.getlate.model.PurchaseWhatsAppPhoneNumberRequest;
import dev.getlate.model.ReleaseWhatsAppPhoneNumber200Response;
import dev.getlate.model.RequestWhatsAppVerificationCode200Response;
import dev.getlate.model.RequestWhatsAppVerificationCodeRequest;
import dev.getlate.model.SearchAvailableWhatsAppNumbers200Response;
import dev.getlate.model.VerifyWhatsAppPhoneNumber200Response;
import dev.getlate.model.VerifyWhatsAppPhoneNumberRequest;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import org.apache.http.HttpEntity;
import org.apache.http.NameValuePair;
import org.apache.http.entity.mime.MultipartEntityBuilder;
import org.apache.http.message.BasicNameValuePair;
import org.apache.http.client.entity.UrlEncodedFormEntity;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-11T08:59:44.740089086Z[Etc/UTC]", comments = "Generator version: 7.19.0")
public class WhatsAppPhoneNumbersApi {
  /**
   * Utility class for extending HttpRequest.Builder functionality.
   */
  private static class HttpRequestBuilderExtensions {
    /**
     * Adds additional headers to the provided HttpRequest.Builder. Useful for adding method/endpoint specific headers.
     *
     * @param builder the HttpRequest.Builder to which headers will be added
     * @param headers a map of header names and values to add; may be null
     * @return the same HttpRequest.Builder instance with the additional headers set
     */
    static HttpRequest.Builder withAdditionalHeaders(HttpRequest.Builder builder, Map<String, String> headers) {
        if (headers != null) {
            for (Map.Entry<String, String> entry : headers.entrySet()) {
                builder.header(entry.getKey(), entry.getValue());
            }
        }
        return builder;
    }
  }
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<InputStream>> memberVarAsyncResponseInterceptor;

  public WhatsAppPhoneNumbersApi() {
    this(Configuration.getDefaultApiClient());
  }

  public WhatsAppPhoneNumbersApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }


  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    InputStream responseBody = ApiClient.getResponseBody(response);
    String body = null;
    try {
      body = responseBody == null ? null : new String(responseBody.readAllBytes());
    } finally {
      if (responseBody != null) {
        responseBody.close();
      }
    }
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Download file from the given response.
   *
   * @param response Response
   * @return File
   * @throws ApiException If fail to read file content from response and write to disk
   */
  public File downloadFileFromResponse(HttpResponse<InputStream> response, InputStream responseBody) throws ApiException {
    if (responseBody == null) {
      throw new ApiException(new IOException("Response body is empty"));
    }
    try {
      File file = prepareDownloadFile(response);
      java.nio.file.Files.copy(responseBody, file.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
      return file;
    } catch (IOException e) {
      throw new ApiException(e);
    }
  }

  /**
   * <p>Prepare the file for download from the response.</p>
   *
   * @param response a {@link java.net.http.HttpResponse} object.
   * @return a {@link java.io.File} object.
   * @throws java.io.IOException if any.
   */
  private File prepareDownloadFile(HttpResponse<InputStream> response) throws IOException {
    String filename = null;
    java.util.Optional<String> contentDisposition = response.headers().firstValue("Content-Disposition");
    if (contentDisposition.isPresent() && !"".equals(contentDisposition.get())) {
      // Get filename from the Content-Disposition header.
      java.util.regex.Pattern pattern = java.util.regex.Pattern.compile("filename=['\"]?([^'\"\\s]+)['\"]?");
      java.util.regex.Matcher matcher = pattern.matcher(contentDisposition.get());
      if (matcher.find())
        filename = matcher.group(1);
    }
    File file = null;
    if (filename != null) {
      java.nio.file.Path tempDir = java.nio.file.Files.createTempDirectory("swagger-gen-native");
      java.nio.file.Path filePath = java.nio.file.Files.createFile(tempDir.resolve(filename));
      file = filePath.toFile();
      tempDir.toFile().deleteOnExit();   // best effort cleanup
      file.deleteOnExit(); // best effort cleanup
    } else {
      file = java.nio.file.Files.createTempFile("download-", "").toFile();
      file.deleteOnExit(); // best effort cleanup
    }
    return file;
  }

  /**
   * Get pre-verified numbers
   * Returns the user&#39;s pre-verified phone number IDs that are ready for OTP-free Embedded Signup. Only returns numbers with verified Meta status and non-expired verification. 
   * @param profileId Profile ID to filter by (required)
   * @return GetPreverifiedWhatsAppNumbers200Response
   * @throws ApiException if fails to make API call
   */
  public GetPreverifiedWhatsAppNumbers200Response getPreverifiedWhatsAppNumbers(@javax.annotation.Nonnull String profileId) throws ApiException {
    return getPreverifiedWhatsAppNumbers(profileId, null);
  }

  /**
   * Get pre-verified numbers
   * Returns the user&#39;s pre-verified phone number IDs that are ready for OTP-free Embedded Signup. Only returns numbers with verified Meta status and non-expired verification. 
   * @param profileId Profile ID to filter by (required)
   * @param headers Optional headers to include in the request
   * @return GetPreverifiedWhatsAppNumbers200Response
   * @throws ApiException if fails to make API call
   */
  public GetPreverifiedWhatsAppNumbers200Response getPreverifiedWhatsAppNumbers(@javax.annotation.Nonnull String profileId, Map<String, String> headers) throws ApiException {
    ApiResponse<GetPreverifiedWhatsAppNumbers200Response> localVarResponse = getPreverifiedWhatsAppNumbersWithHttpInfo(profileId, headers);
    return localVarResponse.getData();
  }

  /**
   * Get pre-verified numbers
   * Returns the user&#39;s pre-verified phone number IDs that are ready for OTP-free Embedded Signup. Only returns numbers with verified Meta status and non-expired verification. 
   * @param profileId Profile ID to filter by (required)
   * @return ApiResponse&lt;GetPreverifiedWhatsAppNumbers200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<GetPreverifiedWhatsAppNumbers200Response> getPreverifiedWhatsAppNumbersWithHttpInfo(@javax.annotation.Nonnull String profileId) throws ApiException {
    return getPreverifiedWhatsAppNumbersWithHttpInfo(profileId, null);
  }

  /**
   * Get pre-verified numbers
   * Returns the user&#39;s pre-verified phone number IDs that are ready for OTP-free Embedded Signup. Only returns numbers with verified Meta status and non-expired verification. 
   * @param profileId Profile ID to filter by (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;GetPreverifiedWhatsAppNumbers200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<GetPreverifiedWhatsAppNumbers200Response> getPreverifiedWhatsAppNumbersWithHttpInfo(@javax.annotation.Nonnull String profileId, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getPreverifiedWhatsAppNumbersRequestBuilder(profileId, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getPreverifiedWhatsAppNumbers", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<GetPreverifiedWhatsAppNumbers200Response>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        GetPreverifiedWhatsAppNumbers200Response responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<GetPreverifiedWhatsAppNumbers200Response>() {});
        

        return new ApiResponse<GetPreverifiedWhatsAppNumbers200Response>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getPreverifiedWhatsAppNumbersRequestBuilder(@javax.annotation.Nonnull String profileId, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'profileId' is set
    if (profileId == null) {
      throw new ApiException(400, "Missing the required parameter 'profileId' when calling getPreverifiedWhatsAppNumbers");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/whatsapp/phone-numbers/preverified";

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "profileId";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("profileId", profileId));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get phone number
   * Retrieve the current status of a purchased phone number. Used to poll for Meta pre-verification completion after purchase. 
   * @param phoneNumberId Phone number record ID (required)
   * @return GetWhatsAppPhoneNumber200Response
   * @throws ApiException if fails to make API call
   */
  public GetWhatsAppPhoneNumber200Response getWhatsAppPhoneNumber(@javax.annotation.Nonnull String phoneNumberId) throws ApiException {
    return getWhatsAppPhoneNumber(phoneNumberId, null);
  }

  /**
   * Get phone number
   * Retrieve the current status of a purchased phone number. Used to poll for Meta pre-verification completion after purchase. 
   * @param phoneNumberId Phone number record ID (required)
   * @param headers Optional headers to include in the request
   * @return GetWhatsAppPhoneNumber200Response
   * @throws ApiException if fails to make API call
   */
  public GetWhatsAppPhoneNumber200Response getWhatsAppPhoneNumber(@javax.annotation.Nonnull String phoneNumberId, Map<String, String> headers) throws ApiException {
    ApiResponse<GetWhatsAppPhoneNumber200Response> localVarResponse = getWhatsAppPhoneNumberWithHttpInfo(phoneNumberId, headers);
    return localVarResponse.getData();
  }

  /**
   * Get phone number
   * Retrieve the current status of a purchased phone number. Used to poll for Meta pre-verification completion after purchase. 
   * @param phoneNumberId Phone number record ID (required)
   * @return ApiResponse&lt;GetWhatsAppPhoneNumber200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<GetWhatsAppPhoneNumber200Response> getWhatsAppPhoneNumberWithHttpInfo(@javax.annotation.Nonnull String phoneNumberId) throws ApiException {
    return getWhatsAppPhoneNumberWithHttpInfo(phoneNumberId, null);
  }

  /**
   * Get phone number
   * Retrieve the current status of a purchased phone number. Used to poll for Meta pre-verification completion after purchase. 
   * @param phoneNumberId Phone number record ID (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;GetWhatsAppPhoneNumber200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<GetWhatsAppPhoneNumber200Response> getWhatsAppPhoneNumberWithHttpInfo(@javax.annotation.Nonnull String phoneNumberId, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getWhatsAppPhoneNumberRequestBuilder(phoneNumberId, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getWhatsAppPhoneNumber", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<GetWhatsAppPhoneNumber200Response>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        GetWhatsAppPhoneNumber200Response responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<GetWhatsAppPhoneNumber200Response>() {});
        

        return new ApiResponse<GetWhatsAppPhoneNumber200Response>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getWhatsAppPhoneNumberRequestBuilder(@javax.annotation.Nonnull String phoneNumberId, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'phoneNumberId' is set
    if (phoneNumberId == null) {
      throw new ApiException(400, "Missing the required parameter 'phoneNumberId' when calling getWhatsAppPhoneNumber");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/whatsapp/phone-numbers/{phoneNumberId}"
        .replace("{phoneNumberId}", ApiClient.urlEncode(phoneNumberId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * List phone numbers
   * List all WhatsApp phone numbers purchased by the authenticated user. By default, released numbers are excluded. 
   * @param status Filter by status (by default excludes released numbers) (optional)
   * @param profileId Filter by profile (optional)
   * @return GetWhatsAppPhoneNumbers200Response
   * @throws ApiException if fails to make API call
   */
  public GetWhatsAppPhoneNumbers200Response getWhatsAppPhoneNumbers(@javax.annotation.Nullable String status, @javax.annotation.Nullable String profileId) throws ApiException {
    return getWhatsAppPhoneNumbers(status, profileId, null);
  }

  /**
   * List phone numbers
   * List all WhatsApp phone numbers purchased by the authenticated user. By default, released numbers are excluded. 
   * @param status Filter by status (by default excludes released numbers) (optional)
   * @param profileId Filter by profile (optional)
   * @param headers Optional headers to include in the request
   * @return GetWhatsAppPhoneNumbers200Response
   * @throws ApiException if fails to make API call
   */
  public GetWhatsAppPhoneNumbers200Response getWhatsAppPhoneNumbers(@javax.annotation.Nullable String status, @javax.annotation.Nullable String profileId, Map<String, String> headers) throws ApiException {
    ApiResponse<GetWhatsAppPhoneNumbers200Response> localVarResponse = getWhatsAppPhoneNumbersWithHttpInfo(status, profileId, headers);
    return localVarResponse.getData();
  }

  /**
   * List phone numbers
   * List all WhatsApp phone numbers purchased by the authenticated user. By default, released numbers are excluded. 
   * @param status Filter by status (by default excludes released numbers) (optional)
   * @param profileId Filter by profile (optional)
   * @return ApiResponse&lt;GetWhatsAppPhoneNumbers200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<GetWhatsAppPhoneNumbers200Response> getWhatsAppPhoneNumbersWithHttpInfo(@javax.annotation.Nullable String status, @javax.annotation.Nullable String profileId) throws ApiException {
    return getWhatsAppPhoneNumbersWithHttpInfo(status, profileId, null);
  }

  /**
   * List phone numbers
   * List all WhatsApp phone numbers purchased by the authenticated user. By default, released numbers are excluded. 
   * @param status Filter by status (by default excludes released numbers) (optional)
   * @param profileId Filter by profile (optional)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;GetWhatsAppPhoneNumbers200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<GetWhatsAppPhoneNumbers200Response> getWhatsAppPhoneNumbersWithHttpInfo(@javax.annotation.Nullable String status, @javax.annotation.Nullable String profileId, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getWhatsAppPhoneNumbersRequestBuilder(status, profileId, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getWhatsAppPhoneNumbers", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<GetWhatsAppPhoneNumbers200Response>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        GetWhatsAppPhoneNumbers200Response responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<GetWhatsAppPhoneNumbers200Response>() {});
        

        return new ApiResponse<GetWhatsAppPhoneNumbers200Response>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getWhatsAppPhoneNumbersRequestBuilder(@javax.annotation.Nullable String status, @javax.annotation.Nullable String profileId, Map<String, String> headers) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/whatsapp/phone-numbers";

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "status";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("status", status));
    localVarQueryParameterBaseName = "profileId";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("profileId", profileId));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Purchase phone number
   * Initiate purchasing a WhatsApp phone number. Payment-first flow: the user does not pick a specific number. The system either creates a Stripe Checkout Session (first number) or increments the existing subscription quantity and provisions inline (subsequent numbers).  Requires a paid plan. The maximum number of phone numbers is determined by the user&#39;s plan. 
   * @param purchaseWhatsAppPhoneNumberRequest  (required)
   * @return PurchaseWhatsAppPhoneNumber200Response
   * @throws ApiException if fails to make API call
   */
  public PurchaseWhatsAppPhoneNumber200Response purchaseWhatsAppPhoneNumber(@javax.annotation.Nonnull PurchaseWhatsAppPhoneNumberRequest purchaseWhatsAppPhoneNumberRequest) throws ApiException {
    return purchaseWhatsAppPhoneNumber(purchaseWhatsAppPhoneNumberRequest, null);
  }

  /**
   * Purchase phone number
   * Initiate purchasing a WhatsApp phone number. Payment-first flow: the user does not pick a specific number. The system either creates a Stripe Checkout Session (first number) or increments the existing subscription quantity and provisions inline (subsequent numbers).  Requires a paid plan. The maximum number of phone numbers is determined by the user&#39;s plan. 
   * @param purchaseWhatsAppPhoneNumberRequest  (required)
   * @param headers Optional headers to include in the request
   * @return PurchaseWhatsAppPhoneNumber200Response
   * @throws ApiException if fails to make API call
   */
  public PurchaseWhatsAppPhoneNumber200Response purchaseWhatsAppPhoneNumber(@javax.annotation.Nonnull PurchaseWhatsAppPhoneNumberRequest purchaseWhatsAppPhoneNumberRequest, Map<String, String> headers) throws ApiException {
    ApiResponse<PurchaseWhatsAppPhoneNumber200Response> localVarResponse = purchaseWhatsAppPhoneNumberWithHttpInfo(purchaseWhatsAppPhoneNumberRequest, headers);
    return localVarResponse.getData();
  }

  /**
   * Purchase phone number
   * Initiate purchasing a WhatsApp phone number. Payment-first flow: the user does not pick a specific number. The system either creates a Stripe Checkout Session (first number) or increments the existing subscription quantity and provisions inline (subsequent numbers).  Requires a paid plan. The maximum number of phone numbers is determined by the user&#39;s plan. 
   * @param purchaseWhatsAppPhoneNumberRequest  (required)
   * @return ApiResponse&lt;PurchaseWhatsAppPhoneNumber200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<PurchaseWhatsAppPhoneNumber200Response> purchaseWhatsAppPhoneNumberWithHttpInfo(@javax.annotation.Nonnull PurchaseWhatsAppPhoneNumberRequest purchaseWhatsAppPhoneNumberRequest) throws ApiException {
    return purchaseWhatsAppPhoneNumberWithHttpInfo(purchaseWhatsAppPhoneNumberRequest, null);
  }

  /**
   * Purchase phone number
   * Initiate purchasing a WhatsApp phone number. Payment-first flow: the user does not pick a specific number. The system either creates a Stripe Checkout Session (first number) or increments the existing subscription quantity and provisions inline (subsequent numbers).  Requires a paid plan. The maximum number of phone numbers is determined by the user&#39;s plan. 
   * @param purchaseWhatsAppPhoneNumberRequest  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;PurchaseWhatsAppPhoneNumber200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<PurchaseWhatsAppPhoneNumber200Response> purchaseWhatsAppPhoneNumberWithHttpInfo(@javax.annotation.Nonnull PurchaseWhatsAppPhoneNumberRequest purchaseWhatsAppPhoneNumberRequest, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = purchaseWhatsAppPhoneNumberRequestBuilder(purchaseWhatsAppPhoneNumberRequest, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("purchaseWhatsAppPhoneNumber", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<PurchaseWhatsAppPhoneNumber200Response>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        PurchaseWhatsAppPhoneNumber200Response responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<PurchaseWhatsAppPhoneNumber200Response>() {});
        

        return new ApiResponse<PurchaseWhatsAppPhoneNumber200Response>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder purchaseWhatsAppPhoneNumberRequestBuilder(@javax.annotation.Nonnull PurchaseWhatsAppPhoneNumberRequest purchaseWhatsAppPhoneNumberRequest, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'purchaseWhatsAppPhoneNumberRequest' is set
    if (purchaseWhatsAppPhoneNumberRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'purchaseWhatsAppPhoneNumberRequest' when calling purchaseWhatsAppPhoneNumber");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/whatsapp/phone-numbers/purchase";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(purchaseWhatsAppPhoneNumberRequest);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Release phone number
   * Release a purchased phone number. This will: 1. Disconnect any linked WhatsApp social account 2. Decrement the Stripe subscription quantity (or cancel if last number) 3. Release the number from Telnyx 4. Mark the number as released 
   * @param phoneNumberId Phone number record ID (required)
   * @return ReleaseWhatsAppPhoneNumber200Response
   * @throws ApiException if fails to make API call
   */
  public ReleaseWhatsAppPhoneNumber200Response releaseWhatsAppPhoneNumber(@javax.annotation.Nonnull String phoneNumberId) throws ApiException {
    return releaseWhatsAppPhoneNumber(phoneNumberId, null);
  }

  /**
   * Release phone number
   * Release a purchased phone number. This will: 1. Disconnect any linked WhatsApp social account 2. Decrement the Stripe subscription quantity (or cancel if last number) 3. Release the number from Telnyx 4. Mark the number as released 
   * @param phoneNumberId Phone number record ID (required)
   * @param headers Optional headers to include in the request
   * @return ReleaseWhatsAppPhoneNumber200Response
   * @throws ApiException if fails to make API call
   */
  public ReleaseWhatsAppPhoneNumber200Response releaseWhatsAppPhoneNumber(@javax.annotation.Nonnull String phoneNumberId, Map<String, String> headers) throws ApiException {
    ApiResponse<ReleaseWhatsAppPhoneNumber200Response> localVarResponse = releaseWhatsAppPhoneNumberWithHttpInfo(phoneNumberId, headers);
    return localVarResponse.getData();
  }

  /**
   * Release phone number
   * Release a purchased phone number. This will: 1. Disconnect any linked WhatsApp social account 2. Decrement the Stripe subscription quantity (or cancel if last number) 3. Release the number from Telnyx 4. Mark the number as released 
   * @param phoneNumberId Phone number record ID (required)
   * @return ApiResponse&lt;ReleaseWhatsAppPhoneNumber200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<ReleaseWhatsAppPhoneNumber200Response> releaseWhatsAppPhoneNumberWithHttpInfo(@javax.annotation.Nonnull String phoneNumberId) throws ApiException {
    return releaseWhatsAppPhoneNumberWithHttpInfo(phoneNumberId, null);
  }

  /**
   * Release phone number
   * Release a purchased phone number. This will: 1. Disconnect any linked WhatsApp social account 2. Decrement the Stripe subscription quantity (or cancel if last number) 3. Release the number from Telnyx 4. Mark the number as released 
   * @param phoneNumberId Phone number record ID (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;ReleaseWhatsAppPhoneNumber200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<ReleaseWhatsAppPhoneNumber200Response> releaseWhatsAppPhoneNumberWithHttpInfo(@javax.annotation.Nonnull String phoneNumberId, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = releaseWhatsAppPhoneNumberRequestBuilder(phoneNumberId, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("releaseWhatsAppPhoneNumber", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<ReleaseWhatsAppPhoneNumber200Response>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        ReleaseWhatsAppPhoneNumber200Response responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<ReleaseWhatsAppPhoneNumber200Response>() {});
        

        return new ApiResponse<ReleaseWhatsAppPhoneNumber200Response>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder releaseWhatsAppPhoneNumberRequestBuilder(@javax.annotation.Nonnull String phoneNumberId, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'phoneNumberId' is set
    if (phoneNumberId == null) {
      throw new ApiException(400, "Missing the required parameter 'phoneNumberId' when calling releaseWhatsAppPhoneNumber");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/whatsapp/phone-numbers/{phoneNumberId}"
        .replace("{phoneNumberId}", ApiClient.urlEncode(phoneNumberId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("DELETE", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Request OTP
   * Request a new OTP verification code from Meta for a pre-verified phone number. Useful when the initial SMS did not arrive or when re-verifying before the 90-day expiry. 
   * @param phoneNumberId Phone number record ID (required)
   * @param requestWhatsAppVerificationCodeRequest  (optional)
   * @return RequestWhatsAppVerificationCode200Response
   * @throws ApiException if fails to make API call
   */
  public RequestWhatsAppVerificationCode200Response requestWhatsAppVerificationCode(@javax.annotation.Nonnull String phoneNumberId, @javax.annotation.Nullable RequestWhatsAppVerificationCodeRequest requestWhatsAppVerificationCodeRequest) throws ApiException {
    return requestWhatsAppVerificationCode(phoneNumberId, requestWhatsAppVerificationCodeRequest, null);
  }

  /**
   * Request OTP
   * Request a new OTP verification code from Meta for a pre-verified phone number. Useful when the initial SMS did not arrive or when re-verifying before the 90-day expiry. 
   * @param phoneNumberId Phone number record ID (required)
   * @param requestWhatsAppVerificationCodeRequest  (optional)
   * @param headers Optional headers to include in the request
   * @return RequestWhatsAppVerificationCode200Response
   * @throws ApiException if fails to make API call
   */
  public RequestWhatsAppVerificationCode200Response requestWhatsAppVerificationCode(@javax.annotation.Nonnull String phoneNumberId, @javax.annotation.Nullable RequestWhatsAppVerificationCodeRequest requestWhatsAppVerificationCodeRequest, Map<String, String> headers) throws ApiException {
    ApiResponse<RequestWhatsAppVerificationCode200Response> localVarResponse = requestWhatsAppVerificationCodeWithHttpInfo(phoneNumberId, requestWhatsAppVerificationCodeRequest, headers);
    return localVarResponse.getData();
  }

  /**
   * Request OTP
   * Request a new OTP verification code from Meta for a pre-verified phone number. Useful when the initial SMS did not arrive or when re-verifying before the 90-day expiry. 
   * @param phoneNumberId Phone number record ID (required)
   * @param requestWhatsAppVerificationCodeRequest  (optional)
   * @return ApiResponse&lt;RequestWhatsAppVerificationCode200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<RequestWhatsAppVerificationCode200Response> requestWhatsAppVerificationCodeWithHttpInfo(@javax.annotation.Nonnull String phoneNumberId, @javax.annotation.Nullable RequestWhatsAppVerificationCodeRequest requestWhatsAppVerificationCodeRequest) throws ApiException {
    return requestWhatsAppVerificationCodeWithHttpInfo(phoneNumberId, requestWhatsAppVerificationCodeRequest, null);
  }

  /**
   * Request OTP
   * Request a new OTP verification code from Meta for a pre-verified phone number. Useful when the initial SMS did not arrive or when re-verifying before the 90-day expiry. 
   * @param phoneNumberId Phone number record ID (required)
   * @param requestWhatsAppVerificationCodeRequest  (optional)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;RequestWhatsAppVerificationCode200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<RequestWhatsAppVerificationCode200Response> requestWhatsAppVerificationCodeWithHttpInfo(@javax.annotation.Nonnull String phoneNumberId, @javax.annotation.Nullable RequestWhatsAppVerificationCodeRequest requestWhatsAppVerificationCodeRequest, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = requestWhatsAppVerificationCodeRequestBuilder(phoneNumberId, requestWhatsAppVerificationCodeRequest, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("requestWhatsAppVerificationCode", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<RequestWhatsAppVerificationCode200Response>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        RequestWhatsAppVerificationCode200Response responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<RequestWhatsAppVerificationCode200Response>() {});
        

        return new ApiResponse<RequestWhatsAppVerificationCode200Response>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder requestWhatsAppVerificationCodeRequestBuilder(@javax.annotation.Nonnull String phoneNumberId, @javax.annotation.Nullable RequestWhatsAppVerificationCodeRequest requestWhatsAppVerificationCodeRequest, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'phoneNumberId' is set
    if (phoneNumberId == null) {
      throw new ApiException(400, "Missing the required parameter 'phoneNumberId' when calling requestWhatsAppVerificationCode");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/whatsapp/phone-numbers/{phoneNumberId}/request-code"
        .replace("{phoneNumberId}", ApiClient.urlEncode(phoneNumberId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(requestWhatsAppVerificationCodeRequest);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Search available numbers
   * Search for available US phone numbers that can be purchased for WhatsApp Business. Requires a paid plan. Numbers are sourced from Telnyx. 
   * @param prefix Area code to search (e.g., \&quot;212\&quot; for New York) (optional)
   * @param locality City name (e.g., \&quot;New York\&quot;) (optional)
   * @param contains Pattern to match within the phone number (optional)
   * @param limit Maximum results (default 20, max 100) (optional, default to 20)
   * @return SearchAvailableWhatsAppNumbers200Response
   * @throws ApiException if fails to make API call
   */
  public SearchAvailableWhatsAppNumbers200Response searchAvailableWhatsAppNumbers(@javax.annotation.Nullable String prefix, @javax.annotation.Nullable String locality, @javax.annotation.Nullable String contains, @javax.annotation.Nullable Integer limit) throws ApiException {
    return searchAvailableWhatsAppNumbers(prefix, locality, contains, limit, null);
  }

  /**
   * Search available numbers
   * Search for available US phone numbers that can be purchased for WhatsApp Business. Requires a paid plan. Numbers are sourced from Telnyx. 
   * @param prefix Area code to search (e.g., \&quot;212\&quot; for New York) (optional)
   * @param locality City name (e.g., \&quot;New York\&quot;) (optional)
   * @param contains Pattern to match within the phone number (optional)
   * @param limit Maximum results (default 20, max 100) (optional, default to 20)
   * @param headers Optional headers to include in the request
   * @return SearchAvailableWhatsAppNumbers200Response
   * @throws ApiException if fails to make API call
   */
  public SearchAvailableWhatsAppNumbers200Response searchAvailableWhatsAppNumbers(@javax.annotation.Nullable String prefix, @javax.annotation.Nullable String locality, @javax.annotation.Nullable String contains, @javax.annotation.Nullable Integer limit, Map<String, String> headers) throws ApiException {
    ApiResponse<SearchAvailableWhatsAppNumbers200Response> localVarResponse = searchAvailableWhatsAppNumbersWithHttpInfo(prefix, locality, contains, limit, headers);
    return localVarResponse.getData();
  }

  /**
   * Search available numbers
   * Search for available US phone numbers that can be purchased for WhatsApp Business. Requires a paid plan. Numbers are sourced from Telnyx. 
   * @param prefix Area code to search (e.g., \&quot;212\&quot; for New York) (optional)
   * @param locality City name (e.g., \&quot;New York\&quot;) (optional)
   * @param contains Pattern to match within the phone number (optional)
   * @param limit Maximum results (default 20, max 100) (optional, default to 20)
   * @return ApiResponse&lt;SearchAvailableWhatsAppNumbers200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<SearchAvailableWhatsAppNumbers200Response> searchAvailableWhatsAppNumbersWithHttpInfo(@javax.annotation.Nullable String prefix, @javax.annotation.Nullable String locality, @javax.annotation.Nullable String contains, @javax.annotation.Nullable Integer limit) throws ApiException {
    return searchAvailableWhatsAppNumbersWithHttpInfo(prefix, locality, contains, limit, null);
  }

  /**
   * Search available numbers
   * Search for available US phone numbers that can be purchased for WhatsApp Business. Requires a paid plan. Numbers are sourced from Telnyx. 
   * @param prefix Area code to search (e.g., \&quot;212\&quot; for New York) (optional)
   * @param locality City name (e.g., \&quot;New York\&quot;) (optional)
   * @param contains Pattern to match within the phone number (optional)
   * @param limit Maximum results (default 20, max 100) (optional, default to 20)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;SearchAvailableWhatsAppNumbers200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<SearchAvailableWhatsAppNumbers200Response> searchAvailableWhatsAppNumbersWithHttpInfo(@javax.annotation.Nullable String prefix, @javax.annotation.Nullable String locality, @javax.annotation.Nullable String contains, @javax.annotation.Nullable Integer limit, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = searchAvailableWhatsAppNumbersRequestBuilder(prefix, locality, contains, limit, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("searchAvailableWhatsAppNumbers", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<SearchAvailableWhatsAppNumbers200Response>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        SearchAvailableWhatsAppNumbers200Response responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<SearchAvailableWhatsAppNumbers200Response>() {});
        

        return new ApiResponse<SearchAvailableWhatsAppNumbers200Response>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder searchAvailableWhatsAppNumbersRequestBuilder(@javax.annotation.Nullable String prefix, @javax.annotation.Nullable String locality, @javax.annotation.Nullable String contains, @javax.annotation.Nullable Integer limit, Map<String, String> headers) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/whatsapp/phone-numbers/available";

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "prefix";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("prefix", prefix));
    localVarQueryParameterBaseName = "locality";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("locality", locality));
    localVarQueryParameterBaseName = "contains";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("contains", contains));
    localVarQueryParameterBaseName = "limit";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("limit", limit));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Verify OTP
   * Manually verify a phone number by entering the OTP code received via SMS or voice call. This is a fallback for when the auto-verification webhook does not capture the code. Verification is valid for 90 days. 
   * @param phoneNumberId Phone number record ID (required)
   * @param verifyWhatsAppPhoneNumberRequest  (required)
   * @return VerifyWhatsAppPhoneNumber200Response
   * @throws ApiException if fails to make API call
   */
  public VerifyWhatsAppPhoneNumber200Response verifyWhatsAppPhoneNumber(@javax.annotation.Nonnull String phoneNumberId, @javax.annotation.Nonnull VerifyWhatsAppPhoneNumberRequest verifyWhatsAppPhoneNumberRequest) throws ApiException {
    return verifyWhatsAppPhoneNumber(phoneNumberId, verifyWhatsAppPhoneNumberRequest, null);
  }

  /**
   * Verify OTP
   * Manually verify a phone number by entering the OTP code received via SMS or voice call. This is a fallback for when the auto-verification webhook does not capture the code. Verification is valid for 90 days. 
   * @param phoneNumberId Phone number record ID (required)
   * @param verifyWhatsAppPhoneNumberRequest  (required)
   * @param headers Optional headers to include in the request
   * @return VerifyWhatsAppPhoneNumber200Response
   * @throws ApiException if fails to make API call
   */
  public VerifyWhatsAppPhoneNumber200Response verifyWhatsAppPhoneNumber(@javax.annotation.Nonnull String phoneNumberId, @javax.annotation.Nonnull VerifyWhatsAppPhoneNumberRequest verifyWhatsAppPhoneNumberRequest, Map<String, String> headers) throws ApiException {
    ApiResponse<VerifyWhatsAppPhoneNumber200Response> localVarResponse = verifyWhatsAppPhoneNumberWithHttpInfo(phoneNumberId, verifyWhatsAppPhoneNumberRequest, headers);
    return localVarResponse.getData();
  }

  /**
   * Verify OTP
   * Manually verify a phone number by entering the OTP code received via SMS or voice call. This is a fallback for when the auto-verification webhook does not capture the code. Verification is valid for 90 days. 
   * @param phoneNumberId Phone number record ID (required)
   * @param verifyWhatsAppPhoneNumberRequest  (required)
   * @return ApiResponse&lt;VerifyWhatsAppPhoneNumber200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<VerifyWhatsAppPhoneNumber200Response> verifyWhatsAppPhoneNumberWithHttpInfo(@javax.annotation.Nonnull String phoneNumberId, @javax.annotation.Nonnull VerifyWhatsAppPhoneNumberRequest verifyWhatsAppPhoneNumberRequest) throws ApiException {
    return verifyWhatsAppPhoneNumberWithHttpInfo(phoneNumberId, verifyWhatsAppPhoneNumberRequest, null);
  }

  /**
   * Verify OTP
   * Manually verify a phone number by entering the OTP code received via SMS or voice call. This is a fallback for when the auto-verification webhook does not capture the code. Verification is valid for 90 days. 
   * @param phoneNumberId Phone number record ID (required)
   * @param verifyWhatsAppPhoneNumberRequest  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;VerifyWhatsAppPhoneNumber200Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<VerifyWhatsAppPhoneNumber200Response> verifyWhatsAppPhoneNumberWithHttpInfo(@javax.annotation.Nonnull String phoneNumberId, @javax.annotation.Nonnull VerifyWhatsAppPhoneNumberRequest verifyWhatsAppPhoneNumberRequest, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = verifyWhatsAppPhoneNumberRequestBuilder(phoneNumberId, verifyWhatsAppPhoneNumberRequest, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("verifyWhatsAppPhoneNumber", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<VerifyWhatsAppPhoneNumber200Response>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        VerifyWhatsAppPhoneNumber200Response responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<VerifyWhatsAppPhoneNumber200Response>() {});
        

        return new ApiResponse<VerifyWhatsAppPhoneNumber200Response>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder verifyWhatsAppPhoneNumberRequestBuilder(@javax.annotation.Nonnull String phoneNumberId, @javax.annotation.Nonnull VerifyWhatsAppPhoneNumberRequest verifyWhatsAppPhoneNumberRequest, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'phoneNumberId' is set
    if (phoneNumberId == null) {
      throw new ApiException(400, "Missing the required parameter 'phoneNumberId' when calling verifyWhatsAppPhoneNumber");
    }
    // verify the required parameter 'verifyWhatsAppPhoneNumberRequest' is set
    if (verifyWhatsAppPhoneNumberRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'verifyWhatsAppPhoneNumberRequest' when calling verifyWhatsAppPhoneNumber");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/whatsapp/phone-numbers/{phoneNumberId}/verify"
        .replace("{phoneNumberId}", ApiClient.urlEncode(phoneNumberId.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(verifyWhatsAppPhoneNumberRequest);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
